### ISSUE TITLE
feature : could api provide more information about step ?

### ISSUE THREAD

**Issue by dmpvost** [VROOM-Project/vroom#101]
Hi Julien,

Is it possible to provide more informations ( duration & distance ) on step object?
I need this informations, otherwise I would need to make an other call to OSRM to build the full route. 

Or maybe there is not other way, and vroom should in all case make a call to OSRM for full informations?

Normally, the result of table matrix give score duration, so we should be able to get easily duration time for a step. After I could use V=D/T to make some approximation.

 Vroom is very cool & fast ;) 

thank,
Vincent 
(I'm french as you can read, but I wrote in english for everybody)

**Comment by jcoupey** [comment]
Thanks for your feedback. I've been thinking about adding this kind of information too.

When using OSRM, there is always a `table` request at first, and then optional `route` requests after optimization, if the `-g` flag is provided. In that case we return `duration` and `distance` values in `route` objects but we could actually get down to the `step` level.

The best option I see so far would be to add two keys in the `step` object:

- `arrival` would provide time of arrival for a step (`arrival` for the first step would be 0 in the absence of other timing reference)
- `distance` would provide the distance covered so far on the current route when reaching a step (this would be 0 for the first step and equal to the `route` distance for the last step).

As for reusing the matrix values for durations, this is not possible because custom matrices can be provided in input with arbitrary cost values. This is why `cost` and `duration` are separated in the output API even if they are basically the same thing when using OSRM.

**Comment by dmpvost** [comment]
That could be nice!! 
I really need step information. For the moment I will use vroom for order points, and after OSRM I think.

If we could have an arrival_time(sec) and arrival_distance(m) it's really enough on my case

for reusing the matrix, maybe we could add an option like -osrm that allow to use more information about osrm. I agree the API will not be equal if you use an home made matrix, but it could be a first step. (or proof of concept)

**Comment by jcoupey** [comment]
> maybe we could add an option like -osrm

This is more or less what `-g` already does. Providing that flag will trigger a `route` request after optimization to retrieve info that the initial `table` request doesn't provide in the first place (distance and detailed route geometry). It's optional for use-cases where only the ordering is needed and the unnecessary additional requests can be skipped.

The `-g` flag currently operates whatever the matrix source (custom or obtained with OSRM), see #87.

**Comment by dmpvost** [comment]
ok, so is it possible to think about provide more information from osrm when we use -g ? Or whatever provide distance/time one day with vroom to make only one request?

**Comment by jcoupey** [comment]
@dmpvost `arrival` and `distance` keys are added to step objects in #102. Any feedback appreciated if you have time to check out the `feature/add-step-info` branch.

**Comment by dmpvost** [comment]
ok, I will look it,

**Comment by dmpvost** [comment]
For me it's look good!

**Comment by jcoupey** [comment]
Thanks for testing, I'll merge this asap.

**Comment by dmpvost** [comment]
Oh sorry, i read the code, but i didn't test. Is it available on the demo server? If yes i could test and give a feedback

**Comment by jcoupey** [comment]
> Is it available on the demo server?

Not yet, that might take a bit longer. If you really want to try this right now, you'll have to run you own instance.

**Comment by dmpvost** [comment]
Ok, I will try it later, it's not urgent, I'm going to take some holidays soon so I will try when I'm back ;)
thank to add this feature, vroom is really cool

**Comment by jcoupey** [comment]
Landed in `master` with #102.
