### ISSUE TITLE
Implementing Maximum Daily Driving Time for Multi-Day Routes

### ISSUE THREAD

**Issue by maitelorf** [VROOM-Project/vroom#1033]
Hello VROOM Team,

I am currently working on a project that involves planning multi-day routes and I have a specific requirement regarding driving time constraints. I'm aware of the **max_travel_time** parameter, which is great for setting an overall limit on travel time. However, my use case requires the ability to set a maximum driving time per day, as the routes span multiple days.

In more detail, I'm looking for a solution or feature that would allow me to specify a limit on how much time a vehicle can spend driving each day, which is a common requirement due to regulations and driver safety concerns. This constraint would need to reset for each new day of the route.

Could you please advise if there is a current feature in VROOM that would allow me to implement this kind of daily driving time limit? If not, do you have any recommendations or workarounds that I could consider to achieve this functionality? Additionally, is this a feature that might be considered for future development in VROOM?

Any guidance or suggestions you can provide would be greatly appreciated.

Thank you for your time and the excellent work on this tool.

**Comment by maitelorf** [comment]
I'd like to add some more information to my previous query:

Duplicating Vehicles for Each Day: I've thought about duplicating the vehicle for each day of the route. However, the challenge is that I'm not certain where the vehicle would end each day, which makes planning for the next day's start point difficult.

Using Breaks: Another idea was to implement breaks to limit driving time. But this approach seems flawed because the breaks would also restrict the vehicle from making deliveries. According to the regulations, a driver can work (drive, load, unload,...) up to 12 hours a day but is only allowed to drive for 9 hours. The delivery work outside of driving needs to be accommodated.

**Comment by jcoupey** [comment]
There is no way to do exactly this currently. As you mentioned one idea would be to duplicate vehicles (one per day) in which case you can use the default `max_travel_time`, but this is not very flexible because it requires to fix the end/start of the vehicles at night in input.
Using a single vehicle with a TW spanning several days and breaks to model the nights may make more sense in your situation, but then the travel time constraint is on the overall route, not a daily constraint.

There may be ways to come up with a work-around that would make sure solutions are pretty much OK using one or the other approach and the specifics of your problem instances, but that would be quite use-case dependent, not a general solution to the "daily limit".

For the record, this is kind of similar to #918 except the restriction would not apply between tasks at a specific location, but between breaks.
