### ISSUE TITLE
Only some special vehicles can enter in special geofence

### ISSUE THREAD

**Issue by salarnz** [VROOM-Project/vroom#1055]
Hi

I have points in map. some of them are inside of a geofence . and only some special vehicle can enter that geofence ( the geofence is forbiden for all cars and only cars with access license can enter ).

how can i force the algorithm to use that cars with license visits the points in geofence?

thanks.

**Comment by jcoupey** [comment]
You can use `skills` in order to control which tasks can be allocated to which vehicles. Note that this is a way to restrict allocation at the optimization level (e.g. make sure a given vehicle does not handle any task in a given geofence) but this would not guarantee that the vehicle route itself would be fully outside of a given region. This would have to be handled at the routing level.

**Comment by salarnz** [comment]
thanks @jcoupey

**Comment by HeshamMagdy97** [comment]
How can the skills handle this if my vehicle can serve multiple zones?

**Comment by jcoupey** [comment]
> How can the skills handle this if my vehicle can serve multiple zones?

Sounds like the reverse problem: you don't want to avoid zones but restrict vehicles to a number of zones. Just set one skill per zone and list multiple zones/skills per vehicle.
