### ISSUE TITLE
Question regarding the 1.14 release

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#1060]
Is there any outstanding issue that is blocking the 1.14.0 release?

The RC3 has been tagged some time ago and I was wondering when the final release will be out.

Thanks :-)

**Comment by jcoupey** [comment]
Nothing blocking feature-wise, the milestone is empty and I don't want to put any new stuff in, which is why I tagged the release candidates. It's only that I had in mind to do some more additional testing internally and did not got around to doing it with the end of year and other stuff.

Hopefully the release should happen in the next few days/weeks.

**Comment by kkarbowiak** [comment]
> Hopefully the release should happen in the next few days/weeks.

Cool. Thanks!
