### ISSUE TITLE
How is cost calculated?

### ISSUE THREAD

**Issue by DCSnip3r** [VROOM-Project/vroom#1067]
How the cost is calculated in solutions? If I wanted to reproduce the cost calculations using my fixed, per_hour, per_km costs how would I go about doing that? 

For example:
```json
{
  "code": 0,
  "summary": {
    "cost": 18711,
    "routes": 2,
    "unassigned": 0,
    "delivery": [
      4
    ],
    "pickup": [
      2
    ],
    "setup": 0,
    "service": 2100,
    "duration": 18711,
    "waiting_time": 0,
    "priority": 0,
    "distance": 312359,
    "violations": []
  },
  "unassigned": [],
  "routes": [
    {
      "vehicle": 1,
      "cost": 6565,
      "delivery": [
        2
      ],
      "pickup": [
        1
      ],
      "setup": 0,
      "service": 900,
      "duration": 6565,
      "waiting_time": 0,
      "priority": 0,
      "distance": 95606,
      "steps": []
```
The two issues I'm having that led to this question:
In the examples and in my own solutions where no costs are provided, the cost of the vehicle and overall route is equal to the duration. However, that means "service" and "waiting_time" are not included in the total cost calculation. In my case, the cost of service time is generally equal to the per_hour costs of travel (though it can also be different, such as fuel costs in vehicle idling vs in transit). I ultimately want to account for the cost of service, wait time, and breaks in my route. 

I am also curious if the per_km * distance cost calculation contributes to overall cost, or if it is just omitted in this example.

**Comment by jcoupey** [comment]
Cost for a route that lasts $tt$ hours and is $d$ km long, when assigned to vehicle $v$ used in a solution is:

$v.costs.fixed + v.costs.per\\_hour \times tt + v.costs.per\\_km \times d$

Of course this is the theoretical formula and YMMV if you try to reproduce exactly: internally there are some conversions to treat all costs as integers and some tricks to try being efficient while applying the ponderation operations.

> where no costs are provided, the cost of the vehicle and overall route is equal to the duration

That is intended for backward compatibility: the default value for `per_hour` cost is 3600 which you can reason about as if it were a cost in seconds.

> However, that means "service" and "waiting_time" are not included in the total cost calculation

That's correct. Please note that those have never been taken into account even when we were only evaluating duration values as costs. The reason is that basically service time is constant at equal task perimeter. In particular if all tasks are assigned there is nothing to optimize service-wise. This is also shadowed by the fact that before minimizing cost, we aim at maximizing the number of tasks included in the solution.

The waiting time case is subtly different, we simply don't have a way to compute it with the current approach without blowing the algorithmic complexity.

> if the per_km * distance cost calculation contributes to overall cost

Yes, as stated above. The default value for `costs.per_km` is `0` though, so you won't see any contribution to the cost unless you explicitly specify a non-zero value.

**Comment by DCSnip3r** [comment]
Thank you! That completely answers my questions. 

Makes sense that service time and waiting time aren't included in the cost calculation. Just wasn't obvious to me at first because service and waiting time contribute to job arrival times. No need for additional features here, with this information I can simply re-estimate the cost tailored to my application.

Thanks Julien!
