### ISSUE TITLE
How to config strict start for vehicle?

### ISSUE THREAD

**Issue by Ivinnic** [VROOM-Project/vroom#1074]
There are multiple jobs scheduled within specified time windows, and each vehicle also operates within its own time window.
Calculated waiting time is included before the start of the trip.
But I want to start delivery as early as possible, the waiting time should ideally occur between jobs rather than before the start of the trip.

How can I achieve this goal?

PS. Thank you for your hard work!!

**Comment by jcoupey** [comment]
We don't have a way to force start time for vehicles, but even if we had you would not observe a different behavior. That is we'd force the vehicle start, then add some waiting time on the first task and the rest of the route would not change.

The reason for this is that there is something deeper than just start time at stake here: we optimize for route cost (by default total travel time) so the reason we provide a route starting later is that it's cheaper overall.

In your situation, shifting all work earlier would probably mean reordering the route, resulting in a more expensive solution. We'll never return that if we have a choice. Put it differently: you probably want to optimize on completion time first rather than "regular" cost.

**Comment by jcoupey** [comment]
> Is it possible to optimize by finish time

Not out of the box. See #466 for more context and a link to a script doing this that can be relevant in some situations.

This ticket is also very similar to #1019.

**Comment by Ivinnic** [comment]
Thank you so much for explanation and links, it was very helpful!

**Comment by cv-or** [comment]
Hello,

I've also been reflecting on how to enforce a strict start for a vehicle and I wanted to share my modeling approach. The rational is similar to the first message in this issue, meaning that having some waiting time along the route is accepted. The objective is to have a more "conservative" planning approach that leaves some room for unexpected events and potential problems during real-life execution. 

The overall idea is to force each vehicle to perform a dummy job at the vehicle start location. Basically, my idea would be to add, for each vehicle in `vehicles`, a dummy job with:

- `location` = start location of each vehicle
- `time_windows` = [[tw_1, tw2]], where `tw_1` is equal to the earliest time window of the vehicle and `tw_2` is a generic upper bound for the "latest" start of the route. For example, vehicles could start operating at 08:00 but routes have to start before 08:30. In such a case I would have [[08:00, 08:30]]
- `skill` = a dummy skill used to create a 1:1 relationship between the dummy job and its related vehicle
- `delivery` amount = 0, to have no effect on capacity check

Assumption: each vehicle has always a start defined. 

Would this approach work?

**Comment by jcoupey** [comment]
> Would this approach work?

The impact would be that you'd force the planning to start earlier, but this would not change the cost-based ordering after that, for the same reason [mentioned above](https://github.com/VROOM-Project/vroom/issues/1074#issuecomment-1954311705). In other words, it would only change the *time presentation* of the solution, not the vehicle dispatch and task ordering.

This would have the same effect than a simple post-processing of the solution: advance the start step `arrival` by X (pick acceptable value) and adding X to the `waiting_time` for the step after start.

**Comment by cv-or** [comment]
It's all very clear, thank a lot!
