### ISSUE TITLE
Max distance With relevance to tasks

### ISSUE THREAD

**Issue by zahert** [VROOM-Project/vroom#1118]
Hi I have a problem and not sure if VROOM can solve this specific case:-

we have max_distance & max_tasks parameters

The objective is to try to make sure that the distance between each of the tasks does not exceed a certain distance eg. max 5 KM per task. or even decide if the solution must have a certain max distance depending on the trips tasks that I will get out of the solution. is there any workaround to get this result

**Comment by jcoupey** [comment]
> The objective is to try to make sure that the distance between each of the tasks does not exceed a certain distance eg. max 5 KM per task

There is no way to enforce this currently, as the `max_distance` parameter applies to the full route. Can you expand on the use-case/reason to discard route legs over a given threshold?

**Comment by RegularnaMatrica** [comment]
You could get distance matrix between the points (ex. using OSRM) and then put large number (ex. `max_distance`) for values that are higher than 5 in matrix and pass this custom matrix to VROOM.

**Comment by zahert** [comment]
@RegularnaMatrica Can you please elaborate, the proposed solution and how it could impact VROOM solution

**Comment by jcoupey** [comment]
The suggestion as I understand it would be to prefetch the matrices, then modify them by setting a huge cost for values that you want to avoid (e.g. those representing edges over 5km) before feeding them into VROOM. This may lead to solutions with less "long" legs since those would be highly penalized. The drawbacks are:

- a more complex setup (handling and tuning the matrices customization);
- if you change the matrices, you mess with the values returned in output (e.g. distance estimates);
- you still have no absolute guarantee to avoid route legs over 5km (think a situation with an isolated location that is more than 5km away from any other location).

**Comment by RegularnaMatrica** [comment]
@jcoupey I thought that `max_distance` is maximum distance of the entire route, so setting all distances in matrix that are higher than 5 to value `max_distance+1` should make such transitions yield unfeasible solution. You are right that this approach requires much more setup.
