### ISSUE TITLE
ORS max waypoints and vroom request

### ISSUE THREAD

**Issue by msmolka** [VROOM-Project/vroom#1128]
ORS has max waypoints configuration 50 by default. 
There is no configuration for vroom to let know, how many is sent for routing. Some client sending jobs witch are 1 minute long, so it produce error. I believe VROOM should not send more than allowed? So maybe it should have duplicated config to know how many it can sent to ORS?

**Comment by jcoupey** [comment]
> I believe VROOM should not send more than allowed?

VROOM can't tell beforehand if a routing request will be successful, be it due to routing limits or any other problem in your stack. But you'll get the routing error message clearly reported by VROOM upon any routing failure.

I don't think we should do more than that because adding a limitation at VROOM level would mean duplicating configuration and taking ownership on something we do not control (the routing layer). We have to somehow assume that the routing layer will be able to respond.

> ORS has max waypoints configuration 50 by default.

What about simply raising that?

**Comment by msmolka** [comment]
> VROOM can't tell beforehand if a routing request will be successful, be it due to routing limits or any other problem in your stack. But you'll get the routing error message clearly reported by VROOM upon any routing failure.

It is not exactly routing error. It is config error from ORS. And our problem is we cannot control how many waypoints will be sent from vroom to ORS. I just wonder how to mitigate the issue, with many small jobs. Some limit of how many jobs can be assigned to route? 

> > ORS has max waypoints configuration 50 by default.
> 
> What about simply raising that?

After some thought we probably just display user friendly message her on error. The problem is however it is difficult to manual limit request to get result. E.g we cannot throw 1000 jobs and 300 vehicles, as it would then in some scenarios cause error if job is short and over 50 can be assigned for time window.

So user will have to go with limit both jobs and vehicles, but then no automatic smart assignment. We would need to think how to deal with such scenarios.

**Comment by jcoupey** [comment]
> Some limit of how many jobs can be assigned to route?

You could indeed add a `max_tasks` limitation to the vehicles, but that would be reducing model flexibility. So you'd potentially get more expensive solutions just for the sake of complying to the routing limitation. Does not sound really ideal.
