### ISSUE TITLE
Question related to locations in non-loaded maps

### ISSUE THREAD

**Issue by mhosman** [VROOM-Project/vroom#1144]
Hey @jcoupey I have a question. Let's say I have a route and I have a map loaded for Europe but one of the points I load is from South America. That will produce an error like "Could not find route near location [-58.429310,-34.592010]". There's a way to avoid that error and just not include that point in the route?
Thank you so much.

**Comment by jcoupey** [comment]
> There's a way to avoid that error and just not include that point in the route

Sure, just remove the matching task in input and solve again. ;-)

Joking aside, I don't think that would be a good idea to silence the error here and simply ignore one coordinate. Most situations were this error occurs are related to bad data in input (including the infamous lat,lon instead of lon,lat). Removing the error sounds like imposing hours of debugging on the poor newcomer trying to figure out why they get an empty solution (or even worse a partial solution) for no apparent reason.

**Comment by jcoupey** [comment]
Closing as answered.
