### ISSUE TITLE
Does limiting threads available reduce the quality of a solution?

### ISSUE THREAD

**Issue by SimonBradley1993** [VROOM-Project/vroom#1153]
We have been required to limit the number of threads available for Vroom to avoid causing issues when large requests are processed and consume all the CPU - meaning smaller requests are no longer able to be served.

We found that restricting the threads to 1, while keeping exploration level at the default 5 allowed large requests to be completed, in a similar time to before, while not blocking much smaller requests from returning quickly.

One thing we aren't sure on, is whether restricting the threads like this will affect the quality of the solution that Vroom produces. As we have kept exploration at the highest, we would think that the quality isn't affected - but then we would have expected the same larger requests to take significantly longer to process with restricted threads.

Any insights into Vroom's behaviour with this setup would be greatly appreciated!

**Comment by jcoupey** [comment]
Changing the number of threads should only impact computing time, not solution quality (read you should get the *exact* same solution).

> restricting the threads to 1, while keeping exploration level at the default 5 allowed large requests to be completed, in a similar time to before

That is suspicious.

If you're using the default exploration level (5), then we're running 32 independent searches "in parallel". Of course the way that happens depend on how many threads you allow and the actual capacity of your hardware. If you can physically provide 32 threads to run all searches independently, then the completion time is the max of the completion time across all those 32 searches. That is of course also dependent on other things happening on the system, including concurrent solving!

Now if you switch to a single thread, then all searches will be performed in a row, so in the worst case you should expect (up to) a 32x slowdown. In reality this would usually be less than that because the sum of completion times is generally lower than 32 times the max completion time across searches. Now again that is also highly dependent on system load due to other stuff.

**Comment by SimonBradley1993** [comment]
Thanks for your reply. It's good to know the solution that we'll get from Vroom won't be affected.

It is strange that we're not really seeing a slowdown in the time taken to process the solutions. It's the best outcome for us though with making this change!

I'll close this ticket now, thanks for your help.

**Comment by jcoupey** [comment]
Happy to help. You may still want to investigate because such a suspicious behavior is usually a bad smell. The only explanation I can think of is if for some reason in your previous setup you *did not* parallelize anything in the first place...
