### ISSUE TITLE
Exception with large input

### ISSUE THREAD

**Issue by SkyTik** [VROOM-Project/vroom#1204]
I get this error when the number of jobs is about more than 5000

> vroom._vroom.VroomInputException: Too high cost values, stopping to avoid overflowing.

How can I increase this limit?

**Comment by jcoupey** [comment]
Note: issue transferred from `pyvroom` as it is really an upstream question.

This is only indirectly related to the size of the instance. What happens here is that internally we compute an upper bound of the total cost for a solution: this is because when you have very high values in the matrices, then it is possible that the solution cost evaluation would overflow.

My guess is that the bound is high for your instance partly because there are many jobs, but probably also because you may be feeding custom matrices with very high values. Can you confirm?

**Comment by SkyTik** [comment]
So, I think it may be because of the custom matrices, my country's currency has a lot of 0. A stop point may cost 50.000 and a final point may cost more than 140.000, but the total amount is just around 25.xxx.000 for all trips.

Currently, I work around by batching jobs at the same location together, and everything works well. I will do some tests to confirm this question.

**Comment by jcoupey** [comment]
In that case, you may want to scale costs in some way to get them down to smaller values.

Grouping jobs would indeed reduce the value of the bound we compute, so does help on this side. It is also a good idea in general.
