### ISSUE TITLE
Feature : calcul way for only 2 jobs.

### ISSUE THREAD

**Issue by dmpvost** [VROOM-Project/vroom#125]
Hi,

Is it possible to adapt the program for only 2 jobs? 
I know there is no complexity resolution, but it could be nice to use only one API.

Currently I have in my code : 

2 points = use OSRM
2 points > use VROOM 

Any fails -> use google

Thank
Vincent

**Comment by jcoupey** [comment]
You should get exactly that if you submit the starting point as `vehicle` start (with no end) and a  `jobs` array containing only your destination. I wouldn't advise this though because you'll then introduce an unnecessary overhead for *all* your route requests. Also, you'll loose control on any other option you might want to use with the OSRM API, and the ability to retrieve more information from OSRM responses.

**Comment by dmpvost** [comment]
Yes I see, but for simple use case it's nice! 
I'm just trying some options for now. I will continue in future to route request to OSRM or VROOM as you advice
thank! it work

**Comment by jcoupey** [comment]
Glad this works out for you. Feel free to reopen if necessary.
