### ISSUE TITLE
CVRP search operators performance

### ISSUE THREAD

**Issue by krypt-n** [VROOM-Project/vroom#144]
The CVRP local search operators spend a lot of time in calls of `is_valid()`. The `is_valid`-functions are not as cheap as one might expect since comparing the capacities/amounts requires memory allocations (e.g. `operator+` creates a new vector to store the result in). I'm thinking (and a small test suggests) that the local search operators could be made a lot faster if one gets rid of the allocations by moving to element-wise capacity comparisons (i.e. first check if the first amount is smaller than the capacity, then check if the second amount is smaller than the capacity and so on).

I'd suggest implementing [Expression templates for `amount`](https://en.wikipedia.org/wiki/Expression_templates) which would allow the `is_valid`-checks to stay simple and readable but would allow to get rid of the memory allocations. I could take a look at implementing that, if this seems like a sensible change to you.

**Comment by jcoupey** [comment]
@krypt-n thanks for investigating this! The way the `amount` class is currently implemented makes a good job of abstracting the arithmetic operations for a simple use in `is_valid`, but I was not actually aware of this drawback.

It makes definitely sense to try improving that part, and I'd expect the impact to be quite significant as the `is_valid` calls are the front-facing checks in the core part of the local search. Also this is not only relevant for CVRP but will also impact any other variant with capacity constraints. It would be great if you can give it a try if you have the implementation layout in mind, especially if managing to keep usage simple.

One thing to keep in mind for the current arithmetic requirements on amounts is that we rely on all comparison checks to pass with empty amounts, see https://github.com/VROOM-Project/vroom/issues/97#issuecomment-380197094.

**Comment by krypt-n** [comment]
I've got a first working version with quite promising results:

```
origin/master:
../bin/vroom -t 1 -i ../bin/X-n344-k43.json  1.26s user 0.00s system 99% cpu 1.278 total

branch:
../bin/vroom -t 1 -i ../bin/X-n344-k43.json  0.67s user 0.01s system 99% cpu 0.678 total
```

the solution stays the same.

**Comment by jcoupey** [comment]
Quick post-merge report. All CVRP instances with 8 threads, total computing times comparisons:

| `x` | 4463af7 | 3979d76 | Gain (%) |
|:------------------|------------:|---------:|---------:|
| 0 | 2m23.429s | 0m48.951s | -65.9 |
| 1 | 4m21.055s | 1m34.196s | -63.9 |
| 2 | 10m15.670s | 3m13.119s | -68.6 |
| 3 | 14m31.113s | 4m21.838s | -69.9 |
| 4 | 27m20.504s | 8m18.420s | -69.6 |
| 5 | 53m57.172s | 15m32.191s | -71.2 |

Numbers from https://github.com/VROOM-Project/vroom/pull/146#issuecomment-413008946 are further improved by the latest commits. I updated the benchmarks page in the wiki and will update gain in the changelog.

@krypt-n kudos for your work on this! :100:

**Comment by krypt-n** [comment]
That's cool :+1: 

I glanced at some old benchmarks I ran on the CVRPLIB A instances and it appears that although vroom is currently significantly faster than e.g. VRPH or jsprit, its gap to the best solution is almost always larger. So I guess we could use the gained time to improve the CVRP solving a bit.

**Comment by jcoupey** [comment]
> we could use the gained time to improve the CVRP solving a bit.

Possibly, but not necessarily straightforward since the solving scheme was essentially designed for speed (with scaling in mind). I see two ways to try and do that:

1. Tune parameters for existing approach.
2. Deepen solution space exploration in some way.

Option 1 is actually what already happens [here](https://github.com/VROOM-Project/vroom/blob/master/src/problems/cvrp/cvrp.cpp#L42-L91) for exploration levels. I tuned that to maintain reasonable computing times with several depth/quality ratios. Of course the big reduction in computing time means we can adjust this tuning towards more depth. Worth a try even if I suspect the quality gain will become marginal at some point.

Option 2 is more tricky. For example implementing other local search operators with a higher complexity will raise very high computing times even for middle-sized instances - I did try that at some point. Probably possible (and easier now) but requires a good balance.
Another option I can think of would be to also use the heuristic from https://github.com/VROOM-Project/vroom/issues/137 in addition to the existing clustering scheme to gather additional (hopefully better) solution. There is nothing in the heuristic that would prevent it's use in the CVRP case and I suspect it would behave quite well in the single-depot context of the benchmarks we use.

**Comment by jcoupey** [comment]
@krypt-n I'd be quite interested to have some insights on the results you got with VRPH or jsprit on the CVRPLIB classes. Do you think you could share some figures?

**Comment by krypt-n** [comment]
Sure, if you're alright with CSV data. My gnuplot scripts for the files are producing some sort of tex input and I can't figure out how to get them to produce readable output right now.

[A-costs.txt](https://github.com/VROOM-Project/vroom/files/2346273/A-costs.txt)
[A-costsrelative.txt](https://github.com/VROOM-Project/vroom/files/2346274/A-costsrelative.txt)
[A-times.txt](https://github.com/VROOM-Project/vroom/files/2346275/A-times.txt)
[B-costs.txt](https://github.com/VROOM-Project/vroom/files/2346276/B-costs.txt)
[B-costsrelative.txt](https://github.com/VROOM-Project/vroom/files/2346277/B-costsrelative.txt)
[B-times.txt](https://github.com/VROOM-Project/vroom/files/2346278/B-times.txt)

(Renamed csv files, github is a bit silly)

* A/B-times is the runtime in seconds. Timelimit of 15mins per instance. That's why symphony didn't complete all instances.
* This is without any parameter tweaking. All solvers are used naively "out of the box". Obviously one could get better or faster results by doing that.
* vrph is vrph_rtr
* Times include stuff like process startup, it's not measured very professionally.
* Although I have still have binaries/scripts lying around, I am not confident that I could reproduce everything. Also I am not completely sure whether I made sure that all solvers use the correct distance matrix.
