### ISSUE TITLE
Reproducible solutions

### ISSUE THREAD

**Issue by krypt-n** [VROOM-Project/vroom#145]
As discussed in #142 solutions should be reproducible on different machines. Different machines means different compilers and standard-library implementations in particular. Even more specific:

* Vroom should not rely on the iteration order of a hashmap/hashset
* Vroom should not rely on the ordering of the input (This is relevant from an end-user perspective. It'd be kinda hard to explain why suddenly it is no longer possible to assign all jobs, just because the jobs are send to vroom in a different order)
* Vroom should not rely on the ordering of elements with the same cost after unstable sorting.
* Vroom should not rely on the order in which threads finish their calculations

(This are the things I can think of off the top of my head, there may be more)

The implemented algorithms need to be analyzed to see if they rely on any implementation specific behavior.

**Comment by jcoupey** [comment]
I agree that this is a good target, if only for debugging purpose or for consistency, in particular on benchmarks. Yet we should keep in mind that there are other "external" factors that might impact results for real-life use cases: using different OSRM versions, with different/customized routing profiles, running on different OSM datasets etc.

Another concern is that we should check that this does not increase computing time too much.

> Vroom should not rely on the order in which threads finish their calculations

And on the number of threads allocated. This is normally already the case as the CVRP approach only basically runs separate solving processes in parallel, and multi-threading for TSP is just a matter of splitting the operators lookup. In both cases the subsequent choices are deterministic, in particular with draws.

> Vroom should not rely on the ordering of elements with the same cost after unstable sorting.

Probably requires to go through the codebase and make sure we use stable sorts.

> Vroom should not rely on the iteration order of a hashmap/hashset

This has been started in #142. Requires to spot current uses of `unordered` data structures and see whether ordering is at stake, hoping this will not defeat the purpose of using `unordered_*` in the first place...

> Vroom should not rely on the ordering of the input

Probably the trickiest part. For now everything rests on the order in which jobs and vehicles are defined throught `input::add_job` and `input::add_vehicle` (be it from the json input parser or directly from C++ when using libvroom). As far as I can see, we would have to implement a total order on jobs and vehicles and use that to store them in a `std::set` instead of a `std::vector` during problem definition, then we'd have to copy the sets to `std::vector`s for random access through the solving. 

The ordering question would be simple if we enforced unique ids, but I'm reluctant to do so for vehicles due to https://github.com/VROOM-Project/vroom/issues/136#issuecomment-406896877. Avoiding unique ids would mean having to define an ordering based on all properties (ids, location, skills, amounts etc.), some of them being optional. And it should also be relevant in case a custom matrix is provided and other keys are expected/possible (e.g. `location` vs `location_index`).

Happy to hear any comment or idea on this!

**Comment by DCSnip3r** [comment]
Hi I'm curious to hear more about this. My question has to do with how vehicles are chosen when there are multiple vehicles that can do the same job, and if vehicle selection varies between different runs of a solution on the same machine. 

- Does the ordering of the input jobs have an impact on which vehicles are used to solve a problem? Does the first vehicle you define try to do the first stops you feed in? 
- What impact does the ordering of the input have? 
- How does the program decide which stops vehicle 1 will do?

**Comment by jcoupey** [comment]
First note that this ticket was rather initiated by the concerns of different results on different machines/standard-library implementations.

> if vehicle selection varies between different runs of a solution on the same machine

The entire search process is totally deterministic. You'll get the exact same *solution cost* for different runs on the exact same input and the same machine. The only way the solution itself could be different is if the same cost is achieved by different searches/set of routes, and the threads terminate in a different order. Having two solutions with the exact same cost in a real-life scenario where all travel times are known down to the second sound very unlikely though.

Now for the vehicles/jobs in input, order could have an impact but my guess is that this would really only hit at the very margin. 

Initial vehicle ordering is decided in the heuristics:

1. For an homogeneous (think single-depot) situation, we [sort vehicles](https://github.com/VROOM-Project/vroom/blob/24a6dd54175f40f2fb58be1c2ff76dd951a957f8/src/algorithms/heuristics/solomon.cpp#L37-L47) based on capacity first, then available time, using a stable sort.
2. For an heterogeneous situation, we [pick the next vehicle to use](https://github.com/VROOM-Project/vroom/blob/24a6dd54175f40f2fb58be1c2ff76dd951a957f8/src/algorithms/heuristics/solomon.cpp#L464-L487) based on number of closest jobs, then capacity, then available time.

In both cases, a difference could theoretically occur if you have ties on those criteria **and** ties vehicles are submitted in a different order **and** ties vehicles differ on other aspects that could affect solving (the only one off the top of my head being `skills`).

Job insertion is decided:

1. To seed an empty route based [on various options](https://github.com/VROOM-Project/vroom/blob/24a6dd54175f40f2fb58be1c2ff76dd951a957f8/src/algorithms/heuristics/solomon.cpp#L97-L134), e.g. job with higher amount, earliest deadline, furthest, nearest.
2. To fill in a route under construction, based on [a mix](https://github.com/VROOM-Project/vroom/blob/24a6dd54175f40f2fb58be1c2ff76dd951a957f8/src/algorithms/heuristics/solomon.cpp#L228-L229) of the cost of addition and the cost of reaching to that job from an empty route.

In both situations, the retained job is the first one (in input order) that matches the best choice. Ties and different input ordering could make a difference, but the odds are low, at least for a travel-time related evaluation in a real-life scenario.

So maybe I'm being a bit optimistic here but I don't think this is really a problem for use in the field. A simple step to try and evaluate this would be to use reference instances, randomly shuffle vehicles/jobs in input a number of times while comparing solutions. I don't really have time for this right now but would be interested in any feedback.

**Comment by jcoupey** [comment]
Let's face it, this is stale, and maybe it's not a big deal. Probably our solutions are "reproducible enough" so that this is actually not a strong concern, even for academic/benchmark reproducibility sake. I'd argue that IRL no one cares.

Last nail in the coffin: if a PR achieving total reproducibility meant hurting performance (e.g. by not using `unordered_*` data structures whenever possible) I would not merge it.
