### ISSUE TITLE
Calculate gain ratio

### ISSUE THREAD

**Issue by nielsenko** [VROOM-Project/vroom#149]
If the job sequence in the posed problem, actually is a valid solution to the problem, I think it would be cool if vroom would calculate the gain ratio for cost, distance and duration compared to the input sequence.

**Comment by jcoupey** [comment]
I can see how any job sequence in input is a valid solution for a TSP, but describing a solution to a multi-vehicle problem would require more than just an ordered sequence.

Would this use-case come down to being able to by-pass the optimization phase to "just" recompose  an existing solution, thus providing missing indicators in output?

**Comment by jcoupey** [comment]
The reason I mentioned bypassing the optimization is because I though you were trying to evaluate existing solutions from other sources (e.g. manually designed). I guess this could be useful in some cases.

> see how much it improves on a previous solution, from a previous version of vroom or with a more aggressive -x

We don't do improvement to existing solutions so far. As for the `-x` comparison, it can be done completely outside of VROOM based on the reported indicators, provided you keep the different solutions at hand. For what it's worth, there are a bunch of scripts in the [vroom-scripts](https://github.com/VROOM-Project/vroom-scripts/tree/master/benchmarks/CVRP) repo that allow to compare individual results and global indicators when batch solving a set of problems. They're designed to work out of the box on benchmarks from the literature but you can adjust them to run on your own set of problems.

**Comment by nielsenko** [comment]
Thanks, I will look into the scripts. Anyway, it was just an idea I had while playing with vroom. Feel free to close the issue.
