### ISSUE TITLE
Is vehicle capacity configurable?

### ISSUE THREAD

**Issue by Rajavelu** [VROOM-Project/vroom#158]
hi,
I am new to VROOM project. How to config max capacity for a vehicle?
For example, Refer below image, Each vehicle can contains max 4 points only. Is it possible?

<img width="1435" alt="screen shot 2018-09-11 at 3 28 36 pm" src="https://user-images.githubusercontent.com/3033600/45353467-7e389180-b5d8-11e8-8a30-de20f1d81082.png">

**Comment by jcoupey** [comment]
If your question is to know if there is a way to do that directly from the website UI, then no you can't. 

What you should do in order to manage capacity restrictions is format your own json input file (or even reuse one of the queries generated from the UI) and make sure you set `amount` and `capacity` values for `jobs` and `vehicles` (see [API](https://github.com/VROOM-Project/vroom/blob/release/1.2/docs/API.md)). Then you can solve the problem directly or even feed it to the frontend.

The frontend actually does [exactly this](https://github.com/VROOM-Project/vroom-frontend/blob/78e30e99b767a9a92b6462882cc345b75660379c/src/utils/solution_handler.js#L18-L26) when no capacity are provided, in order to split the load between provided vehicles.

**Comment by jcoupey** [comment]
@Rajavelu I'm closing this issue, feel free to re-open if you have any further question.
