### ISSUE TITLE
Scalability Test 

### ISSUE THREAD

**Issue by Eichenherz** [VROOM-Project/vroom#185]
I'm trying to test the scalability of VROOM. I have 14k entries. But they are in excel & I'm having a hard time transforming them to a VROOM json.  I need 14k jobs & 37 vehicles. Could you please offer a quick alternative ? Or give me some pointers ? I don't want to spend time writing code , because I want this to be a quick test :)
Thanks in advance !

**Comment by Eichenherz** [comment]
I'm not concerned with capacity,skill or time windows. Just how VROOM scales

**Comment by jcoupey** [comment]
This might depend on your tools of choice, but what I would do is parse a csv version of the jobs file with a simple python script to collect coordinates. You could probably reuse [that function](https://github.com/VROOM-Project/vroom-scripts/blob/9e28b904c0de40818d902bdbbf88f7fe2af2b5d9/src/utils/format_input.py#L5-L25) that will format a json problem from a pair of lon/lat arrays, so you would only have to handle the parsing.

Another option would be to feed a list of lat,lon pairs (one on each line) in the frontend and copy the generated request from your browser dev tools. You'd have to run your own instance of [vroom-frontend](https://github.com/VROOM-Project/vroom-frontend/) to get over the 100 points limitation. Also in that case there is normally a reverse geocoding request to get an address. You probably want to bypass that when using a 14k line file.

**Comment by jcoupey** [comment]
Couple thoughts:

- if you don't impose any capacity or skill or time-window restriction with identical vehicles, you'll get a one-vehicle solution to a giant TSP (because that's cheaper)
- check out the `-x` flag, for huge instances you probably want to start with 0 (fastest) and then decide to increase depending on the quality/computing time trade-off you need

**Comment by jcoupey** [comment]
@Eichenherz did you manage to format your 14k-jobs instance?

**Comment by hyzajabada** [comment]
Hello @jcoupey. 

I'm very much interested in using VROOM in my own application and have come across this question. I'm going to do some performance tests myself and will post the results here once I've got them in order, however one thing is puzzling me. You mentioned that if identical vehicles are used then the result will be just for one vehicle - is there any way to change this? I understand that it's due to the optimization algorithm, however using the demo front-end, whenever I specify say 50 locations and 5 vehicles, I end up having 5 different routes. Are there any limitations imposed implicitly that I'm not aware of? It's possible that I will put some time windows, skills etc. later on, however right now I just want to quickly generate some optimized routes. 

Currently I'm using 6 vehicles and about 300 locations, which isn't big, but once I've got my code up and running I will try to solve the problem for as much as 200 vehicles and 20000 locations. Definitely will let you know how that went once I'm ready.

**Comment by jcoupey** [comment]
>  if identical vehicles are used then the result will be just for one vehicle

That's true in a single-depot setting (all vehicles starting and ending at the same place) **if** no constraint make it necessary to use several vehicles. Not the case as soon as you start adding capacity, skills or timing restrictions.

> Are there any limitations imposed implicitly that I'm not aware of?

Yes, [there is](https://github.com/VROOM-Project/vroom-frontend/blob/master/src/utils/solution_handler.js#L18-L26). The rationale is that if someone manually defines 5 vehicles in the demo, they expect to split the load between them. So if no capacity constraint is defined otherwise, we enforce them to make sure several vehicles will be used.

@hyzajabada looking forward for the feedback on your tests!

**Comment by jcoupey** [comment]
@Eichenherz @hyzajabada any update on your tests? I don't mind leaving this ticket open for future feedback but please let me know if we should close.

**Comment by hyzajabada** [comment]
@jcoupey I'm planning to run them at some point, but I'm incredibly busy at the moment so don't know when I'll be able to. As far as I'm concerned you can close it, I assume there is an option to re-open if and when I get to it?

**Comment by jcoupey** [comment]
@hyzajabada thanks for your answer, I was just asking in order to close if you had given up on this. It's best in my opinion to leave it open if it tracks something that is planned, even remotely.

**Comment by jcoupey** [comment]
Closing as stale. @hyzajabada @Eichenherz feel free to re-open if required.
