### ISSUE TITLE
Additional OSRM-Parameter

### ISSUE THREAD

**Issue by dooley** [VROOM-Project/vroom#194]
How can one use additional parameter for OSRM? Sometimes it is necessary to add them, especially to allow u-turns in some cases. We got a routing-problem, see [https://github.com/Project-OSRM/osrm-backend/issues/5333](url), where the solution is to add "continue_straight=false". We don't want to use it all the time, only when the request fails without and then try again with it. If not possible, may i ask to implement as feature request?

**Comment by PattyDePuh** [comment]
In a summary: With the given optimization model of single points representing jobs and without the information about the directional orientation it is unlikely to implement the requested feature.

If to make VROOM sensitive for u-turn restrictions and assuming, that jobs are not located directly on street junctions (but on the routes themeselfs), it is necessary to add two additional dimension to the matrix to determine the directional orientation - resulting in a **4-dimensional** matrix[A][Oa][B][Ob]. 

Such a matrix with the 2 location-dimensions (A,B) plus orientation (Oa,Ob) could return the distance to travel from job A to job B with intelligence from which direction (Oa) the traveler arrived to job A  and from which direction (Ob) of the street the traveler has to arrive at job B. By knowing the preceeding job, we can determine the directional orientation. (Aligning the Orientations of the jobs is an optimization-problem by itself btw.).
In case of present u-turn restrictions it might be the case, that the route from job B to job C alters and the distance probably gets bigger in comparison to the direct route from B to C. 

In particular routing models for bulky vehicles (like in refuse collection) it might be a welcome addition, if such described multi-dimensional matrix is provideable by OSRM itself - as building such a matrix manually  requires an overhead of multiple route-requests. And even if the named feature from OSRM is given: implementation will requre deep alterations inside core optimization modules,

**Comment by dooley** [comment]
I don't see the issue here. What's the problem to just pass a given VROOM command line parameter to OSRM? VROOM should not handle with it, just pass thru OSRM.

**Comment by jcoupey** [comment]
@PattyDePuh you're right that taking orientation into account **within** the optimization process would be somehow challenging. Also there is no such thing as an orientation option for OSRM `table` requests to even retrieve the different matrices you mention. But I think the original question was more about the options that are passed to OSRM for the `route` requests performed **after** solving.

@dooley can you expand on how https://github.com/Project-OSRM/osrm-backend/issues/5333 impacts your VROOM usage?

I'm confused because the current `route` requests performed by VROOM already set the `continue_straight` option to `false` [for `osrm-routed`](https://github.com/VROOM-Project/vroom/blob/fd087ef2932b4b9cbd0b98e8945650c5782d200f/src/routing/routed_wrapper.cpp#L149-L150) and [for `libosrm`](https://github.com/VROOM-Project/vroom/blob/fd087ef2932b4b9cbd0b98e8945650c5782d200f/src/routing/libosrm_wrapper.cpp#L85-L91). This  is precisely a way to make sure that travel times retrieved after solving using the `route` requests are consistent with travel times from the `table` request that are used for solving.

**Comment by dooley** [comment]
@jcoupey Now i'm confused, i didn't know the param is already set. The 3 coordinates are from a much bigger request, where VROOM got a "NoRoute" from OSRM. I'll build a smaller testcase for VROOM and come back later.

**Comment by dooley** [comment]
Sorry for confusion. I mixed up up some tools in our chain :-( The error happened in another tool we use. I'll close the ticket.
