### ISSUE TITLE
Stops on a way street are not optimized

### ISSUE THREAD

**Issue by 123bistami** [VROOM-Project/vroom#220]
Stops on a one way street are not optimized, for example it will be faster to run house number 7,8,9,12,11,22 vroom result is than run number 9,7,8,12,22,11 in a one way street route circle you many times Example drive to one way street visit number... and than visit the street again visit the number...

**Comment by jcoupey** [comment]
It's hard to guess what the problem is without more details on your input. Can you share a file so I can try to reproduce the problem?

**Comment by jcoupey** [comment]
Closing as stale. @123bistami feel free to reopen if you can provide some more details.

**Comment by braktar** [comment]
@123bistami Tell me if I'm wrong, but in the cases I have in mind, your route have to travel through this one way street multiple times due to the repartition of the jobs.

So, from the point of view of the resolution serving those points in one row or in multiple times doesn't matter.

A simple bypass is to modify the distance matrix to encourage the long trips. Experientially it works pretty good with d + 20*sqrt(d) [d any distance in your matrix]
