### ISSUE TITLE
Balancing route times

### ISSUE THREAD

**Issue by smil78** [VROOM-Project/vroom#225]
Hello,
I was thinking about balancing route times, let's say we have 3 vehicles with 8-hour work time (8-16 for example), and the routes came up as: vehicle 1 took 7 hours, v2 took 3h, and v3 is 8h
In order to balance work times my thought is to take the average time (6 hours in this case) and limit work times for each vehicle on this value (8-14 in this case). Is there any downsides in this?

Thanks.

**Comment by jcoupey** [comment]
The current optimization objective is overall travel time and there is no simple way to take into account route time balance *as an objective*.

Fiddling with the vehicle time windows as you suggest would basically work to still optimize on overall travel time while reducing route length differences. The only downside I can think of is that since you'll be pushing tighter constraints, you'll probably get a more expensive solution (in term of overall travel time). What I'd suggest to easily evaluate this would be to solve the same problem with different thresholds/flexibility for vehicle time windows (8 hours, 7.5 hours, 7 hours, 6.5 hours etc.). Then compare both balance and overall cost to see what works for you.

**Comment by jcoupey** [comment]
Looks like this has been answered, so closing now. Feel free to re-open if required.

**Comment by atanas0** [comment]
> The only downside I can think of is that since you'll be pushing tighter constraints, you'll probably get a more expensive solution

Also in some cases making time windows tighter will lead to shipments being left out despite remaining capacity and time since vehicles' time windows stop overlapping with some of the shipments' time windows at some point.
