### ISSUE TITLE
Is it possible to set a time limit for the solver?

### ISSUE THREAD

**Issue by MingyiZhangQimia** [VROOM-Project/vroom#248]
Hi, is it possible to set a time limit for the solver, such that the solver will give the best result it can find during that time?

**Comment by jcoupey** [comment]
No, there is no such option at the moment because the solving approach is consistent as a whole and stopping it prematurely could lead to low-quality results. Also we try to be fast enough to not need it. ;-)

We have a way to manage the trade-off between solution quality and computing time though. See [the `-x` flag](https://github.com/VROOM-Project/vroom/wiki/Usage#complete-usage-and-options-list-for-v140). Other aspects like number of threads (`-t`) also of course come into play.

Did you experience too long computing times on some instances? Can you share a bit more on your use-case (problem type/constraints, problem size in term of number of jobs and vehicles, expected or experienced computing times) in order to have a better view on your question?

**Comment by jcoupey** [comment]
Looks like this has been answered. Feel free to reopen if required.
