### ISSUE TITLE
TSP with no start or end depot for the vehicle

### ISSUE THREAD

**Issue by senhalil** [VROOM-Project/vroom#258]
Hello,
We are solving a TSP problem in which there is no start nor end depot for the vehicle (which is not supported by vroom)
To circumvent the depot limitation, we created an auxiliary node which has zero distance to all other nodes and set this node as the start node of the vehicle. 
However, we are not sure if our "trick" is supported or not. Can you see any issues with this approach?
If not, I am willing to create a patch for vroom if you would like me to do so.
Cheers,
h.

**Comment by jcoupey** [comment]
The "start-only" case for TSP is already hacky, as we actually still compute a round trip while [making sure](https://github.com/VROOM-Project/vroom/blob/4486868821f9402d73f22f7105e7f7c085c406ff/src/problems/tsp/tsp.cpp#L67-L75) the last cost (any end job to the start) is zero. Then we present the tour [from the start](https://github.com/VROOM-Project/vroom/blob/4486868821f9402d73f22f7105e7f7c085c406ff/src/problems/tsp/tsp.cpp#L239) and [pop it](https://github.com/VROOM-Project/vroom/blob/4486868821f9402d73f22f7105e7f7c085c406ff/src/problems/tsp/tsp.cpp#L255) to only show jobs.

The difference you're making is that the cost from the start to any job will **also** be zero so there will be a node in the TSP that can be visited at any time in the tour at zero cost. This may generate some wild moves during the local search, but the cost evaluation should always stick to what you want to model. So as far as I can tell at first sight, it should work.

Note that you'll get a dummy "start" step in output for your vehicle.

I'd be interested to get some feedback on how it turns out in your experiments, and what you can achieve with this.
