### ISSUE TITLE
[v1.4] Wrong quantity key

### ISSUE THREAD

**Issue by braktar** [VROOM-Project/vroom#268]
While trying to update Vroom, I followed the tag v1.4.

I've tried to update the keys I used. But the key 'pickup' wasn't defined in this version.
The size of quantities and capacities are compared. Even if one of those entities doesn't exist.
This has generated a SegFault. The problem is fixed in v1.5 rc1. But here is a minimal example to keep track of it:
`{
  "vehicles": [
    {
      "id": 0,
      "start_index": 2,
      "end_index": 2,
      "capacity": [
        3000
      ],
      "time_window": [
        900,
        57600
      ]
    },
    {
      "id": 0,
      "start_index": 2,
      "end_index": 2,
      "capacity": [
        550
      ],
      "time_window": [
        900,
        57600
      ]
    }
  ],
  "jobs": [
    {
      "id": 0,
      "location_index": 0,
      "service": 0,
      "priority": 4,
      "anykey": [
        500
      ]
    },
    {
      "id": 1,
      "location_index": 1,
      "service": 0,
      "priority": 4,
      "anykey": [
        500
      ]
    }
  ],
  "matrix": [
    [0,    1067, 936],
    [1059, 0,    627],
    [722,  712,  0  ]
  ]
}
`

**Comment by jcoupey** [comment]
We normally check for consistent lengths between vehicle `capacity` and job `amount` arrays (here having no `amount` for jobs defaults to creating an empty array). The [check for v1.4](https://github.com/VROOM-Project/vroom/blob/release/1.4/src/structures/vroom/input/input.cpp#L174-L187) relies on a `_locations` vector being empty to spot the first call to the check. It turns out this is flawed when using a custom matrix without coordinates for jobs as in that case this vector always stays empty...

**Comment by jcoupey** [comment]
As mentioned above, this is fixed in `v1.5-rc.1` as checks for amount size consistency have been refactored, so I don't think it's worth issuing a patch for the `v1.4` series. Let's just keep this ticket open until `v1.5` is published (and to use as a reference for anyone hitting the same issue with `v1.4`).

@braktar thanks for reporting!
