### ISSUE TITLE
How to run vroom on windows?

### ISSUE THREAD

**Issue by ifle** [VROOM-Project/vroom#269]
How to run vroom on windows?

**Comment by jcoupey** [comment]
You should simply compile the code with any C++ compiler/toolchain you have available, using the provided makefile. I have no experience with such tools in windows so I can't provide more feedback myself.

We've had a couple of successful windows compilation reports after some troubleshooting in #60 and #207. Of course we only hear about the problems, so there may be users out there that built successfully out-of-the-box under windows...

**Comment by ifle** [comment]
Unfortunately I'm not familiar with C++ and it took me a time to get it to compile. I don’t know why, the ERROR class is conflicted with some another ERROR type. I've renamed it to VROOM_ERROR as also some several c++ files with the same names.

**Comment by jcoupey** [comment]
This is weird, the [definition](https://github.com/VROOM-Project/vroom/blob/70deadafbab175336bce210c6ae5232d26cd8ffb/src/structures/typedefs.h#L63) already happens under a dedicated namespace so it's actually `vroom::ERROR` in order to avoid exactly this kind of conflict.

Anyway feel free to close here if there is no more action/info required.
