### ISSUE TITLE
Where's the verbose flag?

### ISSUE THREAD

**Issue by unguul** [VROOM-Project/vroom#280]
I was getting the following on v1.4.0
```json
{"code":1,"error":"basic_string::_M_construct null not valid"}
```
so I started looking around for a verbose/debugging flag to `vroom` but did not find any. I did find some issues and PRs that vaguely mentioned logging but that lead nowhere.

Perhaps a command line flag that would make `vroom` crash loudly would be appropriate?

Fortunately(?), my error just went away after restarting the osrm instance but that error message said nothing to lead me in that direction.

**Comment by jcoupey** [comment]
We used to have a verbose flag in the early days, mostly to keep track of how the solving approach went on and output some basic info during solving. It came to a point where it was really messy and not really usable any more with the introduction of concurrent solving, so I removed it.

Now regarding your error with code 1 ("internal error"), the only place where it can come from is [this catch](https://github.com/VROOM-Project/vroom/blob/release/1.4/src/main.cpp#L197) which is unfortunately the last catch-all for unhandled errors. It's purpose is precisely to avoid a crash by reporting the error within a json response. The exception details (`e.what()`) are also logged to the error output, but unfortunately there is not much more we can do here even with more verbosity.

A way to debug this would be to remove the last `catch` to have `vroom` crash within a `gdb` session and trace back the exception.

> Fortunately(?), my error just went away after restarting the osrm instance

Maybe this is due to some unexpected stuff in the previous OSRM response triggering an unhandled parsing error. But it does not look like we'll be able to easily reproduce?

**Comment by unguul** [comment]
> But it does not look like we'll be able to easily reproduce?

@jcoupey  Indeed.

However, I did notice some weird behavior on some other servers I use, unrelated to `vroom` or OSRM but they do all have 1 particular change in common which caused other to require a reboot in order to function properly. Perhaps we could extend the error handling of `vroom` to report issues in communicating with OSRM more clearly?

**Comment by jcoupey** [comment]
> report issues in communicating with OSRM more clearly

Errors happening during exchanges with OSRM (initial table request or route queries after solving) should already have their own "routing error" [status code](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#code). There are basically two options:

- your error is related to OSRM and not catched appropriately. Then not filing the correct error code (and more explicit error message) is a bug
- the error is not OSRM related

The problem is in both cases I don't know how to do much more without being able to reproduce.

**Comment by unguul** [comment]
@jcoupey Since the issue went away as soon as I rebooted the OSRM instance I'd be inclined to say it was OSRM that was not replying appropriately, or at all. 

I'll close this issue since I can't reproduce the problem.

Thanks for the help! :+1:
