### ISSUE TITLE
Option to use all vehicles provided to the solver

### ISSUE THREAD

**Issue by ivosabev** [VROOM-Project/vroom#283]
It would be nice if we can set a flag that requires the solver to provide as many routes as vehicles available in the solution. Eg. we have 6 vehicles and we want 6 routes as a result.

This can be somewhat hacked with using capacity, but if we have 3 vehicles and 30 tasks, then we would get 3 routes with 10 tasks roughly: 10-10-10, but sometimes a more optimal solution would be 15-11-4.

**Comment by jcoupey** [comment]
Currently the reason for providing a solution with less routes than vehicles in input is that it's cheaper in term of overall travel time. Can you expand on the use-case you have in mind and the reasons why you'd rather have a longer solutions with all vehicles used?

**Comment by jcoupey** [comment]
For now you have a couple options on the hacky side:
- use capacities as suggested, but with more flexibility (something like 14-14-14 in your example)
- reduce vehicle time windows to make sure all vehicles are required, thus reducing solution makespan
- make sure one job has to be serviced by each vehicle using skills (not very practical because you then have to pick which job/vehicle)

**Comment by ivosabev** [comment]
Thanks for the suggestions. Maybe capacity is the best alternative, unless you plan to have a flag in the future that requires the algorithm to utilize all vehicles.
