### ISSUE TITLE
Delivery jobs based on inventory

### ISSUE THREAD

**Issue by metehan** [VROOM-Project/vroom#285]
I am wondering is it possible to solve routing problem vehicles according to inventory in the car.

Lets say one car has 5 bricks 3 sticks and the other car has 3 sticks 5 bricks. And there is a pickup location to take bricks and sticks. When customers orders sticks and bricks I need to plan the routing.

In the API documentation I saw "pick-up" and "delivery" sections but it's not very clear how to use them and I am not sure if it's related with my problem.

**Comment by jcoupey** [comment]
I think what you're looking for lies in a [comment on capacity restrictions](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#capacity-restrictions). This is neither very explicit nor illustrated with an example.

The API uses arrays to describe amounts in order to provide flexibility in modelling: each component of the array matches one metric you want to take into account and you can have as many as you want provided amount sizes are consistent. The downside is you have to figure things out yourself for your use-case.

In the above example, you could describe bricks as the first component of your amounts and sticks as the second. Your vehicles would have respective capacity `[5, 3]` and `[3, 5]`. A customer order of 2 bricks and 3 sticks would be described as a job with `delivery: [2, 3]`.

**Comment by metehan** [comment]
Thank you very much. It's clear now when I finish my code I would like to contribute to the documentation.
