### ISSUE TITLE
What's the recommended solution for updating routes that are already in progress?

### ISSUE THREAD

**Issue by jwld** [VROOM-Project/vroom#305]
I'll try and describe our use case as clearly as possible:
- We often want to add new jobs to existing routes - so for example we might want to add a new job in a route with 30 jobs, where 10 have already be completed - we essentially just need to re-route from step 11 onwards
- Our current plan is just to create a new route using the non-completed jobs only (so from step 11 onwards) and stitch that together with the original route (steps 1-10) in our database - the main downside to this being that things like distance, duration and geometry on the "new" route don't factor in the "old" route's values
- Is there a more elegant way to handle this with vroom's api? i.e. here are all the jobs, but keep jobs 1-10 in the supplied order

Also just to note we assign jobs to specific vehicles in advance ourselves, so when we're using vroom we only ever supply one vehicle for each list of jobs (basically that part isn't relevant to us).

**Comment by jcoupey** [comment]
> Our current plan is just to create a new route using the non-completed jobs only

This is what I would have advised. If the 10 first jobs are already completed, they're not really a part of the "new" optimization problem with added jobs. Hopefully our very fast computing times allow for such a dynamic use of the API.

Now on stitching the routes:

- If you're using `duration` and `distance` keys for steps, those are cumulated values so there would be no problem to stitch both solutions.

- In order to have consistent ETA between the two solutions, you'd have to set your vehicle time window start to account for the beginning of the new route. So when solving for the non-completed jobs only, vehicle new start availability should be set using `arrival + waiting_time + service` for step 10.

- The only problem I see would be with the `geometry` that comes as a whole. Possible solutions off the top of my head: 1. run a separate routing query for a new geometry with all jobs (not ideal) 2. use a post-treatment on the first decoded polyline to spot step 10, then use the first geometry only up to that point.

**Comment by jwld** [comment]
Ok great thanks, I think we'll have a go at that. If it's too problematic I think we might optimize the remaining jobs using vroom and then run the full route through osrm's `route` service to get the overall distance / duration / geometry.

**Comment by jcoupey** [comment]
Happy to have some feedback on how it turns out whenever you can!
