### ISSUE TITLE
Force all vehicles to be used

### ISSUE THREAD

**Issue by kubasienki** [VROOM-Project/vroom#329]
Hi, 
I've seen few issues about using only one vehicle when more than one is put.
I get it that it's expected behavior but I've seen it introduced briefly here: https://github.com/VROOM-Project/vroom/issues/97
and then removed soon later because of performance issues (and questionable validity). 
But it would be great it there was a flag to force this behavior.

**Comment by kubasienki** [comment]
I can't set rigid time windows and dividing jobs equally between vehicles (using capacity constants) discriminate cases where for ex. one driver would do some points much away while the others would do much more close to start.

**Comment by jcoupey** [comment]
I guess you've already read https://github.com/VROOM-Project/vroom/issues/328#issuecomment-615879739.  The ticket you mention (#97) is different as it's about a situation with a distributed fleet where adding a vehicle that is closest to the jobs actually reduces overall travel time.

The way you model your problem through constraints is really what will impact the kind of solution you get. If people agree to a more expensive route plan it's usually in order to comply with some other rule: share work among drivers, avoid too long working hours, serve all customers sooner etc. You need to figure out what those are in your use-case to translate them into relevant constraints.

You may argue that "force all vehicles to be used" is yet another constraint but I suspect that forcing this while searching won't necessarily provide the expected solutions. For example you might end up with most of the vehicles marginally used doing a single cheap job close by, while most of the work is still handled in a single route.

> Unfortunately and obviously it doesn't work for more than two

Why not? The demo server does [just this](https://github.com/VROOM-Project/vroom-frontend/blob/06d6f401aa30e17fc0fd65ed70cb7b44d38a744c/src/utils/solution_handler.js#L18-L26) prior to sending a request when several vehicles are defined with no capacity (or else only one route would be returned in most cases).

**Comment by kubasienki** [comment]
> Why not? The demo server does just this prior to sending a request when several vehicles are defined with no capacity (or else only one route would be returned in most cases).

I wasn't precise enough - What I meant that if not all vehicles are needed for the route, then probably some won't be used. So if two of the vehicles has enough capacity combined then the third won't do anything in most cases (or in all?).

Again I agree with your approach, just looking for some kind of _trick_ to make it working for me.

> The way you model your problem through constraints is really what will impact the kind of solution you get. If people agree to a more expensive route plan it's usually in order to comply with some other rule: share work among drivers, **avoid too long working hours**, serve all customers sooner etc. You need to figure out what those are in your use-case to translate them into relevant constraints.

Is there any way to divide the work equally in time units or just limit the amount of work done by one vehicle (not via amount)?

**Comment by kubasienki** [comment]
A great feature would be to select the cost function between the current cost impl and the time combined?

**Comment by jcoupey** [comment]
> So if two of the vehicles has enough capacity combined then the third won't do anything in most cases (or in all?)

Check the behaviour when adding vehicles on http://map.vroom-project.org/. Setting aside any other constraint, you always get as many routes as defined vehicles. The "fair share" is simply based on the number of stops (one per delivery) and vehicles. Setting a strict value is probably too restrictive, hence the `1.2` factor. You could also try applying this to any other "real" capacity value.

> Is there any way to divide the work equally in time units 

Set the same `time_window` for all vehicles.

> or just limit the amount of work done by one vehicle

Use a specific amount component that counts stops as suggested above. Or use any other meaningful value as amount.

> A great feature would be to select the cost function between the current cost impl and the time combined?

I don't get what you mean. Except for considerations related to priorities and number of unassigned jobs, our objective function is already the overall travel time.

**Comment by kubasienki** [comment]
Thank you for great responses - keep it up :)

> I don't get what you mean. Except for considerations related to priorities and number of unassigned jobs, our objective function is already the overall travel time.
I've deleted my comment :D because I've realized my mistake. 

Thanks again I'll tinker a bit

**Comment by jcoupey** [comment]
Hope this helps! Please report if you manage to setup something that works for your use-case, so others will find suggestions when browsing issues.

**Comment by jcoupey** [comment]
Closing as stale, feel free to reopen if required.

**Comment by Sandarr95** [comment]
Hi, I would like to ask some follow-up questions on this if that's okay.

Some context:
I am using this project because a small company has had an increase in demand that they can't solve with their previous solution. There are a multitude of vehicles available that have to deliver goods from 1 location to about 400 addresses.

For my solution, at first only 1 vehicle was used, so I stumbled upon this issue and found the solution of setting a `time_window` for each vehicle. In principle this works but setting the appropriate `time_window` is a bit arbitrary and doesn't always work with a factor of 1.2.
To find a better time I can calculate the route for 1 vehicle then, divide this by the number of vehicles I have, to get a better approximate time. This however doubles the work to get a route calculated.

Can you think of any better solution to approximate route times?
And/or are you open to introducing some new form of time constraints? I'm thinking either `time_window` as fractions of the total work time or a cost goal of the least concurrent work time if that makes sense.

Interested to hear what you think!

PS. Great project, I was amazed such a valuable and feature rich routing optimizer exists as FOSS.

**Comment by jcoupey** [comment]
The optimization process aims to find the "cheapest" possible solution. Now whatever "cheapest" means depends on the optimization objective. If we set aside stuff like priorities and number of assigned jobs, the main objective we currently have is the overall travelled time. As long as there is nothing in the optimization objective that tends to favour all-vehicles solutions (those are usually more expensive in term of total travel time), then you'll have to force that through constraints.

Now how to best model the constraints really depends on the specific use-case you're facing. Usually it takes time to analyse how people work and how that translates in term of constraints. The available levers are:

- capacities (real metrics and/or a number of jobs) ;
- time windows ;
- skills (you can use those to force a specific vehicle or set of vehicles to be used on a subset of the jobs).

> time_window as fractions of the total work time or a cost goal of the least concurrent work time if that makes sense

If working hours for vehicles were to be defined differently, I don't see how we could have them match to "real" time windows used for jobs.

Having other cost goals would indeed be a way to influence the solutions. For example switching to minimizing the overall end date (makespan) of the planning would definitely push solutions with all vehicles used. But there are several reasons why there is currently no plan to do so:

- it would introduce a bigger algorithmic complexity for several "hot" internal tasks (e.g. estimating gain for small solution changes), which would hugely impact the computing times ;
- it would provide much more expensive solutions in term of travel time and this is not desirable in many use-cases.

**Comment by Sandarr95** [comment]
Hi, thanks for the feedback, really explained a lot.

I'm currently trying to get a second capacity dimension involved that should describe the maximum amount of deliveries a vehicle can do. Then each delivery (x)or pickup should increase this by 1. Within shipments currently it's not possible to express this because the amount for pickup is equal and calculated to be the inverse of the delivery. From what I can understand from the code, being quite inexperienced with c++, is that all shipments are internally represented by Jobs. I was not able to figure out how these jobs are kept in proper order, other than preserving the order from the start. I was also not able to figure out if the symmetric amounts for shipments are a hard requirement. 
Would it in theory work if these amounts differ between a pickup and delivery?
If not, could you link to some code that depends on them being equal?

I'd love to tinker with it myself but as I said, my c++ is not that great, so without some pointers I feel a bit overwhelmed to start. Thanks again for the help.

**Comment by jcoupey** [comment]
> Within shipments currently it's not possible

That's correct.

> all shipments are internally represented by Jobs

Yes, all tasks have a `vroom::Job` type, and an `Input` object stores them in the `input.jobs` member vector. All internal references to jobs are usually their rank in this vector. Internally, `Job` objects have [a type](https://github.com/VROOM-Project/vroom/blob/638f6d11ac29d80189c70d5c797dd6549287caaa/src/structures/typedefs.h#L67): `JOB_TYPE::SINGLE` refers to the API notion of `job`, while `JOB_TYPE::PICKUP` and `JOB_TYPE::DELIVERY` describe the steps for a`shipment`.

Defining a `shipment` necessarily happens in `Input::add_shipment`, and the pickup and delivery steps are [added in a row](https://github.com/VROOM-Project/vroom/blob/638f6d11ac29d80189c70d5c797dd6549287caaa/src/structures/vroom/input/input.cpp#L124-L132). Internally we rely on matching pickup and deliveries having consecutive ranks in `input.jobs`.

>  figure out if the symmetric amounts for shipments are a hard requirement

Defining different amounts would [cause an error](https://github.com/VROOM-Project/vroom/blob/638f6d11ac29d80189c70d5c797dd6549287caaa/src/structures/vroom/input/input.cpp#L109-L111) but this check is mostly a way to make sure the notion of `shipment` from the API is consistently translated.

I think what you have in mind would work (setting 1 on the extra component for both pickup and delivery so they don't cancel each other). To achieve this, you'd have to adjust how amounts are defined for pickups and deliveries from [their `Job` constructor](https://github.com/VROOM-Project/vroom/blob/638f6d11ac29d80189c70d5c797dd6549287caaa/src/structures/vroom/job.cpp#L57-L58) and possibly toy around with the way the amounts are defined [when parsing the json input](https://github.com/VROOM-Project/vroom/blob/638f6d11ac29d80189c70d5c797dd6549287caaa/src/utils/input_parser.cpp#L476-L516).

Now that you mentioned the `shipment` drawback, the extra-component hack sounds overly complicated. On the other hand, the number of tasks in a route is just the plain size of [some vector](https://github.com/VROOM-Project/vroom/blob/638f6d11ac29d80189c70d5c797dd6549287caaa/src/structures/vroom/raw_route.h#L55). So maybe at some point we should provide a more straightforward way to define this kind of restriction as a top-level constraint.

**Comment by Sandarr95** [comment]
Hi, I started to work on getting the amounts separated for the shipment pickup and delivery. I removed the check and edited the parser so it expects amounts to be in the pickup and delivery objects. I also removed some assertions that were causing the program to exit, just to see if I could get a somewhat okay result without diving to deep into the inner-workings.
This is not meant to be code that adheres to any quality standards, just to provide a PoC.

So about the results, obviously they are not quite what they should be, probably because those assertions I removed are there for a reason. It seems like some part of the optimizer does assume the load can decrease back to zero or something like that. It counts the load correctly, meaning when we set an amount of 1 on every pickup and an amount of 0 on every delivery the total load of a vehicle only ever increases. When turned around, the load goes negative. However, the capacity constraint is not enforced anymore on amounts that are not equal.
This clearly has something to do with the assertions I removed. Could you take a look and give some context on what they are asserting and why?
https://github.com/Sandarr95/vroom/pull/1

**Comment by jcoupey** [comment]
@Sandarr95 from what I can tell, your PR is getting there, except you should not have need to comment that many asserts. I'll drop comments directly there.

**Comment by Sandarr95** [comment]
Hi, thanks for the feedback. I checked out the Job constructor but couldn't figure out exactly what I needed to change about it.

If I understand correctly it will take the amount it has been given and assign it based on what `JOB_TYPE` (pickup or delivery) matches, then assign the other `Amount` attribute a 0 initialized amount of equal size. Because the parser now provides separate amount objects for each ([pickup](https://github.com/Sandarr95/vroom/blob/5d90087f06472eaf980d34de953fe51442d549f2/src/utils/input_parser.cpp#L625) & [delivery](https://github.com/Sandarr95/vroom/blob/5d90087f06472eaf980d34de953fe51442d549f2/src/utils/input_parser.cpp#L649)) type when the constructor is called the resulting two Jobs should be in the correct states.

I'm probably missing something, can you understand/tell where my description is not accurate?

**Comment by jcoupey** [comment]
@Sandarr95 for the sake of a simple example, let's consider that the only capacity component you have is the one you use to limit the number of visited locations. If a vehicle has `capacity: [15]`, this translates to "the vehicle starts with room for 15 visits". If each regular job has `pickup: [1]`, each job step will "consume" one of the visit spots, so the route won't include more than 15 jobs.

Now in order to avoid pickup and delivery steps cancelling each other, you'd have to define a `pickup: [1]` upon pickup (with a 0 initialized amount for delivery). Then if you want to count the whole shipment as a single visit, the matching delivery should have 0 initialized amounts for both pickup and delivery (in that case you could handle e.g. 9 jobs and 6 shipments in a route). If you want to consider that pickup and delivery are two different locations and should count as two visits, then you want to also have a `pickup: [1]` upon delivery (in that case you could handle e.g. 9 jobs and 3 shipments in a route).

**Comment by DejavuDaniel** [comment]
hey @kubasienki  @Sandarr95 did you find a optimal way to divide the jobs to drivers with around the same time ?

**Comment by Sandarr95** [comment]
Unfortunately not. I haven't looked into it anymore. If I ever do again, for my use case I'll use the new feature of `max_tasks`.

**Comment by DejavuDaniel** [comment]
With max_tasks does it divide by time ?

**Comment by kubasienki** [comment]
@DejavuDaniel I've looked into my old code and I solved my case this way:
`
driverCapacity = totalPackages / drivers;
driverCapacityRemainder = totalPackages % driverCapacity;
for (int i = 0; i < drivers; i++) {
     addVehicles(vehiclesdriverCapacity + (driverCapacityRemainder > i ? 1 : 0))
}
`
This rather was to ensure that all drivers would get a similar number of packages and would get some work. I have treated multiple deliveries for the same address as different packages, so in the end, for my use case, it kinda balances time too :)
