### ISSUE TITLE
support dates in time_windows params?

### ISSUE THREAD

**Issue by stefanocudini** [VROOM-Project/vroom#340]
I was wondering if the time windows management parameter could (and if so in what way) support time intervals of days(or day of week)

from the examples of jobs that I have seen so far, each time parameter is expressed in seconds.

but if I wanted to specify a range of a few days for deliveries how should I convert the value of the parameters? simply from seconds to days?

there is any use case of this?

**Comment by jcoupey** [comment]
How you define your planning horizon is up to you, see [the docs](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#time-windows). You can either use `0` as start of the planning horizon, or use [timestamps](https://en.wikipedia.org/wiki/Unix_time) (which actually simply means setting the 0 value back in 1970).

In any case, there is no problem to model time windows across several days, you just have to express them as seconds since whatever reference you picked.

Using timestamps is probably a convenient way because many programming contexts offer ways to convert back and forth to usual "dates". Internally, durations are stored as `uint32_t` so if using unix timestamps, you should be fine planning stuff up to around year 2106. ;-)
