### ISSUE TITLE
volunteer food deliveries in Brooklyn?

### ISSUE THREAD

**Issue by healeyjoseph** [VROOM-Project/vroom#342]
hello,

would you recommend VROOM for routing deliveries to food insecure households in Brooklyn? in light of the pandemic we are serving 200+ households daily with a varying number of volunteer delivery people.

we're focused on optimizing the logistics of this volunteer operation rather than routing, since our volunteers generally know their way around the neighborhood.

for example, could VROOM generate a data visualization similar to this one (grouping nearby addresses into clusters to aid delivery dispatching): 

https://outagemap.duke-energy.com/#/current-outages/ncsc

except of course on the smaller scale of an NYC neighborhood.

love this project, thank you for your hard work.

let us know if you think VROOM could help or if we might look elsewhere?

**Comment by jcoupey** [comment]
VROOM could definitely handle the logistics optimization part. It would typically ingest the list of households to visit on a given day, the set of available volunteers and (if required) some additional constraints such as working hours, capacity etc. Then what you can easily get from VROOM is:

- how to split the work across several (efficient) routes
- how to order visits within each route to reduce overall travel time

This repo is the core solver so there is no visualization involved, and depending on what you want to achieve, you may have some dev to format optimization requests and integrate VROOM results.

On the other hand, we provide a [demo server](https://github.com/VROOM-Project/vroom/wiki/Demo-server) and a simple [demo UI](http://map.vroom-project.org/) for testing purposes. Let me know if this is enough for you to get started. You're very welcome to use the demo, especially for volunteer work like this! The max number of locations that can be optimized over there has been recently raised from 100 to 200 due to this kind of demand in the light of the covid context.

**Comment by healeyjoseph** [comment]
thank you! we will try out the demo and get back to you if necessary
