### ISSUE TITLE
Loops in the route

### ISSUE THREAD

**Issue by valerivp** [VROOM-Project/vroom#352]
I get two visits to the same point in my route. What am I doing wrong?

![2020-06-12_1811](https://user-images.githubusercontent.com/28062383/84519195-65439f80-acda-11ea-9c12-814f7cff615b.png)

[src.json.txt](https://github.com/VROOM-Project/vroom/files/4771695/src.json.txt)
[res.json.txt](https://github.com/VROOM-Project/vroom/files/4771694/res.json.txt)

**Comment by jcoupey** [comment]
Hard to tell much without being able to reproduce, especially as the underlying travel time costs and output geometry are unknown, and may vary depending on your routing setup. You could always [share a standalone instance](https://github.com/VROOM-Project/vroom/wiki/Standalone-problem-instance) to allow reproducing.

A wild guess: maybe going from 15 to 14 passes in front of 13 anyway, so that `8 -> 13 ->15 -> 14` would actually not be cheaper than the `8 -> 15 -> 13 -> 14` you're getting.

**Comment by valerivp** [comment]
Why can't you play it back? I also attached a file for example (src.json.txt)

**Comment by valerivp** [comment]
Sample with matrix
[res-m.json.txt](https://github.com/VROOM-Project/vroom/files/4772969/res-m.json.txt)
[src-m.json.txt](https://github.com/VROOM-Project/vroom/files/4772970/src-m.json.txt)

[res-m.json.txt](https://github.com/VROOM-Project/vroom/files/4772966/res-m.json.txt)
[src-m.json.txt](https://github.com/VROOM-Project/vroom/files/4772967/src-m.json.txt)

**Comment by jcoupey** [comment]
> Why can't you play it back?

There are many reasons why the behaviour may differ:

- what routing engine you use
- what profile you're using
- what adjustments you've made to the profile
- the version of OSM data you picked

Also it's usually simpler to just have a standalone instance rather than having to setup a whole routing stack that covers your area, just for debugging.

**Comment by valerivp** [comment]
Is the matrix example suitable for playback?
I tried on self hosted 1.6 and on http://solver.vroom-project.org

[src.json.txt](https://github.com/VROOM-Project/vroom/files/4772967/src-m.json.txt)

**Comment by jcoupey** [comment]
Yes, the file with embedded matrix makes it possible to reproduce and debug. It looks like my first guess was right here. 

1. The list of steps `13 -> 15 -> 8 -> 14` (ids) means matrix values at `1 -> 7 -> 1 -> 6` (`location_index`), which makes up for a travel time of `189 + 189 + 3647 = 4025`.
2. Now `8` and `13` have same location, so you'd expect to get steps `13 -> 8 -> 15 -> 14` (ids). But this translates to `1 -> 1 -> 7 -> 6` (`location_index`), which makes up for a travel time of `0 + 189 + 10637 = 10826`.

So the reported solution is actually better in term of overall travel time. Now the bottom line here is not related to optimization, but to the routing layer providing travel times with a huge violation of the triangle inequality: `7 -> 1 -> 6` is nearly 3 times cheaper than `7 -> 6`. You may want to investigate this with direct route requests to OSRM.

**Comment by jcoupey** [comment]
On a side note, it looks like most of your `shipment` objects have a delivery `location_index` that is the same as the vehicle `end_index`. In order to model picking stuff that has to be brought back to the end of the route, you should really use `job` objects with a `pickup` key over shipments. This will reduce the size of your input problem and make it easier for the optimization phase to reach better solutions.

**Comment by valerivp** [comment]
Is it possible (how?) to add a condition, not to visit one point two or more times?

Different types of delivery can be mixed with me, and the shipment option is most clear to me.

**Comment by valerivp** [comment]
Another algorithm produces a very similar solution, slightly longer, but without a loop. But it doesn't know how to work with time constraints. So I want to use vroom. But I can't visit the point again.
[route.xlsx](https://github.com/VROOM-Project/vroom/files/4779801/route.xlsx)

**Comment by jcoupey** [comment]
> Is it possible (how?) to add a condition, not to visit one point two or more times?

No, the steps ordering (thus number of time of visit) is a result of the constraints and the underlying travel costs. Again in the example you submitted, this is not an optimization problem, but related to the fact that the "obvious" route you'd expect is actually much more expensive according to your routing engine. If you fix this, VROOM will provide a solution without a loop.

The other solution does not change the analysis. The only difference lies in `9 -> 15 -> 8 -> 13 -> 14` that costs `7907`, whereas VROOM provides `9 -> 13 -> 15 -> 8 -> 14` which costs `7850`. So again the reason why VROOM splits the same locations point is that because it's cheaper that way.

> Different types of delivery can be mixed with me, and the shipment option is most clear to me.

No problem, as long as you're aware that the way you model the problem can result in both longer computing times and lower quality solutions.

**Comment by valerivp** [comment]
You are certainly right, from the point of view of mathematics, vroom is building the shortest route. But from a practical point of view, this route is bad.

Wish - add the ability to ban visits to one point several times. Even to the detriment of the cost of the route.

Wish - if at one point loading and unloading - first plan to unload. But this is not important - it is much easier to process than to build a route.

**Comment by jcoupey** [comment]
> But from a practical point of view, this route is bad.

Agreed, my point is that if the optimization does it's best to provide a good route on top of poor travel times evaluations, you can't blame the optimization.

You should investigate the problem I pointed [above](https://github.com/VROOM-Project/vroom/issues/352#issuecomment-643987017) and fix it **from a routing point of view**.

**Comment by valerivp** [comment]
vroom is a very good product! I do not think that he plans the route poorly.
But I get the matrix data from https://openrouteservice.org/ (or from other geoservices) and I can not check their correctness. I can’t check all the possible ways ...

Out of 107 test routes, I don't like just one. But having such a problem prevents me from using vroom.

I would really like to use vroom, so I ask for a patch that will not allow you to build an invalid route (two visits to the point), even if such a route is not the shortest.

**Comment by jcoupey** [comment]
Then maybe the routing curiosity you've uncovered should be reported to the Openrouteservice team.

> I ask for a patch that will not allow to build an invalid route (two visits to the point)

I won't implement this kind of restriction myself because for some use-cases (think disjoints time windows, different skills etc.) having several visits to the same location is not a problem, and even required.

**Comment by valerivp** [comment]
I understood you.
But maybe you will make this condition optional or tell me where and how to change the code to get this restriction?

**Comment by jcoupey** [comment]
Unfortunately there is no easy way to add this. You'd need to decide that a given route is invalid as soon as it visits the same location twice but *not in a row*. This would require an extra data structure for each route storing the set of ranks bounds at which a given `location_index` is visited. Then check that any new move does not break the proximity rule. Also update the data structure for each route change.

This means digging deep into the code. Frankly, no worth the trouble IMHO if you're only unhappy with 1 route out of 107.

Trying an optimization fix for a routing problem just does not sound right. I'd strongly suggest again to investigate the routing problem: run route queries to ORS with the relevant locations to understand where the huge triangle inequality violation comes from. The fix might be just a couple OSM tags away...

**Comment by valerivp** [comment]
Many thanks. I don’t like this route, but really, when I add time limits, such a route may be valid.
