### ISSUE TITLE
Vehicles priority

### ISSUE THREAD

**Issue by boooch** [VROOM-Project/vroom#359]
Do you have vehicle priority by any rule? For example I have 2 trucks, one 50 tonn and other 100 tonn capacity. And all shipments can be sipped by one of them. Which of them will be selected?

**Comment by jcoupey** [comment]
No, there is currently no such notion of priority. What vehicle(s) are picked up in the solution is a consequence of the optimization choice, basically it comes down to whatever combination of routes we found that is the cheapest **and** is valid with regard to all constraints.

On the other hand, if you have an heterogeneous fleet, the choice usually makes sense because it's a direct consequence of the way the constraints apply. Items that can impact which vehicles are used are:

- capacity (more fits into a given vehicle)
- time windows (more jobs available during working hours)
- skills  (more matching jobs available)
- start/end location (changes cost of reaching to the jobs)

In the case you mention of routes that are interchangeable between vehicles with not all vehicles used, the result will be an arbitrary consequence of how vehicles are handled internally during the search phase.

**Comment by braktar** [comment]
@jcoupey Any plan to implement a notion of fixed cost for vehicles in order to discriminate equivalent vehicles in term of constraints ?
In real cases, it is often the case when you have a limited fleet but you can eventually add extra vehicles from sub-contractors with a higher initial cost to hire this asset.

**Comment by jcoupey** [comment]
@braktar would a "simple" notion of priority be enough for the use-case you have in mind? Vehicles from the initial limited fleet would get a higher priority, while sub-contractors vehicles would have lower priorities depending on initial cost.

I get it this would not allow to discriminate between adding a vehicle to handle more jobs versus doing less to mitigate costs. But usually everything need to get done.

**Comment by braktar** [comment]
It could do the trick as long as there is no other cost defined at the vehicle level (distance or time cost).
But it won't allow to handle properly cases with large waiting time in the middle of a route.

**Comment by boooch** [comment]
Usually in real cases we have several types of vehicle cost counting:
1. Cost per km (including fuel cost and  vehicle amortization)
2. Cost per hour (including driver salary and for example for rented cars)
3. Cost per usage - additional payment for the fact of usage. Allow you to prefer to do all tasks by one vehicle instead of two if it possible.

**Comment by jcoupey** [comment]
This would indeed be a great addition to be able to set the costs on a vehicle basis just as you described. Point 3 would actually solve the initial problem reported in this issue. The rest has a much broader scope so I think we should open a dedicated ticket for the cost rework thing.

The good news here is that it should be easier now thanks to previous work in #450 that introduced a clear separation internally between the notions of travel duration and cost.

**Comment by jcoupey** [comment]
Closing as a feature that would solve the initial scope is now ticketed in #528.
