### ISSUE TITLE
Dispatch capacity constraints

### ISSUE THREAD

**Issue by Trollgeir** [VROOM-Project/vroom#375]
Imagine you have a depot which can only load 1 vehicle at the time for a fixed service time. How could I make constrains to generate an optimal 'queue' (technically optimize the startup-time per vehicle) based on the available slot in the depot?

I could preprocess a queue and mutate the starting-time of each vehicle myself before solving with vroom, but this could easily be a sub-optimal solution when the jobs have time windows.

**Comment by Trollgeir** [comment]
Deciding the loading order beforehand sounds a bit stochastic. I could imaging mutating the vehicle start-times into a set of problem instances do multiple `vroom`-runs, only to select the best solution.

We currently use OR Tools as a post-optimizer for shuffling about the start-time of the vehicles once they've been assigned to routes. It works, although sub-optimal :)

**Comment by jcoupey** [comment]
Again this is totally problem-dependent. If you have a somewhat homogeneous fleet, then going for a fixed schedule would totally make sense. If not, I suspect you're better off running the whole VRP stuff and then adjusting the loading phase.

> It works, although sub-optimal

Well, we live in a sub-optimal world anyway. ;-)

Feel free to close if the post-processing trick does the job for your use-case, I frankly don't see any step toward handling this kind of constraint any time soon.

**Comment by Trollgeir** [comment]
Am I able to _force_ the start time of a vehicle at a specific time?

**Comment by jcoupey** [comment]
> Am I able to force the start time of a vehicle at a specific time?

Not really. Vehicles start times are of course always included in the vehicle `time_window` but except for this, the start time is decided during the optimization phase and is the result of route load and other constraints, especially job time windows.

During the whole optimization phase, we work with time margins for all steps (earliest and latest dates) and setting arrival times in ouptut only happens after that in [`format_route`](https://github.com/VROOM-Project/vroom/blob/efc5a9d1f8a26a00a4cad7af5f4b94c4eded4313/src/utils/helpers.h#L392). The logic is:

1. Pick earliest possible arrival at the end of the route (minimize completion time)
2. Browse the route backward to determine latest possible start time matching this value (in order to minimize waiting times along the route)
3. Decide `arrival` values based on this start time, pushing every step asap in its feasibility window.

**Comment by jcoupey** [comment]
Looks like this can be handled outside `vroom`.
