### ISSUE TITLE
Fixed start time

### ISSUE THREAD

**Issue by hyzajabada** [VROOM-Project/vroom#379]
Hi, is there any built-in way to force the start time set for vehicle? I've had examples when the start time in the optimized route was later than specified in input because the first job had time window set 2 hours later. It makes sense considering that the optimization aims for the shortest travel time, so if the constraints allow it moving the start time to a later hour might result in shorter route. 

I thought about creating a job with time window and location exactly the same as the starting point, but I think that the first job is still going to be the same, the only difference would be the vehicle's arrival time resulting in a break. 

Ideally I'd like the start time to be fixed and breaks disabled so that the vehicle would start at the specified time and arrive at all jobs within their time windows, not before, even if it would result in a longer time travel. Any way to achieve this?

**Comment by jcoupey** [comment]
This is somehow similar to the question raised at https://github.com/VROOM-Project/vroom/issues/375#issuecomment-670861266, see answer there for a bit of context.

There is no way to do this currently but I'm flagging this ticket as a feature request because that could indeed be a totally valid requirement: think a situation where drivers are available early and it does not make sense to push the start time too much even if achieving a shorter route.

In term of implementation/API, it would come down to introducing a new parameter (something along the line of `start_before`, and maybe also `end_after`). Then whenever we use time bounds to compute earliest/latest dates for start/end, we should use those values instead of the `time_window` bounds.

It would allow to reach a solution that is more relevant (and with a smaller completion time) in some situations, at the cost of a potentially longer route.

**Comment by jcoupey** [comment]
On second though, this would not be straightforward at all. With the current optimization objective of minimizing overall travel time, forcing the vehicles to start earlier would not guide the search process toward *worst* solutions only for the sake of filling routes. Filling the routes from the start only happens insofar as the time constraints allows it.

In fact, we already provide solutions where arrival at the last step happens ASAP, and first step is pushed at the latest possible time to meet this arrival. Thus artificially formatting routes with earlier start times would only add unnecessary waiting time along the route.

The real way to reach solutions that are *worse* in term of overall travel time but fill route starts would be to have the completion time come into play. But then mixing yet another optimization objective is a different kettle of fish.

**Comment by andreykochev** [comment]
Hi jcoupey, 
Can you please tell me where I can find the solution of "arrival at the last step happens ASAP"?
I`ll be very thnakful!
Thanks in advance

**Comment by jcoupey** [comment]
> "arrival at the last step happens ASAP"

This particular snippet of the above comment is describing what is already happening internally. For any generated route, the last step is scheduled ASAP based on vehicle/tasks timing constraints. That's a fact so I'm not sure I get what you're asking about?

**Comment by windrexcz** [comment]
Little late to party, but for those reading this... 

I found a workaround where you can create a 'pseudo job' for the vehicle start with 0 service and timewindows being [vehicleStart, vehicleStart], in my case this creates a concrete start time for the route (unless you have other stops that have time window before the vehicle start)
