### ISSUE TITLE
Vehicle-dependent travel times

### ISSUE THREAD

**Issue by K-Leon** [VROOM-Project/vroom#394]
First of thanks for this great project 👍 

One point I was thinking about is how to handle optimization of vehicles with different speed profiles. (Truck and Car and so on)

Is there already a possibility?

Thanks already!!

**Comment by jcoupey** [comment]
This is not possible currently because we only store a single matrix for travel time costs so those need to be constant across vehicles. I agree this would be a great new feature for the project. The high-level tasks would be:

1. Fire several concurrent matrix requests to different routing instances based on `vehicle` profiles and store access to the relevant matrix from a vehicle perspective.
2. Replace all travel time lookups with their vehicle-dependant counterpart. This means *many* changes scattered all over the codebase, touching all critical components: heuristics, local search moves etc.
3. Adjust the solving approach to account for the fact that vehicles will have different reach (think foot vs bike or car) and are then "expected" to serve different subsets of the tasks.

1 and 2 are pure technical tasks, 2 being more tricky because of the intricate use of travel times throughout solving. I expect 3 would require changes and tuning on the heuristic approaches because some of the current features (e.g. specific route seeding or using regret costs) could lead to poor choices with heterogeneous travel times.

**Comment by K-Leon** [comment]
Thanks for considering this as a feature! I‘m not that fluent with C++, but I can offer you any help with testing at a larger scale!

**Comment by jcoupey** [comment]
Also some of the local search operators currently implicitly rely on travel times being equal across vehicles, so:

4. Adjust local search operators to account for different travel times between pairs of vehicles.
