### ISSUE TITLE
VRP wishlist

### ISSUE THREAD

**Issue by systemed** [VROOM-Project/vroom#4]
Really pleased to see this - it looks like a great fit with OSRM. Though I'm happy with jsprit (which I use at the moment) I'd love to have something that doesn't require Java.

For my VRP project the following would be good:
- [ ] Multiple vehicles
  - ideally with clustering support or similar
  - prefer small number of vehicles with full days (jsprit sometimes issues many vehicles with half-days)
  - start from/return to depot
- [ ] Delivery windows (start/end times for each destination)
- [ ] Service times (delay at each destination)

**Comment by jcoupey** [comment]
Thanks for the input.

Handling multiple vehicles starting and returning to a given point would definitely be the next step in functionality. 
Delivery windows is yet another step as it might be wise to use a different approach when those constraints arise.

The project might benefit from other non-functional things such as benchmarking the existing code and promoting through a demo server. 

Not sure yet how all of this is to be ordered, so the roadmap remains quite informal...

**Comment by thrownblown** [comment]
A simple server example?

I'm setting up Vroom for the first time now to test it and I'm going to build a little node-express server to handle the requests and pass them to Vroom's CLI. It would be a nice to be able to have an example setup out the box. I'd be happy to issue a pull request when I'm done.

**Comment by jcoupey** [comment]
@thrownblown This is a very interesting prospect! Worth opening a dedicated ticket IMO if you feel like it! ;-) Looking forward to discuss this.

For your tests, make sure to build from the develop branch as it is currently quite ahead from master in term of functionality and performance (a merge is to be expected some time soon).

**Comment by jcoupey** [comment]
@thrownblown Don't know if you had a chance to experiment on your suggestion, but I just gave it a try. I am certainly no javascript/Node expert, so feel free to jump in at https://github.com/VROOM-Project/vroom-express.

**Comment by Drag0s** [comment]
@jcoupey How's it going with the VRP supporting multiple vehicles and the globally VROOM's roadmap nowadays?

**Comment by jcoupey** [comment]
@Drag0s  good question, and a nice opportunity to write things down.

Implementation ideas for new features have been on my mind for a long time (see first comments on this issue nearly one year ago). There has been some delay due to the fact that I'm only working on this as a side project so far. Also there has been some OSRM integration work, the existing TSP approach has been enhanced, made faster, and benchmarked. And setting up a demo server took quite some time too (no functionality added to the core code but important in my view to promote the project).

Before adding features, we also need to rely on a real API designed for further additions. Most of the work has already been conducted in #30. So what I have in mind in term of roadmap as of today is:

- finish the work on #30
- THEN issue a 1.0.0 release using the new API and recent additions (hopefully in September)
- start working on CVRP (i.e. handle multiple vehicles using capacity constraints)

I also plan to push a separate repo with the demo frontend code, but it requires a bit of cleanup and refactoring beforehand.

**Comment by jcoupey** [comment]
Closing as there is not much discussion here anymore and we should probably ticket features separately now.

As a start, any input on multiple vehicles support based on capacity limitations is welcome in #74.
