### ISSUE TITLE
Using VROOM for Airport Ground Vehicle VRP | Snapping to Taxiways/Jetways (as opposed to Roads)

### ISSUE THREAD

**Issue by kurdmalek** [VROOM-Project/vroom#406]
Hello,

I am working on an airport ground handling VRP project and would like to take advantage of the database of mapped taxiways and laneways that OSM has compiled for certain airports. The current frontend demo, however, will route a vehicle that I place in an airfield by snapping it to the nearest public road (a vehicle highway).

Is there a way to disable road snapping, or better yet, snap vehicle routes to the mapped airways or taxiways? Say by installing a VROOM stack locally on my machine, and changing this directly in the source code. I am attaching a screenshot for reference.

![DFW_VROOM](https://user-images.githubusercontent.com/22626737/99523327-c63b6780-294b-11eb-8a70-9794693a2cae.png)
 
Appreciate your help.

**Comment by jcoupey** [comment]
The demo server uses OSRM (with a default car profile) for routing. You can't really disable snapping as it's required to find the "nearest" OSM edge to start a route from. If snapping does not happens on the ways you expect, it's because they have been  ruled out by OSRM from the road network during the extraction phase because they are tagged in a way that make them look as non-publicly accessible. See for example tags on https://www.openstreetmap.org/way/332679855 and a view of the graph [as seen from the OSRM demo instance](http://map.project-osrm.org/debug/car.html#17/32.89456/-97.03917).

Running your own stack would be the good way to go, because it would allow you to tune the routing profile and decide for yourself which ways you want to route on or exclude for your particular use-case. Not sure any of the existing routing engine has an "airport ground vehicle" profile working out of the box. ;-)

If you want to go with OSRM, then you'd have to setup your own server and tweek [the routing profile](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/profiles.md). A neat tool for this is the debug view linked above which you can point to your own server.

**Comment by jcoupey** [comment]
Closing as the required work/changes are on the routing side.
