### ISSUE TITLE
Enforce single pickup location for shipments

### ISSUE THREAD

**Issue by stewartmcgown** [VROOM-Project/vroom#411]
Is there a way to enforce that a vehicle can only pick up from one combined location (up to its capacity limit)?

Use case is food delivery. Orders = shipments, but it never makes sense to assign a delivery driver to multiple pickups at multiple locations, rather we want to assign at most one pickup location + up to N delivery locations.

One thing I've looked at is some pre-optimisation like combining multiple pickups into a single job, but then there seems to be no connection from that job -> the necessary delivery locations, which is of course where shipments come into play.

With this input JSON:
[Gist showing an example input](https://gist.github.com/stewartmcgown/e712374e3f00437990606e00bdc8438f#file-vroom_single_pickup_init-json)

Most of the time I'll get routes that originate from the same pickup location, but occasionally due to other constraints i'll get routes that suggest multiple pickup locations.

[Gist showing example output with multiple pickups](https://gist.github.com/stewartmcgown/e712374e3f00437990606e00bdc8438f#file-result-json)

I've been running some looping, simulated tests of assignments and found that around `1/50` assignments fallback to multiple pickup locations in optimal conditions (multiple shipments waiting and multiple riders available), with a much higher rate as the ratio of shipments:vehicles increases. My current workaround is to filter out the assignments that collide pickup locations after the fact, but this is not optimal for obvious reasons.

As a sidenote, I'm running VROOM this algorithm essentially as a replacement for my exisiting handmade despatch algorithm. It's a much better fit and I'm blown away by how quick it is even for real-time routing optimisation.

**Comment by jcoupey** [comment]
No, currently we don't have a way to enforce that drivers won't perform pickups at multiple locations.

Technically speaking, I think that could be added to the current solving approach without performance loss by maintaining a set of unique pickup locations for all routes. Then if we have a max of `N` pickup locations allowed for a given route, we could add a check for all route moves. If the move adds a `N+1`th pickup location that is either different or not alongside a similar location, then the move is discarded.

Still, this is not a trivial change and would require to apply this logic to the heuristics and all local search moves involving shipments...

On the other hand, if multiple pickups locations appear in a single route, it's probably because it's cheaper to re-use the same vehicle. How often this happens is constraint-dependant (you probably have tight timing constraints to deliver food). In that case, you're looking for a worse solution in term of overall travel time, but using another available vehicle. So you could probably achieve what you want by solving variants of the same problem iteratively and adding skills to fine-tune vehicles-jobs assignement.

**Comment by stewartmcgown** [comment]
Wow, thanks for the quick and detailed response!

Could you explain further what you mean by solving the same problem iteratively?

My only possible solution seemed to be appending all the unique pickup locations to the capacity array, so I'd maybe have:

[MAX_ORDERS, TOTAL_WEIGHT, P1, P2, P3...]
[2, 4000, 1, 1, 1, ...]

But I also realise that a shipment with a weight would then only allow a single pickup for one location.

**Comment by jcoupey** [comment]
I mean that you can keep part of the solution (routes with a single pickup location are fine) and add constraints for the rest in a new solving round. For all routes with multiple pickup locations, you can e.g. choose one pickup location and force assigning associated shipments to the same vehicle in the next run. Then you'd need to make sure shipments associated with extra pickup locations can only be handled by the remaining idle vehicles.

Forcing assigning orders to (a set of) vehicles happens using skills.

**Comment by stewartmcgown** [comment]
Awesome, I've done exactly that with the skills constraints to do an approximation of what I want. Thanks very much for you insight!
