### ISSUE TITLE
How use timewindows with custom matrix?

### ISSUE THREAD

**Issue by valerivp** [VROOM-Project/vroom#413]
Where does vroom take the travel time between points, if I pass distances in the matrix?

**Comment by jcoupey** [comment]
>if I pass distances in the matrix?

You can't input distances, as per [the docs](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#matrix): "A matrix object is an array of arrays of unsigned integers describing the rows of a custom **travel-time** matrix".

If you feed distances in custom matrices instead of travel times, they'll be used for checks against time window constraints, which is probably something you want to avoid.

**Comment by valerivp** [comment]
From docs:

> The summary object has the following properties:
> **Key | Description**
> cost | total cost for all routes
> duration | total travel time for all routes

what's the difference then?

**Comment by jcoupey** [comment]
For the time being, no difference at all. We currently optimize on overall travel time so `cost` and `duration` are equal.
