### ISSUE TITLE
Supply cost matrix and duration matrix separately

### ISSUE THREAD

**Issue by iedmrc** [VROOM-Project/vroom#415]
Hi,

We provide VROOM a customized cost matrix rather than letting VROOM fetch from OSRM (As it is already supported by VROOM). But manipulating the cost matrix deforms time windows due to durations are the same as the cost matrix. It'd be nice if we could pass a duration matrix along with a cost matrix. Then VROOM could optimize the cost matrix but check time windows by looking up to the duration matrix.

Thanks!

**Comment by valerivp** [comment]
That would be fantastic!

**Comment by jcoupey** [comment]
Currently we optimize on overall travel time so we're using travel times as sole cost option. Regardless of how costs are computed (custom matrix or based on other metrics), the real change here would be to switch to a generic notion of `cost`, whatever that means. This would require to adjust all places where costs/gains are used throughout the solving phase, which is a deep dive in the codebase.

Benefits of this work would include:

- support for user-provided cost matrix
- support for user-provided cost functions (fixed cost for vehicle usage and additional cost proportional to travel time and/or distance)

This is also somehow related to #394 if you think cost functions/matrices should be vehicle-dependant. In that prospect, this would require the same kind of deep technical changes to the codebase, but also solving adjustments to account for heterogeneous costs across vehicles. Adding the notion of a fixed cost for a vehicle also requires touching existing local search operators.

**Comment by graham8** [comment]
It would be good if a simple option to equate cost with distance travelled could be introduced.  This is because providers such as openrouteservice can be wrong about how fast some roads can be travelled.  Current proposed workaround is

- run optimisation based on fastest route
- calculate average speed from travel time and distance travelled
- obtain distance matrix and scale by average speed to obtain normalised travel-time matrix
- run optimisation again using travel-time matrix
