### ISSUE TITLE
How can you prohibit a trip to the same point twice?

### ISSUE THREAD

**Issue by valerivp** [VROOM-Project/vroom#419]
I have already asked this question, but I would like to return to it. 
How can you prohibit a trip to the same point twice?
I need this to solve the vrptw problem, in the absence of a tw restriction for the vehicle and with tw for tasks with a wide range. In the physical world, this means that you need to take as many orders as possible, but you can only go to the warehouse once.

**Comment by jcoupey** [comment]
We don't have a way to enforce a max number of visits to a given place. Because we try to include as many tasks as possible, we'll visit a pickup place several times (if possible) if it increases the number of tasks included in the solution.

My understanding is that you're using `shipment` objects with the warehouse as the sole pickup location. But if you want a single visit to a warehouse, this sounds rather like a simple single-depot VRPTW which can be more easily described using `job` objects.

**Comment by valerivp** [comment]
I have the main thing-shipments from the warehouse, to the warehouse may not be the zero point for the vehicle (zz - >wh - >xx). However, there are tasks for delivery to the warehouse (XX - >WH). and there are tasks xx - >xx when both sender and receiver are on the route. 
And yes, there can be several warehouses.

**Comment by jcoupey** [comment]
We don't have a way to make sure going several times to the warehouse for deliveries/pickups won't happen.

But if it does, it's probably a result of the constraints you imposed (e.g. capacity limit that requires going back for a "refill", or disjoints time window that forces several "shifts"). In that case, forcing only one passage to the warehouse would mean some tasks would end up unassigned.

**Comment by jcoupey** [comment]
Closing as stale, feel free to re-open with new input if required.
