### ISSUE TITLE
Capacitated Multi-Depot "Multi-Trip" Routing Problem

### ISSUE THREAD

**Issue by nimahomami** [VROOM-Project/vroom#422]
Hello, 

First off, I can't thank you enough for what you've done with this project! I work for an under-resourced urban school district trying to implement school-meal deliveries to students' homes during this pandemic and this program you've created will be very useful for us and for the many food insecure children in our district!

My question is would you have any advice regarding how to set up a capacitated multi-depot vehicle routing problem where vehicles will likely have to return to a depot to refill before continuing on their route? I currently have it setup using the "jobs" object to mark delivery and pickup locations (with the pickup locations being depots). Am I doing it correctly? Here's my JSON file for reference (this is just an example, realistically there will probably be thousands of delivery locations vs. 200). 

[Example1.txt](https://github.com/VROOM-Project/vroom/files/5752680/Example1.txt)

I noticed in Issue #188 you advised another user on a similar so-called "multi-trip" routing problem dealing with a single depot that they define deliveries as "shipment" object. Is this possible still with a multi-depot vehicle routing problem where I don't know which delivery is associated with which pickup location?

Thanks in advance for your help!

**Comment by nimahomami** [comment]
One potential work-around I was thinking of in case Vroom doesn't handle multi-depot, "multi-trip" routing problems was to just use the clustering feature to assign each node to a depot and then handle it as a series of single-depot, "multi-trip" routing problems, but I'm not exactly sure how I would be able to just do the clustering in Vroom without the routing.

**Comment by jcoupey** [comment]
Happy to see this project used in such a context!

>  I currently have it setup using the "jobs" object to mark delivery and pickup locations (with the pickup locations being depots)

Using a `pickup` key for a `job` does not mean you'll be delivering what you're picking right after, but instead that you're bringing stuff to the end of the route, see https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#capacity-restrictions.

Modelling a pickup and delivery situation happens with `shipment` objects. This is the reason why the issue you mentioned has been closes, see https://github.com/VROOM-Project/vroom/issues/188#issuecomment-602462376. You should define a `shipment` object for each of the deliveries, the `delivery` key describing the delivery (what you currently have in your jobs) and the `pickup` key describing loading stuff at the depot.

The only potential problem I can think of is that by defining a shipment, you'll have to decide how to match a delivery with one of your depots. Is that a problem?

**Comment by nimahomami** [comment]
Yes, matching a delivery with one of the depots is my problem, since all I know is where the depots are, where the clients are, and which depots the vehicles are assigned to. Do you have any guidance about how to match a delivery with a depot?

**Comment by jcoupey** [comment]
>Yes, matching a delivery with one of the depots is my problem

Sorry, you already made that clear in your first message.

If you don't really have time constraints, what you could try is to simply describe your problem as a multi-depot VRP. In that case, the number of routes/trips from each depot will be the result of the capacity constraints. You can then use the various routes from the solution you get as single trips for one (or several) vehicles. For example if you need 20 vehicles from a depot, you're getting 20 routes in output. This means you can actually send 20 vehicles in parallel, but also 10 vehicles with 2 trips each, or 2 vehicles with 10 trips each.

For this, you'd have to define as many vehicles at each depot as the number of expected required trips from this depot. Actually you don't need to worry too much about this, because defining an excess of vehicles will result in the optimization phase deciding what are to most relevant depots to use.
Then you can simply define each delivery as a `job` (instead of using `shipment` objects), which has the extra benefit of reducing your problem size.

**Comment by nimahomami** [comment]
Ah, makes sense! Will introducing time constraints using this configuration you've just described likely result in all of the vehicles leaving their respective depots under capacity?

**Comment by jcoupey** [comment]
Yes, you might have vehicles leaving depot under capacity if the available working hours (`vehicle.time_window` key) become a tighter constraint than capacity. In other words if there is not enough time (travel duration + service time) to handle deliveries for a full vehicle.

The biggest problem (and why I mentionned "if you don't really have time constraints") is that if you have timing constraints imposed on jobs (`job.time_windows` key), then you may be forced to keep routes done in parallel by different vehicles rather than being able to concatenate them as single trips in any way you want.

**Comment by nimahomami** [comment]
Okay, makes sense. Thank you so much for your help!
