### ISSUE TITLE
Add Vehicles with no start and no end

### ISSUE THREAD

**Issue by cbeltrangomez84** [VROOM-Project/vroom#442]
It is possible to solve a TSP problem adding vehicles that has no start and no end location?

**Comment by jcoupey** [comment]
No, it's not possible because the solving approach implemented for the TSP is only designed to come up with a round trip. This is why you'll get an error if you submit such a vehicle.

Open optimizations are obtained by "cheating" on the instance description, not adjusting the actual solving. For example to force an open-ended trip, all costs from any location to the desired start location [are set to 0](https://github.com/VROOM-Project/vroom/blob/d30c26e6b9906eeb8018c53784500f5a6693d9f4/src/problems/tsp/tsp.cpp#L67-L75). We still compute a round trip but then the "phantom edge" back to the start is always cost-less and we only have to remove the last leg in output. There is a similar trick for an end-only route and a slightly more subtle one if start and end locations are different.

Can you expand on the kind of situation that would actually require defining no start **and** no end?

**Comment by cbeltrangomez84** [comment]
Hi, basically I have some pickups and deliveries and I only need the vehicle to start in any pickup step and after deliver the last package he will be free, no need to force a starting point (since any pickup location is valid) and no need to return to any place after the last package is delivered.

I did the following in order to get what I needed: I put one end point at the center of the city and no start point for all vehicles, when I got the vroom response, I replace for every vehicle the starting point using the first point the vroom solution gave me as first location to visit (pickup) and remove the end point. then I request vroom again and it works well.

Thanks a lot.

**Comment by danielcxt** [comment]
Couldn't we get the behavior cbeltrangomez84 wants by adding something like the following [this file](https://github.com/VROOM-Project/vroom/blob/d30c26e6b9906eeb8018c53784500f5a6693d9f4/src/problems/tsp/tsp.cpp#L64):
```
if ([some boolean]) {
	_matrix[_end][_start] = 0;
	for (Index i = 0; i < _matrix.size(); ++i) {
		if (i != _start) {
			_matrix[_start][i] = 0;
		}
		if ((i != _start) and (i != _end)) {
			_matrix[i][_start] = INFINITE_COST;
		}
		if (i != _end) {
			_matrix[i][_end] = 0;
		}
		if ((i != _start) and (i != _end)) {
			_matrix[_end][i] = INFINITE_COST;
		}
	}
}
```
Basically, just ignore the cost for the start stop to all other stops and the cost for all stops to the end stop.
