### ISSUE TITLE
How to define a vehicle with multiple time window objects?

### ISSUE THREAD

**Issue by alfredorico** [VROOM-Project/vroom#443]
I'm wondering, why is not possible to define multiple time windows slot for vehicle? (as jobs actually do). I think that is natural to think a vehicle has an schedule available. Eg: from 10:00:00 to 12:00:00, then from 17:00:00 to 20:00:00
Using break object seems the solution but it looks very awkward because it requires a programming to negate the schedules. I guess define a time_window [from 6:00, to 23:00] and then define multiple breaks negating the interval schedules. 

Is it the only solution?

Thanks a lot.

**Comment by jcoupey** [comment]
Having a single time window for a `vehicle` object is a design choice for the API. Maybe it's easier to think about it in term of "a resource available for a single route" than an actual vehicle.

If you have multiple shifts for a given driver, you can pass several vehicles in input: one per time slot. This works e.g. for multiple fixed-time shifts from a single depot, because it requires you to make sure the end point for a time slot is consistent with the start for the next slot.

The other way is to use breaks as you suggested. Breaks have two additional benefits:

- you don't have to worry about location consistency as they can occur anywhere depending on the actual route;
- they are much more flexible time-wise and can be shifted depending on what needs to be done before and after.

**Comment by alfredorico** [comment]
Thank you for your advise @jcoupey. Duplicating the vehicle, each one with its time_window slot (am and pm slot respectively) works perfectly.
