### ISSUE TITLE
Using -c planning mode

### ISSUE THREAD

**Issue by tomjakobs1** [VROOM-Project/vroom#446]
How would i set planning mode ? Is this sendt trough options ?

Thanks

Tom

**Comment by jcoupey** [comment]
"Activated using -c" from the docs means you need to add the `-c` flag when running the `vroom` command. See `vroom -h` for a comprehensive list of options.

**Comment by tomjakobs1** [comment]
Ok. so would this be availablet trough vroom express 

Thanks again
Tom

**Comment by tomjakobs1** [comment]
So i did a addition to vroom express index.js to add the -c command. 
But i get the error: 
/root/vroom/bin/vroom: invalid option -- 'c'

Any suggestions ?

Thanks Tom

**Comment by jcoupey** [comment]
I suspect you're running a version of `vroom` that does not include the `plan` mode. It's currently only available from `master` and `v1.9.0-rc.1` (release candidate for next version).

I'm closing this ticket because it's not really about the solving backend. Feel free to open another one in the vroom-express repo if required.

**Comment by tomjakobs1** [comment]
Thanks. I got it. I was running a older version.
Best regards Tom
