### ISSUE TITLE
read json problem from stdin

### ISSUE THREAD

**Issue by stefanocudini** [VROOM-Project/vroom#457]
```bash
cat myproblem.json | vroom -i - 
```

this not work, actually vroom accept only input as string in last parameter?? or a filename with -i param?

I would need to pass input json in stdin in my nodejs spawn

**Comment by jcoupey** [comment]
From `vroom -h`:

```
	-i FILE,			 read input from FILE rather than from stdin
```

The `-i` flag serves as a way to **not** read from standard input, but from a file.

On the other hand, you have a point that using a pipe does not seem OK: `cat myproblem.json | vroom` does not spot a regular problem in input. This is maybe somehow related to escaping because `vroom "$( cat myproblem.json )"` does work.

**Comment by krypt-n** [comment]
I think Stefano is right here. The current implementation does not read from `stdin` but instead considers the last argument to be the json string if `-i` is not given:
https://github.com/VROOM-Project/vroom/blob/02a391503131e0ae7e3f2af3fc716df1787a663e/src/main.cpp#L157-L170
It seems that the documentation of the `-i` option should refer to the last argument instead of stdin.
In C++ terms, reading from stdin would involve reading the json string from `std::cin` and this would make the pipe example work.

**Comment by krypt-n** [comment]
As a fun trick, `cat problem.json | vroom -i /dev/stdin` seems to work on my system :laughing:

**Comment by jcoupey** [comment]
Yes, the piece of code pointed out above does not properly handle reading from stdin. It's been there for quite a long time and I had no idea `cat input.json | vroom` was not working.

> It seems that the documentation of the -i option should refer to the last argument instead of stdin.

I think we should fix the behavior rather than the docs. Piping out to a command is a rather common scenario and anyone would expect that to work out of the box. Did not give this a close look, but it seems like switching to using `std::cin` would not be a big deal?
