### ISSUE TITLE
Using relative time_windows in Breaks

### ISSUE THREAD

**Issue by ky4mail** [VROOM-Project/vroom#467]
Hello,

I'm wondering if would be possible to specify Breaks time_windows in relative format while other windows (Vehicle/Job) in absolute? The reason behind is driver must not exceed maximum hours of driving, then have a break. Since optimization is moving start time , absolute windows in breaks won't work.

Thank you

**Comment by jcoupey** [comment]
Providing a flexible start time for the first break using an absolute time window based on the start of the vehicle time window allows to set a higher bound on maximum work time before the break. But you're right that depending on the work load the start time can be pushed later than the vehicle time window start.

We don't have a way to impose a constraint on work time between actual route start and break. At first sight, it looks like the situation you point out is only a problem if you have an over-capacity fleet. Can you maybe expand a bit on your use-case?

**Comment by ky4mail** [comment]
Thank you. In the long running trips span over multiple days driver must have a break to ensure safety. The most common rule is to have maximum number of hours to drive between breaks. This is not the case for the local deliveries within the same day.  Here is the link to the US service of hours regulation [https://www.fmcsa.dot.gov/regulations/hours-service/summary-hours-service-regulations](url) . It is pretty complex, however the main idea is to **"May drive a maximum of 11 hours after 10 consecutive hours off duty."** What I would expect to set in the model is the first Break with duration 10 hrs with start time as  +11 hours from start of the actual route start. The second Break will be again with duration 10 hrs with start time as +32 hrs from route start.

Route Start
11 hrs. Drive
10 hrs. Break
11 hrs. Drive
10 hrs. Break

Obviously, with time windowed deliveries Breaks make significant impact.

Hope that explains the need.

Thank you

**Comment by jcoupey** [comment]
Yes, the same kind of fancy rules apply in other parts of the world as well.

The problem here is that for efficiency reasons, we don't actually compute actual start/arrival times for route steps. We only store margins (earliest and latest dates) for each step. The rationale is that it provides enough information to check for timing constraints validity for route modification options *without going through the whole route*, the kind of check we perform extensively. On the other hand, checking relative time length between route steps would mean that every validity check would have to go through the whole route and that would incur a **huge** computational overhead.

So I'm afraid we won't be able to support this kind of modelling any time soon. On the other hand in many situations it's somehow possible to come up with an ad-hoc modeling that approximates the expected behavior. In that case, the business logic related to regulations and use-case specifics has to be implemented in a client-side layer.

**Comment by ky4mail** [comment]
Thank you, I do appreciate your work.
