### ISSUE TITLE
Use minimum number of vehicles in solution

### ISSUE THREAD

**Issue by vercom** [VROOM-Project/vroom#495]
Solution uses always all vehicles provided.

I need to solve jobs/shipments with minimum number of vehicles.
Is this possible ?

**Comment by jcoupey** [comment]
The current optimization objective is overall travel time. In a typical single-depot situation, reducing the number of vehicles leads to an overall cost reduction, but this is not always the case. For example if you have vehicles start/end geographically distributed, it may be cheaper to use one more vehicle because it's closer to some of the tasks.

You can try solving the problem several times with a varying number of vehicles in input and see what solution works best for you overall.

**Comment by hugojanruiter** [comment]
We have done something similar to optimize for our use case. But wouldn't it make sense to add an option to set a certain base cost for adding a vehicle to a solution? In the real world it is often cheaper to not schedule an extra vehicle, since it means you have to schedule an extra driver too. I understand that given a certain amount of driving time to the first stop and from the last stop back to the depot is already sort of a base cost, but in the real world this is often higher.

**Comment by jcoupey** [comment]
> wouldn't it make sense to add an option to set a certain base cost for adding a vehicle to a solution

This is definitely something we need to add at some point that would provide a better way to deal with this situation (and others in different tickets).

I don't think we have a feature request clearly stating this, so I'll create one and close the other tickets with a reference.

**Comment by vercom** [comment]
Julien,
This would be a great option !

Met vriendelijke groeten,

Jean-Marie Huys

www.vercom.be<https://www.vercom.be/>
***@***.******@***.***>

[v4busemail]

Van: Julien Coupey ***@***.***>
Verzonden: woensdag 9 juni 2021 11:17
Aan: VROOM-Project/vroom ***@***.***>
CC: Jean-Marie Huys ***@***.***>; Author ***@***.***>
Onderwerp: Re: [VROOM-Project/vroom] Use minimum number of vehicles in solution (#495)


wouldn't it make sense to add an option to set a certain base cost for adding a vehicle to a solution

This is definitely something we need to add at some point that would provide a better way to deal with this situation (and others in different tickets).

I don't think we have a feature request clearly stating this, so I'll create one and close the other tickets with a reference.

**Comment by jcoupey** [comment]
Closing as a feature that would solve this is now ticketed in #528.
