### ISSUE TITLE
Restricting algorithm calculation to geospatial poligon

### ISSUE THREAD

**Issue by alfredorico** [VROOM-Project/vroom#498]
Hi, 

This could sound crazy. But is there a way for restricitng/balancing/considering algorithm route calculation adding a poligonal region for excluding "jobs"?. The reason is that jobs locations are unkonwn (comes from external source) and passed directly to algorithm. So when constructing input json, I'm wondering to know if an additional poligonal parameter included could restrict the calculation to indicated zone.

Thanks in advance.

**Comment by jcoupey** [comment]
No, we don't have this option internally simply because we wouldn't do it any differently than with a dedicated pre-processing step.

If you want to rule out some jobs from your backlog, you should just not include them in the payload for `vroom`. You'll have to run the point-in-polygon check yourself (check available libraries in your favorite language). The additional benefit is that you can add extra rules that make sense for your use-case, e.g. applying different priority levels based on being in a given area.

**Comment by alfredorico** [comment]
Thank you very much @jcoupey
