### ISSUE TITLE
About the Special Matrix Problem

### ISSUE THREAD

**Issue by Akif95** [VROOM-Project/vroom#502]
Hello to everyone,

The following sample problem is given about the use of a special matrix at [this address](https://github.com/VROOM-Project/vroom/blob/master/docs/example_2.json).

`
{
  "vehicles": [
    {
      "id":0,
      "start_index":0,
      "end_index":3
    }
  ],
  "jobs": [
    {
      "id":1414,
      "location_index":1
    },
    {
      "id":1515,
      "location_index":2
    }
  ],
  "matrices": {
    "car": {
      "durations": [
        [0,2104,197,1299],
        [2103,0,2255,3152],
        [197,2256,0,1102],
        [1299,3153,1102,0]
      ]
    }
  }
}
`

When I send this route to my server, I get the following response.

`
{
"code": 2,
"error": "No start or end specified for vehicle 0."
}
`

The start_index and end_index parameters took part in the problem, but I still get an error.

Thank you in advance for your support.

**Comment by krypt-n** [comment]
The example works on my machine. Could you describe how you send the problem to your server?

**Comment by jcoupey** [comment]
My guess is this may be related to the recent introduction of the `matrices` key: the link you point refers to the `master` docs and you'll need to build from `master` or the `release/1.10` branch in order to use this syntax.

In short, if you're using `v1.9.0` or previous the `matrices` key is ignored, so you need to use `matrix` instead.

**Comment by Akif95** [comment]
Thank u, problem solved.
