### ISSUE TITLE
minimum load / vehicle

### ISSUE THREAD

**Issue by vercom** [VROOM-Project/vroom#505]
Is it possible to have a minimum load for each type of vehicle. The problem that I have to solve is 
shipping different workers to different locations with vans. There are vans for 8 people and vans for 16 people. I want 16 persons busses to transport more than 8 people.  

example situation :  I have to pickup 130 persons at 50 different locations and bring them to 4 companies. 
there are timewindows defined for each pickup and delivery.

I have 50 minivans with a capicity of 8 persons and  4 busses  with a capacity of 16 persons available.

the number of persons, minivans and busses available, changes every day.

So I think I have to solve this problem in a few steps. 

Step 1  solve with only the available number of busses for 16 persons. ->( here I would have the minimum load )
Step 2 Exclude the persons already solved in step 1 and solve the remaining shipments with only minivans. 

For step 2 : In order to solve the problem with a minimum number of vehicles, I know that if I try with 100 minivans only the minivans needed will be used. (in this case there will be no fare sharing).

Maybe there's a better solution for this ?

**Comment by jcoupey** [comment]
No there is no such option to ensure a minimum load.

The fact that you are getting under-loaded vehicles in output is a consequence of how the fleet size/availability/spread matches the demand. Imposing this as a new constraint (or using a two-step solving approach) will only narrow down the solving options and result in a more expensive solution in term of overall travel time.

In short: you're probably getting solutions with not all vehicles full because it's cheaper that way based on the current optimization objective. What I'd like to know is: if you're prepared to spend more time on the route in order to fill the vehicles, then what makes this option more interesting in your use-case?

**Comment by vercom** [comment]
Hello, in my case if 12 persons are at the same pickup location at the same time  and only 8 persons can step on the bus which has place for 16 people , the 4 persons that have to wait for a minivan will not be very understanding. There we are prepared to spend more time on the route. We are working with people and not cargo !

**Comment by jcoupey** [comment]
Got it. First you need to check your solutions on why higher capacity vehicles are not used fully (hint above: it's *probably* cheaper). This will provide some pointers on how to design your fleet to get a solution that better fits your use-case.
