### ISSUE TITLE
Route planning with multiple collections and a several delivery locations with demand

### ISSUE THREAD

**Issue by aleksandrd** [VROOM-Project/vroom#516]
We came accross a task which I cannot wrap my head around, even though we made about 20 different projects with Vroom already. So maybe the community could help me out on that.

So imagine there is a company that collects milk from farmers. They have dozens of vehicles with different volume they can take in. It is known how much milk every farmer can provide. So far so good, simple route planning.

Now, they also have several factories and every factory needs certain amount of milk to be delivered to it. Let's say one needs 30 tons, another 50 tons, another 60 (and all the rest if farmers can provide more that full demand is, but let's say for simplicity that farmers provide exactly how much they need).

All vehicles start from one base, go for milk collection, then return to factories to unload and go back to sleep in their base.

Right now they just manually set  which factory every vehicle goes to as the last point in the route. 

The task we are trying to solve is let the algorithm to decide how to optimally collect milk to fill the demand for factories, i.e. not to assign vehicle to factory.

Any help on how to achieve that is much appreciated!

**Comment by jcoupey** [comment]
You're basically facing two problems that are linked but different:

1. How to assign collection points to factories
2. Given an assignment choice, how to get efficient routes

VROOM is able to handle the later but in order to model the underlying VRP you have to use a solution from problem 1.

You could try getting some kind of heuristic matching between collection points and factories, the hardest part being probably to fulfill the capacity requirements. On the other hand, this looks like a classical assignment problem so you may have some luck using a linear programming approach.

**Comment by aleksandrd** [comment]
Yes, you're right, the second point is simple once you have assigned the collection points (farmers) to delivery points (factories), just use shipments and VROOM will first collect everything and then bring it to one place, that works fine.

Assigning though doesn't seem to be linear since the demand can be different, plus say some collection points are located somewhere between the factories, so it's hard to decide which should belong where. 

Maybe it is possible only using some kind genetic algorithm...

**Comment by jcoupey** [comment]
Yes, the problem is not trivial, I meant "linear" as in [linear programming](https://en.wikipedia.org/wiki/Linear_programming). 

Because you'd have decision variables (which collection gets assigned to which factory), you'd end up with a mixed integer program.

**Comment by aleksandrd** [comment]
ok, got it.
Thanks for your replies, best regards!
