### ISSUE TITLE
Rewrite to Rust

### ISSUE THREAD

**Issue by tomaszbawor** [VROOM-Project/vroom#527]
Hello, 
I would like to rewrite your library to rust. Is there any potential issues that you may find most problematic that I should spend most of my time to research?

**Comment by jcoupey** [comment]
This sounds like a lot of fun for a Rust lover, but the most problematic issue I see is spending a huge amount of time rewriting an existing piece of software and then having a hard time maintaining the upstream changes in another language. ;-)

Jokes aside, it would help to understand why you want/need a Rust version? For example if it's to use more conveniently from Rust then you might consider simply implementing a new [`vroom-express` wrapper](https://github.com/VROOM-Project/vroom-express/wiki/Third-party-clients).

**Comment by tomaszbawor** [comment]
I initaly come from Java/JS world and I am lacking good development tools. I believe that rust ecosystem is mature enough to be easy usable to develop some piece of software with testing and benchmark. Also while rewriting I want to learn the algorithms behind your software in order to tweak them to my needs.

**Comment by jcoupey** [comment]
> rust ecosystem is mature enough

Of course the matter of likings and tastes are not to be discussed, yet one may argue that C++ has some kind of mature ecosystem too. ;-)

The "learning" part totally makes sense. But have you considered directly contributing to this project instead of rewriting it to a different language? My point is that we have a couple feature requests out there that would require taking a deep dive in the solving approach. Working on those would be a great way to learn without having to rewrite everything.

You'd still be able to tweak the algorithms to your needs, that's the whole point of having a BSD-licensed project. This would require much less effort on your side while being useful to the project since your needs may turn up as interesting features for other users.

**Comment by jcoupey** [comment]
Closing now, @tomaszbawor feel free to reopen if you have more feedback.
