### ISSUE TITLE
Q: are matrix requests filtered when using "skills"

### ISSUE THREAD

**Issue by nilsnolde** [VROOM-Project/vroom#535]
Do you filter the matrix request for invalid pairs (e.g. different `skills`) so it's less routing computation?

**Comment by jcoupey** [comment]
Nope. We could probably do something like this but I suspect it would be both complex and not that impactful.

1. It's not totally straightforward to know which entries can be safely ignored: if two tasks are not doable in a row for one vehicle, it does not mean the travel time between them won't be used since they could also fit together in another vehicle.
2. It would mean that all skill related checks should always be done first whenever we lookup a travel time. Frankly I'm not sure this is the case currently (we sometimes use travel times to compute bounds to cut some searches early), and that would be asking a lot on the internal implementation to make sure we never retrieve an inconsistent value.
3. When filtering pairs for one vehicle and all tasks, we'd be able to rule out all incompatible tasks locations for the vehicle lines in the matrix. But frankly that's simply changing from one-to-many to one-to-no-that-many. For most routing engines, it's simpler (and probably faster) to compute the whole matrix than trying to break it down, especially since in most cases it won't be that sparse.

Do you have a specific use-case where you think that would be beneficial?

**Comment by nilsnolde** [comment]
> Do you have a specific use-case where you think that would be beneficial?

Nothing concrete yet, but one client was "complaining" that he tried to differentiate areas of responsibility via applying `skills` to vehicles and jobs, but didn't see a significant performance gain at ~1000 jobs and 20 vehicles. I didn't (yet) reproduce what he's doing on his side, but suspected this could be one factor. He's using ORS, not OSRM, the "problem" would get a lot worse for valhalla I guess. 

I don't think the effort involved really justifies the use case, I'd rather tweak the routing engine layer in this case. Thanks for the details though!
