### ISSUE TITLE
computing_times in Output

### ISSUE THREAD

**Issue by booper** [VROOM-Project/vroom#538]
I see computing_time  parameter in output, but i couldn't find it in API documentation, may you please explain what does it mean?   

```
[summary] => Array
        (
            [cost] => 1511
            .........
            [computing_times] => Array
                (
                    [loading] => 48
                    [solving] => 0
                )

        )
```

**Comment by jcoupey** [comment]
When launching `vroom`, the C++ code looks at the clock now and then and reports elapsed difference in ms. The `loading` phase is about everything done before launching actual solving (parsing the json input and building C++ objects, getting matrices from routing engines and performing various consistency/preflight checks), `solving` is the time it takes for the core `cvrp::solve` or `vrptw::solve` function to complete. If you request route geometry, you'll get another `routing` entry for the time it takes to retrieve all route details.

This is really meant for debugging and benchmarking, that's why it's not "officially" part of the API to avoid being tied with a specific format.

**Comment by jcoupey** [comment]
Closing as answered.
