### ISSUE TITLE
Traffic ban hours

### ISSUE THREAD

**Issue by HamdanSU** [VROOM-Project/vroom#548]
We are using vroom to find the best route between a set of points. A problem we are facing is that we need to know if there are any traffic bans on the created path. It will help us choose between going with another road or wait until the traffic ban ends based on this information.

Is there any way using vroom to determine or set the traffic ban hours on the roads that the route will pass through?

**Comment by jcoupey** [comment]
If I'm getting it right, you want to now whether some route in the solution goes through a zone with time-dependent restrictions at the wrong time?

**Comment by HamdanSU** [comment]
Yes, I want to know this information while creating the route before the time-dependent happens.

In our country, trucks or heavy vehicles, in general, are not allowed to go on the highways in the rush hours and certain times of the day. We want to know this information beforehand so we can avoid this issue.

**Comment by JimboManiac** [comment]
I would like to 2nd this feature Julien, as just per example also, I live in a port city, and mainly during off peak hours, but then again, also depending on tide levels, road with draw bridges are closed to let ships pass.

I am new to the project also, have not installed yet, and have not researched into where this data could be got "real time" in order to update or change a database.

https://www.virginiadot.org/travel/hro-tunnel-default.asp


Jim

**Comment by jcoupey** [comment]
The view we have on travel times come through the matrix we get from the routing engine. It's a static view of the situation, so any road with time-dependent restriction is either always closed or always open. That's not something we decide within VROOM, it depends on how you setup the underlying routing engine.

What you could do is add a post-processing step to the solution and check to see if there's a problem based on actual route path and ETA. That's different from handling time-dependent travel times/speeds within the optimization process (which is not currently possible).

**Comment by HamdanSU** [comment]
Thank you for your answer.
