### ISSUE TITLE
Is it possible to deliver all jobs on one route leg during first pass?

### ISSUE THREAD

**Issue by alekw** [VROOM-Project/vroom#551]
Hi, I am planning jobs with osrm + vroom like for couriers. The results are good, however I faced one issue.
Consider there is only one route to some area, then the vehicle drives around that area and goes back using this only route.
Some jobs will be served when going one way, while some would be served when going back.

What I would like to achieve is to deliver all of them during first pass (if other constraint are met) - items are delivered earlier, less cargo stays in vehicle, and there is a chance to try delivery on the way back if recipient was not at home.

Both routes are equally good in terms of time & distance.
Currently I am changing order of jobs manually after generation.
Is there some way to do it using vroom?

**Comment by ibrahimsk1** [comment]
I think you are talking about "path complexity". You may need to change the objective function to achieve this because in this project only distance is minimized. I have included research paper looking into this topic and a picture from it.

![image](https://user-images.githubusercontent.com/35404031/128155984-ef613b48-6510-4ed4-a976-acf487508218.png)
https://www.researchgate.net/publication/271154021_Indentations_and_Starting_Points_in_Traveling_Sales_Tour_Problems_Implications_for_Theory

**Comment by jcoupey** [comment]
> Both routes are equally good in terms of time & distance.

You may indeed run into situations where performing a task incurs the same cost at several places in the route if for some reason the route goes back through the same roads.

In that case and without other constraints, tasks being assigned rather on the way or back is a result of how the internal route building and improvement happens. This may totally look like a random choice in output but we don't have a direct way to avoid that.

If you have a way to spot those tasks before-hand, then what you could try is translate the "items are delivered earlier" into a time window constraint.

**Comment by alekw** [comment]
Since my routes are rather short and compute fast, and I dont have time constraints, I am thinking of using vroom like that:
If I can squeeze further  waypoint inbetween two earlier ones, and the time and distance doesnt change, I will do that.
Thanks for all answers.
