### ISSUE TITLE
Handle mutually exclusive skills

### ISSUE THREAD

**Issue by stefanhahmann** [VROOM-Project/vroom#569]
Hi,

I am wondering, if there is a possibility to let vroom know that 2 skills are mutually exclusive.

Let's consider the following example:

There are 2 vehicles that both have skills "1" and "2" (capacity=2) and there are 2 shipments (same pickup time+location and same delivery time+location), one shipment that requires skill "1" (amount=1) and one shipment that requires skill "2" (amount=1). 
However, in my use case, there is a contraint that shipments which require skill "1" and skill "2" must not be on a vehicle at the same time. So while both vehicles would actually able to handle both shipments, it would still require both vehicles to drive, since the two shipments cannot be in one vehicle.
I am attaching an example where I am trying to find a way to get two routes with each vehicle serving one shipment, no matter which vehicle serves which shipment.

[mutuallyExclusiveSkillsExample.txt](https://github.com/VROOM-Project/vroom/files/7122970/mutuallyExclusiveSkillsExample.txt)

**Comment by jcoupey** [comment]
The whole skills interface comes down to providing valid matches between vehicles and jobs. There is no way to use that in order to discard associating some tasks in the same route. If you badly need this with the current setup, it could be the result of:
- other constraints (probably only practicable with specific small instances);
- prealocating relevant skills to vehicles, in your example only assign one skill per vehicle. This requires to choose beforehand which vehicle has which skill.

> the two shipments cannot be in one vehicle

If you mean they cannot be in the same vehicle **at the same time** then it's a different problem than forbidding allocating them to the same vehicle. In that case, you can probably come up with something that works using a dedicated capacity component.

**Comment by stefanhahmann** [comment]
`If you mean they cannot be in the same vehicle at the same time then it's a different problem than forbidding allocating them to the same vehicle. In that case, you can probably come up with something that works using a dedicated capacity component.`

Yes, this is exactly, what I meant and I also think that your suggestion probably works. In order to document it for others facing the same problem in the future, I will give an example:

Let's assume, a shipment has 2 features that need to be considered, then it would be possible to say the vehicle has these properties: 
"skills": [1, 2]
"capacity": [1, 1] (the first number stands for the capacity for skill '1' and the second number stands for the capacity for skill '2')

A shipment, which requires skill '1' but cannot in the same vehicle at the same time with a shipment that requires skill '2' could be described as follows:
"skills": [1]
"amount": [1, 1]

This way the shipment uses up the capacity of the vehicle for skill '1' and skill '2' shipments even though it actually is only a skill '1' shipment. However, this way the constraint that skill '1' and skill '2' features cannot be in the same vehicle at the same time can be enforced.
