### ISSUE TITLE
Early arrivals:  time windows - soft constraints?

### ISSUE THREAD

**Issue by MachineLearningIsEasy** [VROOM-Project/vroom#579]
Hi guys!

Firstly, I am very grateful for the tremendous work on development VROOM. Brilliant work!

We have found that when solving the VRP-TW problem, about 10 percent of arriving at the point before time windows.
Are time windows soft constraints?

**Comment by MachineLearningIsEasy** [comment]
[50_mtrx.txt](https://github.com/VROOM-Project/vroom/files/7203208/50_mtrx.txt)
Request example

**Comment by jcoupey** [comment]
Arriving at the location before time window start does not mean that the timing constraint is violated. In your case, it means that the vehicle is idle until the task availability date. This shows up in `waiting_time` in route steps. In general, actual task service start is `arrival + waiting_time`.

Now the reason why you're getting so much waiting time is because of the narrow disjoint time windows in input. See for example the timeline for one of the vehicles in output (waiting times show up in orange):

![route_1](https://user-images.githubusercontent.com/6639205/134183109-3076c778-7d3f-453b-9935-558048c3da83.png)

**Comment by MachineLearningIsEasy** [comment]
@jcoupey Thank you for your reply!
