### ISSUE TITLE
Ability to include additional request options to the OSRM API

### ISSUE THREAD

**Issue by egofer** [VROOM-Project/vroom#584]
Hi,

Is it possible to include additional parameters in the OSRM API call? 

I need to model a series of urban solid waste collection routes but it is essential that trucks approach the garbage containers on the right side of the road, since some vehicles are side-loading (`skill`) and this conditions the routes. In addition, on two-way roads, traffic ordinances do not allow trucks to cross the road to collect containers located on both sides of the street.

OSRM allows modeling this behavior through the parameter `approaches=curb` and it would be very useful to be able to include this restriction for cases of route optimization like this (or other parameters such as `radiuses` with which to limit the search for containers to a certain distance radius, for example).

**Comment by nilsnolde** [comment]
yes, that's been discussed a few times, I can't find the issue right now if there was a dedicated one. for osrm (and ors) it's fairly valuable, but it's really essential for valhalla usage. as a workaround though you can always pre-compute the matrix with your OSRM service and inject a custom matrix to vroom to do the solving based on these slightly different routes. you probably will have to also compute the final routes in the end yourself instead of relying on vroom's geometry output.

can you remember @jcoupey if there already was an open issue? it's probably not a priority for you at this point and it might've been getting a little more complex now with mixed-profile vehicles (didn't follow vroom very closely lately), but I'd still like to do this at some point. (no need for implementation suggestions, I'll get back to this when I'm not so overloaded)

**Comment by nilsnolde** [comment]
> Also note there is an experiment/extra-valhalla-options branch which does just that

that's targeted at you @egofer , that branch was adding hard-coded extra parameters to valhalla queries. dynamic is what I'd be interested in for better valhalla integration.

**Comment by egofer** [comment]
Thanks for your comments, as far as I can see this issue has been raised before and is recurrent. I will carefully review the links provided by @jcoupey with the alternatives raised. I see that there is information on how I could move forward, even if not directly.

Please consider dynamic aggregation of parameters in the future. In Municipal Solid Waste (MSW) collection services, factors such as the type of container loading (rear, right side or left side) or limitations on vehicle dimensions, tonnage, gauging or U-turns greatly condition the types of truck routes. This can be easily solved through the parameters provided by the routing engines.

**Comment by nilsnolde** [comment]
> Please consider dynamic aggregation of parameters in the future

you can also consider to fund such a feature. in this project there are enough consulting companies involved, including the owner's company VersoOptim. that'd greatly speed up the implementation.
