### ISSUE TITLE
Keep tcp connections alive

### ISSUE THREAD

**Issue by ilibar-zpt** [VROOM-Project/vroom#610]
I've been doing some tests recently and noticed that Vroom makes requests to OSRM with `Connection: close` header, which causes a new connection on each request instead of reusing an already open one.
It probably is not very noticeable when both are on the same host, but otherwise it results in way too much i/o overhead.

Is there any specific reason for reopening connection on each request? Should this be fixed? Am I missing anything?

**Comment by jcoupey** [comment]
That's an interesting question. Currently the http requests are handled using asio in `HttpWrapper::send_then_receive` and its SSL counterpart `ssl_send_then_receive`:

https://github.com/VROOM-Project/vroom/blob/4d6bc4e1fd82af02b0af2eeb7d8103f8f40bcc6b/src/routing/http_wrapper.cpp#L36-L84

As a result a new connection is opened (and properly closed) for each call, either to compute a matrix or a route (when using `-g`). This means at most `1 + number of routes in solution` connections per solving. Now keeping a single connection open throughout the solving would probably be doable, but would require some changes since the asio objects have no lifetime outside the scope of the `*send_then_receive` calls.

Also in case of a long solving time, maintaining (and relying on) an idle open connection may also not be such a good idea.

> otherwise it results in way too much i/o overhead

Can you elaborate on this: how do you notice/measure such overhead? Can you share steps to reproduce?

**Comment by jcoupey** [comment]
Closing as stale. Feel free to reopen with new input if required.
