### ISSUE TITLE
Set minimum number of jobs per vehicle

### ISSUE THREAD

**Issue by mufassir-khan** [VROOM-Project/vroom#612]
Hi, vroom is really fast and giving amazing solutions. I was wondering if we can enforce a constraint like at least 'n' number of jobs must be assigned to a vehicle or vehicle should not be used. Is there a way to implement this?

**Comment by jcoupey** [comment]
No, there is no such constraint and no easy way to implement it, at least not by making sure it's always respected. Can you elaborate a bit on the context and why you'd need to enforce this?

**Comment by mufassir-khan** [comment]
So, we solve VRP very frequently. In each run, some jobs are assigned to available vehicles. The unassigned vehicles or jobs are sent again to the solver in the next run, Thus it's a continuous process.

Now, let's say that we have 5 vehicles, each vehicle has capacity of 10 jobs, and due to construct of custom distance matrix, the assignment comes in such a way that 1 vehicle gets 10 jobs, 2 vehicles get 9 jobs each while other 2 vehicles get 1 job each. This makes utilisation of last 2 vehicles very inefficient. We want the solver to not to use last two vehicles if they are assigned less than 6  orders(let's say).  We want the solver to either drop the two single assigned jobs or assign them to other vehicles with greater utilisation.

**Comment by jcoupey** [comment]
> due to construct of custom distance matrix

Modifying the cost matrix to try favoring some behavior can have a lot of side effects, including getting "unnatural" solutions that look cheap from the cost perspective but dumb in practice. You probably want to make sure you're not creating (or worsening) the problem in the first place by introducing cost distortions.

> We want the solver to either drop the two single assigned jobs or assign them to other vehicles with greater utilisation.

One thing that could help avoid "small" routes and prefer higher utilization of vehicles would be #528.

**Comment by mufassir-khan** [comment]
Since we have `max_tasks` feature, can we add `min_tasks` as well to incorporate this requirement?

**Comment by jcoupey** [comment]
Well it's not as simple as changing a `max` to a `min`. Using a `max_tasks` is actually easier since it just means that routes with too many tasks are discarded (deemed invalid). There are several additional difficulties with `min_tasks`:

- you can never be sure that's it's even doable to force a min number of tasks in a route without making it invalid with regard to other constraints;
- routes are created iteratively in the first place by adding tasks one at a time so a `min_tasks` constraint could not be applied at first since then all intermediate (smaller) routes would be invalid.
