### ISSUE TITLE
Does vroom officially support double attributes?

### ISSUE THREAD

**Issue by mgalati13** [VROOM-Project/vroom#633]
I tried changing in typedefs.h:
   using Cost = double;
   using Gain = double;
   using Distance = double;
   using Duration = double;  
   using Capacity = double;

But then on my example, an assertion failed (and it was not just tolerance related) in local_search.cpp:
  assert(new_cost + best_gain == previous_cost);

**Comment by jcoupey** [comment]
We've put quite some effort into avoiding floating point arithmetic (and the related limitations). This is why we use integers all along. I would definitely expect some things to break if you simply switch to `double` types, typically the assertion you mention can easily fail due to precision problems.

On the other hand, you hardly really ever need double precision: durations are seconds so rounding does not seem to be a big problem, and for other values you can usually scale things to use integers. On a related matter, see [this note](https://github.com/VROOM-Project/vroom-scripts/tree/master/benchmarks/VRPTW#costs-evaluation) on how we compare to benchmarks using double precision.

Can you share why you want to use double precision instead of sticking to integers?

**Comment by mgalati13** [comment]
The main reason was to handle non-integer values - e..g, how travel time (duration) and cost is not integer. In fact, our capacity and demand might not be integer as well. But, I agree, that in most practical applications we can scale to avoid the need for double arithmetic. From an API perspective, it might be nice if vroom did this for the user. But, in the mean time, I can scale on my end. Thanks!

**Comment by jcoupey** [comment]
Closing as answered.
