### ISSUE TITLE
Question about VehicleStep

### ISSUE THREAD

**Issue by jonathf** [VROOM-Project/vroom#643]
I am trying to understand the model which vroom presents here, and I am wondering why there are `VehicleStep` associated with start and end.

Lets take a scenario. If we define Vehicle and we want it to stop working at 1200, we can either use `TimeWindow(0, 1200)`, or we can set a `VehicleStep(STEP_TYPE::END, forced_service)`.The `forced_service` will then have to be defined with either:
* `before=1200` which is equivalent to `TimeWindow` constraint I think.
* `at=1200` is similar to `TimeWindow`, except we now force the vehicle to idle until 1200 in case the jobs are done early. 
* `after=1200` is unconstrained for an end step, but will also idle in case jobs complete early.

Now forcing a vehicle to idle is different functionality wise, but I fail to see it as something useful.

Have I interpreted the different scenarios correctly? Is vehicle step association to the end points just a convinience, or do they bring bring extra functionality, but I am not seeing it?

**Comment by jcoupey** [comment]
> before=1200 which is equivalent to TimeWindow constraint I think.

I think you're referring to the `service_before` key and though they are somewhat similar it's different from the TW deadline because they are used in different contexts (see https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#solving-mode).

In default solving mode, using `[0, 1200]` forces a deadline on the end step ETA. In this mode the `service_*` keys are not interpreted at all. Instead, the `vehicle.steps` array is used to seed to optimization search (see https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#vehicle-steps).

The `service_*` keys are only meaningful in plan mode. Since usual TW constraints become soft in that context, the `service_*` keys are a way to set additional hard constraints.

**Comment by jonathf** [comment]
Ah, that explains the difference. Thank you for the answer.

It is interesting to learn about the inner mechanics of the code.
