### ISSUE TITLE
small example, odd results, depot != 0

### ISSUE THREAD

**Issue by mgalati13** [VROOM-Project/vroom#656]
I am using the C++ API. This is a VRPTW with very wide time windows. So, basically just CVRP. 

The matrix is just the following (with bigValue=700 for all missing arcs):
Matrix i:1 j:0 -> 1
Matrix i:0 j:2 -> 1
Matrix i:3 j:1 -> 1
Matrix i:2 j:3 -> 1
Matrix i:3 j:4 -> 1
Matrix i:5 j:3 -> 1
Matrix i:3 j:6 -> 100
Matrix i:4 j:5 -> 1

The depot=3, so the start=end=3 for all vehicles.

All customers have demand=1 except for customer 6 which has demand 3. The vehicle capacity is 3 and we have 6 vehicles available. 

A trivial solution exists with routes:
3-6-3
3-1-0-2-3
3-4-5-3

In the end, VROOM fails to find a solution and returns:
Total cost: 207
Unassigned: 1
0
 -->START
nodeId=0
nodeId=6
nodeId=0
 <--END
 -->START
nodeId=0
nodeId=1
nodeId=0
 <--END
 -->START
nodeId=0
nodeId=2
nodeId=0
 <--END
 -->START
nodeId=0
nodeId=5
nodeId=4
nodeId=0
 <--END

The final result is starting at node 0, even though the depot is 3. 

If I rearrange the data so that the depot=0, then it solves it fine. Is this just bad luck? or is there some issue with using depot != 0?

**Comment by mgalati13** [comment]
If I feed it a complete graph (with cost=1 for all arcs), it finds a full solution (unassigned=0), but the solution still starts from node 0 (not the depot, node 3). So, I am guessing there is some issue when the depot != 0?

Total cost: 9
Unassigned: 0
 -->START
nodeId=0
nodeId=6
nodeId=0
 <--END
 -->START
nodeId=0
nodeId=2
nodeId=1
nodeId=0
nodeId=0
 <--END
 -->START
nodeId=0
nodeId=5
nodeId=4
nodeId=0
 <--END

**Comment by mgalati13** [comment]
Maybe step.id is not assigned for the start and end points and the nodeId=0 really is nodeId=3 when depot=3?

**Comment by jcoupey** [comment]
Thanks for sharing the problem description, however it's not something that can be easily reproduced. Can you please share a MWE of C++ client code to reproduce the problematic instance (or the json description counterpart)?

**Comment by hklarner** [comment]
(maybe a bit off topic, but I suggest creating a label "odd results" for this type of question where the user is surprised by the vroom result.)

**Comment by mgalati13** [comment]
I created a MWE, but I can no longer repeat the difference in behavior when using depot=0 vs depot=3. So, I assume my original code had a bug. 

It still might be worth looking at the test for the following:
(1) Notice that step.id for START and END are always 0, regardless of the depot value set. This is probably known behavior, but it was a little confusing at first - which took me down this path of wondering if depot !=0 works or not.
(2) For the tiny (sparse) example I give here, I would have expected the heuristic to be able to find a solution. I use a large constant cost for the edges that "don't exist" in the matrix. The only edges left form the only feasible routing. The solution is not found. 
[main.zip](https://github.com/VROOM-Project/vroom/files/7936758/main.zip)

**Comment by jcoupey** [comment]
The problem here is that you see your TW as not binding but it is in the sense that it does changes the feasibility somehow for job `3` that ends up unassigned.

The route `0-1-3-2-0` is indeed feasible but the simple `0-3-0` is not due to the prohibitive high durations. What happens is that [we mark this job as incompatible](https://github.com/VROOM-Project/vroom/blob/abc6c77710ddeac8e07fe264492d8c640b70212b/src/structures/vroom/input/input.cpp#L459-L501) with all vehicles because of that so it ends up unassigned. The rationale is that we consider a job to be incompatible with a vehicle if it does not fit on its own in a single-job route for this vehicle. This makes sense for all situations where you have real durations.

If you want to keep using arbitrary high prohibitive durations, then you have to extend the time windows: in your example, pushing the deadline from `100` to `1000` does solve the problem. Or even better yet, do not provide TW in the first place to default to no timing constraint.

**Comment by mgalati13** [comment]
@jcoupey In this case, I am trying to model the idea that the edge (0,3) is invalid. The vehicle is not allowed to traverse that edge. 

So, I set the cost matrix to some bigCost. And, duration=cost. For this case, I guess I want to set the duration to 0? The algorithm will still avoid the bigCost edge, but it will not mark job 3 invalid. 

Or, do you think it is best to give a duration for (0,3) as the duration for some path from 0 to 3? Or, is there some alternative way to mark certain edges invalid?

**Comment by mgalati13** [comment]
I guess set_extra_compatibility is assuming duration triangle inequality?

It assumes 0-3 is shorter than 0-1-3? So, if you can't reach 3 directly from 0 within the TW, the job is marked invalid. 

If so, that seems like a dangerous assumption considering real duration data? 0-3 might be a busy road, while 0-1 and 1-3 are not.

**Comment by jcoupey** [comment]
This choice is only made considering `0-3-0`: https://github.com/VROOM-Project/vroom/blob/abc6c77710ddeac8e07fe264492d8c640b70212b/src/structures/vroom/input/input.cpp#L479

Basically we assume that if a job does not fit in a route on its own, it's no use trying to put it along some others. This sounds like a sound assumption, even for real-life circumstances. The problem here is that your matrix does not reflect *real duration data*.

> 0-3 might be a busy road, while 0-1 and 1-3 are not.

Then the 0-3 matrix duration should in fact be the sum of the `0-1` and `1-3` travel time.

Put it differently: matrix values are not about roads, they are about durations for the shortest path (whatever the underlying steps).

**Comment by mgalati13** [comment]
So, when you calculate and check against time windows for some partial path between i and j, are you using duration[i,j] as the time spent on that partial path or are you using the sum of the edges on the partial path between i and j?

I thought duration[i,j] was similar to cost, in that it was the duration of traversing edge (i,j). Not the duration of traversing the Shortest Path between edge i and j. 

Isn't this necessary since we do not know which edges we will traverse a priori.

**Comment by jcoupey** [comment]
Travel time between jobs at index i and j is always `duration[i][j]` and those values are summed if there are several steps in a route.

My point is it does not make sense to have the `3-1-0-2-3` route take `1 + 1 + 1 + 1 = 4` while the duration for `3-0` only is 700.

**Comment by mgalati13** [comment]
OK. I just need to make sure the solution does not contain the edge 0-3. 

I will try to set cost(0,3)=bigCost and duration(0,3)=0. Does that seem reasonable? The algorithm should not select edge (0,3) in that case, and the preprocessing step based on time windows won't make job 3 invalid.

**Comment by jcoupey** [comment]
Yes it makes sense to adjust cost rather than duration here.

**Comment by mgalati13** [comment]
Is this the only place (depot,j) where this kind of reduction happens?

That is, do I need to adjust duration(i,j) for all edges (i,j) that are invalid? Or, just duration(depot,j)?
