### ISSUE TITLE
Limiting object dimensions and vehicle loading space dimensions

### ISSUE THREAD

**Issue by hugojanruiter** [VROOM-Project/vroom#660]
**Problem description**
We ship bulky goods with different vehicle sizes. Not all bulky goods (e.g. large sofa) fit each vehicle. We currently approximate this issue with a single value, volume, for capacity/amount, where we limit the capacity of the vehicle to 60% of the real volume to account for suboptimal packing. 

The problem we have is that some vehicles have enough volume, but an item still wont fit. E.g. loading space is 2.3m, 1.80m, 1.40m * 60% = 3.5m3 and a large table is 3m * 0.8m * 0.8m = 1.92m3. Since 1.92m3 < 3.5m3 it might end up in this vehicle, but it will never fit. 

We now account for this by doing some postprocessing, aka throwing out impossible solutions and retrying. 

**Modelling the problem with skills**
One option would be to use the skills for the largest dimension, e.g. if the vehicles loading space longest dimension is 2.3m we could add a skill for each dm of loading space
`vehicle.skills = [1,2,3,4,5,6....,21,22,23]`
and a job with longest dimension 1,20m
`job.skills`=[12]

This will quickly become quite a list for vehicles with larger loading spaces. Especially since we also use skills for different types of limitations. And it only solves for one dimension of the problem. 

Maybe we could do some other preprocessing that assigns skills to whether a job/shipment will fit a vehicle in the first place. But that will probably also turn out to provide a necessity for quite a large range of skills required. 

**Questions**
- Is there another/better way to model this problem?
- Is there a limit to modelling with skills this way? Can we safely use lists of more than 100 ints?

**Comment by jcoupey** [comment]
> Is there another/better way to model this problem?

Not really. As you clearly stated, you can't fully handle this with capacity constraints. Here "being able to handle a 3-meter long item" is more of a yes or no property, so it's natural to come up with skills, which would have been the approach I would have suggested if you didn't detail it yourself. ;-)

Now of course the granularity and number of metrics you need will highly impact the number of skills values you end up dealing with. There is no technical limitation but rather a problem of finding a model that serves your use-case well without introducing too much complexity.

> Is there a limit to modelling with skills this way? Can we safely use lists of more than 100 ints?

I guess your question is to know whether this could deteriorate the optimization performance, by e.g. adding lengthy array visits to decide on job/vehicle compatibility. The answer is no because we never go through the skills arrays for validity checks *while solving*. Instead, we [precompute a matrix describing vehicle/job compatibility](https://github.com/VROOM-Project/vroom/blob/abc6c77710ddeac8e07fe264492d8c640b70212b/src/structures/vroom/input/input.cpp#L436-L457) which is then exposed for [constant time compatibility checks](https://github.com/VROOM-Project/vroom/blob/abc6c77710ddeac8e07fe264492d8c640b70212b/src/structures/vroom/input/input.h#L124-L126). Since we only go through skills arrays once at startup the timing difference would barely be noticeable even with hundreds of skills values and hundred of vehicles.

> Maybe we could do some other preprocessing that assigns skills to whether a job/shipment will fit a vehicle in the first place. 

This is not an imperative necessity from the optimization point of view, now the question is whether this kind of preprocessing makes it easier or not to maintain your skills model in the long run.

**Comment by hugojanruiter** [comment]
Cool, thanks for the clear explanation. We will do some further tinkering with the skills to see what works best for our use case.
