### ISSUE TITLE
Re-using a vehicle across multiple routes

### ISSUE THREAD

**Issue by jack-premier** [VROOM-Project/vroom#664]
Hi,

Does the api currently support re-using a vehicle on multiple routes? For example, if a vehicle hits it's weight capacity with only a few jobs and finishes early, can it be configured to assign it to future routes (assuming the start/end are the same i guess).

I think it can re-run the planner multiple times, after adjusting the start/end times of the vehicle but i'm unsure if that would produce optimal results/ordering of the routes?

Thank you for this project - it's been really useful.

Thanks

**Comment by jcoupey** [comment]
If you're using jobs to model deliveries, then everything is implicitly loaded at startup so even if a vehicle finishes early due to limited capacity, there is no way it will handle more jobs later since that would make the route invalid. There are two options you can try to get multiple trips:
- define the same vehicle several times in input (with disjoint time windows), the limitation being that you have to decide/force the time windows before-hand;
- use shipments with all pickups located at your depot, the limitation being that you'll basically double the size of your problem.

**Comment by jack-premier** [comment]
Great, thanks for the reply, will give those options a go to see what gets better results for us.
