### ISSUE TITLE
Make `docs/example_2{,_sol}.json` more complete.

### ISSUE THREAD

**Issue by jonathf** [VROOM-Project/vroom#668]
Looks like we only look at routes when testing. The rest of the file has inaccuracy.
Is there a reason not to update example_2 and not test it in its entirety?

**Comment by jonathf** [comment]
Also as a followup: is it worth considering have a few testcases that demonstrates the difference in exploration mode?
Without examples it is hard to imagine what changing that parameter will to do the output.

**Comment by jcoupey** [comment]
> Looks like we only look at routes when testing.

Do you mean [this check](https://github.com/VROOM-Project/vroom/blob/9e0840c8432ed095cde99361532eb09e23f66dcb/.github/workflows/vroom.yml#L32)? If so this has been added because this check is used for the homebrew install (#318) and at some point we broke their install process by changing the file format and forgetting to update the example (#361).

> The rest of the file has inaccuracy.

No sure I get what you mean here?

**Comment by jcoupey** [comment]
On the broader subject of test-cases, the problem is that in order to demonstrate something regarding changes in exploration mode, you need real examples, not toy examples. Good candidates are existing VRP* benchmarks which we already use as functional tests (https://github.com/VROOM-Project/vroom#functional-tests). All those are already available in the `vroom-scripts` repo along with scripts to generate instances and run `vroom`.

**Comment by jonathf** [comment]
Okay, that puts that little thing into context.

I think for the Python side of things I will need to incorporate some of the faster funcitonal tests. This include testing, and demonstration purposes.

Is there any of the tests you think are particularly good for demostrational purposes?
Perhaps a select few that are small, but each demonstrating various core features?

**Comment by jcoupey** [comment]
> Is there any of the tests you think are particularly good for demostrational purposes?

All are relevant in some way since they are built to be representative of a given class of problems: capacity only, with time windows, pickup-and-delivery etc. For each benchmark there are usually different sub-classes for different sizes and different contexts (clustered locations vs random locations or a mix). You can definitely pick a few instances of each as a selection to showcase core features, which ones would be a matter of taste (you may want to use [this script](https://github.com/VROOM-Project/vroom-scripts/blob/master/src/plot.py) in order to see what solutions look like).

But while they are interesting from the optimization point of view, they are also on the other hand poor examples for users that aim at building real-life problems: matrices are always provided so there is no connection with routing, coordinates are usually integers in an arbitrary square, there is never a real mix of constraints and tasks even if we actually support mixing them, etc.

**Comment by jonathf** [comment]
Thanks you for the input. It is much appriciated.

I'll pick and choose some of them. I don't need to test the limit of vroom (that would be your job I suppose). I just need more than the super tiny examples in libvroom_example.
