### ISSUE TITLE
Exclude vehicle from returned geometry

### ISSUE THREAD

**Issue by ThomasRambaud** [VROOM-Project/vroom#670]
Dear Vroom team,
First of all, thanks for an awesome solution.

Is there any way to exclude the vehicle location from the geometry returned by vroom? I only want the pickups and deliveries in the geometry.

![image](https://user-images.githubusercontent.com/1260302/153471464-8a3cea7b-b223-49f9-833f-f79d0c3de7f0.png)

Regards,

**Comment by jcoupey** [comment]
There is no direct way to do get such a truncated geometry. Since we're returning the full encoded polyline from the routing engine we don't actually have a matching from tasks to a rank in the geometry.

The options I see are:
1. regenerate the piece of geometry you want by issuing a new routing request;
2. decode the polyline you have and use the rank of the point that is closest to your task location as start.

1 is clean and consistent by requires and additional (cheap) request, 2 is a bit hacky but would probably work in most situations.

**Comment by ThomasRambaud** [comment]
Hello @jcoupey , thank you for your quick answer.
Alright, I've gone to option #1 and it works fine!
Kind regards,
