### ISSUE TITLE
Solomon benchmark CVRPTW - question on customer ordering and random seeds

### ISSUE THREAD

**Issue by CosmoVal** [VROOM-Project/vroom#680]
Hi, 

I'm comparing Vroom with other solvers (incl. Google OR and others) on the 56 Solomon instances and I have few questions. 

Following the suggestion by Vidal 2022 (see ref), for some solver I'm running the calculation multiple times for each instance with different seeds (_"For KGLS and OR-tools, we use different random permutations of the customers in the data file, since these two algorithms are deterministic but depend on the order of the customers in the data (in this case, the permutation of the customers effectively acts as a seed")_.

My questions are:

1. Do the Vroom results **depends on the ordering** of the data (jobs, vehicles)? From my experiments, it seems yes.

2. If I run Vroom on the Solomon benchmarks as it is (without permutation), I get exactly the same results you're showing in the benchmark page. However, when I shuffle the customers (keeping the depot fixed being the first customer), the results are very different. The most concerning KPI is the number of **unassigned** job, that changes quite a bit (e.g. it's 0 without shuffle, sometimes goes up to 4). Are you using multiple random seeds on the **same shuffled instance** when compiling your benchmark page?

ref: same paper presents the SWAP* operator https://arxiv.org/pdf/2012.10384.pdf)

**Comment by jcoupey** [comment]
On 1: yes. For all sorting/choices based on a given criteria (most demanding capacity, earliest, closest, furthest etc.) there may be ties and changing the order in input can change which job is picked at a given point. Add to this other considerations on internal data structures (see #145).
This may happen also with vehicles to some extent but in the Solomon instances all vehicles are identical.

On 2: no, I haven't actually tried playing with shuffling the jobs for those benchmarks. I'm reporting results with the workflow (and scripts) described [here](https://github.com/VROOM-Project/vroom-scripts/tree/master/benchmarks/VRPTW).

Can you share how you generate the json instances? I don't quite see how you end up with unassigned jobs since in the original setup for the Solomon benchmark, vehicles are supposed to be unlimited. Most solving comparisons actually aims at first reducing the number of vehicles, see https://github.com/VROOM-Project/vroom-scripts/tree/master/benchmarks/VRPTW#optimization-objectives.

**Comment by CosmoVal** [comment]
Great feedback. 

Thanks to your comment I've actually found a bug in the shuffling process that was causing the unassigned jobs. 

I've fixed it and re-run the Solomon benchmark shuffling each instance 10 times (in other words, I have 10 runs for each problem) and now all jobs are always assigned.

The results look interesting, i'm sharing them here in case you're curious (numbers are already %). Two major comments:

- The averages results across the runs are pretty consistent with what you have in your benchmark page 
- There is some interesting variances, but overall everything looks pretty consistent 

<img width="245" alt="Screenshot 2022-03-03 at 15 49 44" src="https://user-images.githubusercontent.com/75121755/156588689-17141830-dea9-42a7-a0a2-69fadc7183fc.png">

I think you can close this issue

**Comment by jcoupey** [comment]
Thanks for the update and report! I would have been a bit surprised to see a huge difference in solution quality with shuffles on the Solomon benchmark.

Do you plan to publish the results of your tests in any way/format at some point? A comparison of both solution quality and computing times would be actually quite valuable, especially if you're including several solvers.

**Comment by CosmoVal** [comment]
I don't know it yet, but I can keep you posted on it. 

When considering the computing times, do you expect to see a relevant difference in the performances between the Docker deployment vs. the "build from source" installation?

**Comment by nilsnolde** [comment]
as long as you're running docker on a linux host there shouldn't be any penalty. only if on mac/win there will be hell to pay;) they're virtualizing, linux doesn't need to (with a linux-based image).

**Comment by CosmoVal** [comment]
ok, understood. Thanks!

**Comment by jcoupey** [comment]
Closing as answered. @CosmoVal still interested if you publish results/comparisons at some point!
