### ISSUE TITLE
Tracking packages width, height, length using capacity/amount

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#684]
Hello,

It seems that the capacity/amount multidimensional quantities are summed component wise, and therefore are best suited to tracking weight and volume (especially of liquids), or number of items, which can be summed.

Due to the above, checking whether a vehicle can hold another package defined by its three dimensions: width, height, and length, seems not possible, at least at the moment. Is this correct?

For example, if my vehicle has a 1m x 1m x 1m trunk and I want to pick up two 1m x 0.01m x 0.01m rods I will not be able to, because the engine will sum up the quantities to 2m, 0.02m, 0.02m, and the first one violates the capacity restriction.

I had a look at all the issues and one of them suggests using skills for modelling such case, but I need to use skills for other purpose.

Is there any way to overcome this?

**Comment by jcoupey** [comment]
> Due to the above, checking whether a vehicle can hold another package defined by its three dimensions: width, height, and length, seems not possible, at least at the moment. Is this correct?

Yep, you have to come up with a metric that makes sense in term of summing stuff up. If this comes from various dimensions, you have to do the math on your own.

For the record, deciding whether a set of packages fits would amount to solve a [bin packing problem](https://en.wikipedia.org/wiki/Bin_packing_problem). We can't really afford to solve an extra NP-hard problem each time we need to assert the validity of a route. ;-)

> I had a look at all the issues and one of them suggests using skills for modelling such case

Skills make sense if you have limitations like "not longer than", not for things that add up.

> I need to use skills for other purpose

You can definitely combine skills defined for various purposes in the same model.

> Is there any way to overcome this?

The easiest option here is to go for volume rather than dimensions, and maybe use some margin on vehicle capacity to account for those empty spaces when filling up.

**Comment by kkarbowiak** [comment]
Thank you for the clarification.

I am fully aware of the complexity of the bin packing problem, etc. On the other hand, do you think it would be possible and useful to extract handling of the capacities/amounts in the engine outside and make it a customization point?

That is, the engine would call user code to determine whether a new item fits in the vehicle, and each user could decide whether the extra complexity is still tractable or not.

**Comment by jcoupey** [comment]
For now I don't feel a strong need for such a generic way to handle amounts but as a first step you could insert your own logic on top of the current validity check code.

The amount definition is done [here](https://github.com/VROOM-Project/vroom/blob/master/src/structures/vroom/amount.h) using the CRTP. Capacity checks happen inside the [various `RawRoute::is_valid_addition_for_*` functions](https://github.com/VROOM-Project/vroom/blob/06af8717ec292a13ce2f7a9a541e41180b9c56da/src/structures/vroom/raw_route.h#L73-L106). Those are used in several ways depending on the context, the overall logic being a bit tricky since:
1. we account for backhauls, allowing to do both deliveries from start and pickup to the end, but also for temporary load from shipments;
2. we want validity checks to be as fast as possible (read: we don't need to go through the whole route to decide on validity) thanks to the use of data stored within routes and updated upon each route change.

**Comment by kkarbowiak** [comment]
Understood. Thank you again for all the explanation.

I guess I will try to experiment a bit, but for now I'm closing the issue since I got all the information.
