### ISSUE TITLE
Connection aborted by size of points 

### ISSUE THREAD

**Issue by fernandogonazales** [VROOM-Project/vroom#711]
Hello every one

I generated a local environment setting OSRM and Vroom with Docker. I'm making the queries in python and managing the data there.  The queries work well with a size of points lower than around 4,500. In greater cases  the environment collapses.  I don't know if it is a problem of hardware requirements, OSMR configuration, or Vroom configuration. I allocate 40 GB of RAM and a  Procesador Intel® Xeon. The limit matrix size of OSMR was set at 1,00,000.  

Does anybody have an idea of where can be the problem ?  I hope you can give me a clue.

Best regards,

**Comment by jcoupey** [comment]
Since you're seeing a size-related limitation, my first hint would be a RAM problem as the required amount required increases with the size of the matrices you have to deal with. Did you try monitoring RAM usage while performing successful and aborted requests?

I'm afraid we can't really help without more details, you'll have to dig a bit deeper in the stack to spot what actually fails. Is it OSRM, `vroom` or the `vroom-express` server, or your system killing the container for some reason?

**Comment by jcoupey** [comment]
Closing as stale.
