### ISSUE TITLE
Stops on vehicle splitting

### ISSUE THREAD

**Issue by Kirbylix** [VROOM-Project/vroom#725]
Hello,

we have about 400 stops & 7 vehicles for one day.

At the moment it is like this when we distribute the single stops to the vehicles. Are they distributed so that the vehicles are fully utilized. Then it can be that 1-3 have nothing to do.

But how can I distribute the stops so that ALL vehicles are equally utilized ?

Thanks already.

**Comment by jcoupey** [comment]
The main optimization objective is overall travel time and it's usually cheaper to use less vehicles. So if it's doable based on your constraints to perform all tasks with less vehicles than provided, it's an expected behavior to not use them all.

If you want all vehicles to be used, you can try adjusting the problem definition, using for example time windows, capacity, max tasks per vehicle etc. You may also be interested in #466 for a related discussion/solution.
