### ISSUE TITLE
Shipment with returning of goods/money

### ISSUE THREAD

**Issue by marcelbancila** [VROOM-Project/vroom#726]
Hello,

Is there a way to model returning of goods / money to the pickup location after delivery? I tried inserting a new shipment for return, but this does not guarantee that the return job is done by the same vehicle that did the delivery in a multi-vehicle scenario.

The scenario would imply multiple return shipments that can be done by the same vehicle, so there is no option to use the start and end coordinates of one vehicle.

Thank you,
Marcel

**Comment by jcoupey** [comment]
If you can model your problem using jobs instead of shipments, then this is supported since `job` objects can have `delivery` and `pickup` amounts. Both can be used for the same job, meaning that you first deliver stuff at a location, then load some other stuff to bring back at the end of the trip.

> I tried inserting a new shipment for return, but this does not guarantee that the return job is done by the same vehicle

The only way to guarantee that if using `shipment` objects would be to pin both tasks to a given vehicle using skills, but this requires to decide on task allocation before-hand.

**Comment by marcelbancila** [comment]
As far as I understand, using jobs will also not guarantee that the same vehicle does the second job (picking up goods/money from the delivery point) but instead, there is a great possibility that the optimization process will do it. Is this right?
