### ISSUE TITLE
Question: What do the numbers in the durations property mean?

### ISSUE THREAD

**Issue by mdanev** [VROOM-Project/vroom#742]
I'm trying to use `vroom` on top of `valhalla` with custom matrices. In the example that you provide for custom matrices there is a property `durations` with bunch of numbers inside. In the documentation it is stated that `location_index` references an element in the `durations` array but what are these numbers and how do they help with the computing of the cost?

**Comment by jcoupey** [comment]
Did you check the part on [input matrices](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#matrices) in the documentation?

**Comment by mdanev** [comment]
I did but this sentence is unclear to me `durations for a custom travel-time matrix that will be used for all checks against timing constraints`. It doesn't answer what the values in the property are. Also the example for custom matrices doesn't have `location` set, how does it know between which locations do i need the cost? And how do i change the profile from car to auto? `Valhalla` doesn't recognize the `car` profile.

**Comment by jcoupey** [comment]
The `durations` values are the travel times between all locations in the problem. If you have two jobs A and B with `location_index` 12 and 27, then `matrices.car.durations[12][27]` is the number of seconds it takes to go from A to B, using the `car` profile.

>And how do i change the profile from car to auto? Valhalla doesn't recognize the car profile.

If you use Valhalla, you probably want to forget all about custom matrices since VROOM is able to fetch the `durations` matrix from Valhalla for you. Check out [options](https://github.com/VROOM-Project/vroom/wiki/Usage#complete-usage-and-options-list-for-v1120), particularly `-r`, `-a` and `-p` to specify router and listening address/port per profile

**Comment by mdanev** [comment]
Going by your example i should specify the profile with `-a` i believe like so `-a car/bike/auto:0.0.0.0`. I've tried this with `auto:0.0.0.0` since its one of the profiles Valhalla mentions in their documentation but i still get this error.
```
[Error] Valhalla matrix error (No costing method found:'car').
{"code":3,"error":"Valhalla matrix error (No costing method found:'car')."}
``` 
This is the command I'm trying to run `./bin/vroom -a auto:0.0.0.0 -r valhalla -p 8002 -i test.json`

**Comment by mdanev** [comment]
Managed to get it working, thanks for the help.
