### ISSUE TITLE
optimization with the most suitable and smallest vehicle capacity first

### ISSUE THREAD

**Issue by felikhn** [VROOM-Project/vroom#744]
hi,
 i've json input as follow:

{"vehicles":[{"id":1,"start":[106.9582264,-6.3643348],"capacity":[1]},{"id":2,"start":[106.9582264,-6.3643348],"capacity":[3]}],"shipments":[{"amount":[1],"pickup":{"id":1,"location":[106.9582264,-6.3643348]},"delivery":{"id":2,"location":[106.9631312,-6.3331212]},"priority":0}],"options":{"g":true}}

and json output as follow:

{"code":0,"summary":{"cost":368,"routes":1,"unassigned":0,"delivery":[1],"amount":[1],"pickup":[1],"setup":0,"service":0,"duration":368,"waiting_time":0,"priority":0,"distance":4306,"violations":[],"computing_times":{"loading":710,"solving":2,"routing":745}},"unassigned":[],"routes":[{"vehicle":2,"cost":368,"delivery":[1],"amount":[1],"pickup":[1],"setup":0,"service":0,"duration":368,"waiting_time":0,"priority":0,"distance":4306,"steps":[{"type":"start","location":[106.9582264,-6.3643348],"setup":0,"service":0,"waiting_time":0,"load":[0],"arrival":0,"duration":0,"violations":[],"distance":0},{"type":"pickup","location":[106.9582264,-6.3643348],"id":1,"setup":0,"service":0,"waiting_time":0,"job":1,"load":[1],"arrival":0,"duration":0,"violations":[],"distance":0},{"type":"delivery","location":[106.9631312,-6.3331212],"id":2,"setup":0,"service":0,"waiting_time":0,"job":2,"load":[0],"arrival":368,"duration":368,"violations":[],"distance":4306},{"type":"end","location":[106.9631312,-6.3331212],"setup":0,"service":0,"waiting_time":0,"load":[0],"arrival":368,"duration":368,"violations":[],"distance":4306}],"violations":[]}]}

two vehicles with each capacity 1 and 3, and shipment amount 1, optimization results using a vehicle with a capacity of 3.

is it possible the result using a vehicle with a capacity of 1? since bigger capacity, higher cost
if possible, how to do that?

kindly  adv
thank You

**Comment by jcoupey** [comment]
This happens because while building the initial solution we're sorting vehicles based on reverse capacity:

https://github.com/VROOM-Project/vroom/blob/18c4290090370d71f7f2397c954d11e3a1e49e8d/src/algorithms/heuristics/heuristics.cpp#L79-L81

The rationale is that in a tight scenario with heterogeneous capacity and many tasks, building "bigger" routes first is more efficient. Now in your example of course this does not make any difference and the choice is somewhat arbitrary.

> since bigger capacity, higher cost

The neat solution here would be to have a way to express this notion of cost of using a different vehicle, a feature already ticketed in #528. For now, you have two ways to work around this:

- change the sort order described above (but depending on your use-case you may deteriorate results for more complex instances) ;
- switch vehicles as a post-processing step.

**Comment by felikhn** [comment]
what do you mean with "switch vehicles as a post-processing step"?

**Comment by jcoupey** [comment]
Simply that if after solving you spot that the route using a bigger vehicle could be performed with a smaller vehicle, you can simply use that vehicle instead for the rest of your workflow.

**Comment by felikhn** [comment]
Thank You
