### ISSUE TITLE
Question: imperative time passages

### ISSUE THREAD

**Issue by RussoNC** [VROOM-Project/vroom#751]
Hi everyone ! I've been working with Vroom recently for the first time, and there is a something I'm wondering.
Our client wants a truck to go do a job on a same location n times. We solved this by creating as many new jobs as the number of times the clients wants the truck to go.

But the other problem is that this location needs to be checked specifically x hours after the first one is done. Non less, non more. By default Vroom would return something like this :

          {
            "type": "job",
            "location": [
                ...
            ],
            "arrival": 30000,
            "duration": 244,
            "distance": 2436,
            "job": 1,
            "service": 300
          },
          {
            "type": "job",
            "location": [
                ...
            ],
            "arrival": 30300,
            "duration": 244,
            "distance": 2436,
            "job": 1001,
            "service": 300
          },
          {
            "type": "job",
            "location": [
                ...
            ],
            "arrival": 30600,
            "duration": 244,
            "distance": 2436,
            "job": 1002,
            "service": 300,
            "waiting_time": 600
          }

In this simple example we only have this recurrent job (main being 1) repeated as many times as the client needs to. I understand if there are tasks between both of them Vroom would add them, but it could also tell us that there is a waiting_time of x hours (this makes sense since Vroom is supposed to find the most efficient path). But in our use-case this is not possible, not more than 5 minutes.

What we did is to check the Vroom ouput and compute the difference between the arrival time of the n+1 and first job. If we don't have the desired "interval time" we modify our orignal request adding the missing time to the n+1 job. This is repeated until we get what we want. It works as it is, but I think there is a better way to do this, and to avoid sending requests to Vroom.

Any insight would be greatly appreciated

**Comment by jcoupey** [comment]
If you submit several jobs at the same place without any additional constraint, you'll probably end up having them done in a row just like in your output example, simply because it's the cheapest solution.

The only way we have to influence job service time is using time windows. In you case, you could probably define smallish time windows that are x hours apart for your duplicate jobs. The limitation is that you have to somehow decide approximate visit times beforehand.

**Comment by RussoNC** [comment]
> If you submit several jobs at the same place without any additional constraint, you'll probably end up having them done in a row just like in your output example, simply because it's the cheapest solution.
> 
> The only way we have to influence job service time is using time windows. In you case, you could probably define smallish time windows that are x hours apart for your duplicate jobs. The limitation is that you have to somehow decide approximate visit times beforehand.

Thank you for your answer !
I'm really sorry, just after reading your reply I realized that I forgot to mention that I'm actually using time windows. I know precicely when we want the patrols to go to those locations. Our main problem is that even if we set those, depending on the other calculated jobs, one patrol might have to wait more than 5 minutes in a place just because it's the cheapest option, instead of go and do others jobs that, even if further, it could be done. Our clients wants the patrols to be in constant move (as much as possible anyways). 
This is why we have to "force" vroom to re-compute, adding a few more minutes if this constraints are not respected, between the end of the job and the start of a new one. Of course if no other tasks are available to do a waiting time of more than 5 minutes is perfectly valid, although we didn't encounter this situation so far.
English's not my first language so I might have trouvel explaining my issue, I apologize for that, and thank you again for the reply.

**Comment by jcoupey** [comment]
>I realized that I forgot to mention that I'm actually using time windows

Don't worry about language, this is totally clear now!

Like you noticed, we'll tend to have vehicles wait in place between same-location visits (if possible) because it's cheapest. On the other hand we aim at maximizing the number of assigned tasks, so we'll also allow for vehicles to perform other jobs between the fixed passages *if there is no other option*. That last part is the key: you want to keep a balance between available resources (number of vehicles and total working hours) and tasks so that it forces the optimization to keep vehicles busy.
Put it differently: if you have idle vehicles, then you have an excess of resources. Finding the right balance sound like a business logic you should build on top of VROOM.

This being said, it's totally possible that some solutions with idle vehicles are actually better than when forcing vehicles to move around, even if this is not easy to accept in the field as it may sound counter-intuitive.

**Comment by RussoNC** [comment]
Oh I understand ! I will be refactoring the code to give vroom a better input, thank you for your time !
