### ISSUE TITLE
Doesn't work without "Jobs"

### ISSUE THREAD

**Issue by zenmobileagency** [VROOM-Project/vroom#779]
Hello.
Help. I'm trying to run routing without the jobs array since I only need Shipments. But the API returns:

> code: 2
> error: "Invalid JSON object in request, please add jobs and vehicles to the object body"

I use OSRM

Tnx!

**Comment by jcoupey** [comment]
This has nothing to do with `vroom` as this error is sent by `vroom-express` [here](https://github.com/VROOM-Project/vroom-express/blob/8326c0b8969a6b010b1bf331712f586c02f5ea13/src/index.js#L49). "Invalid JSON object in request" means that, well, you're probably sending invalid json so you want to first check the payload you're using.

The error only mentioning jobs (and not shipments) seems to indicate you're using an old version since the error in above link is different.

**Comment by vladimir2t** [comment]
> 

Thanks for the help!
