### ISSUE TITLE
`Input` keeps both zero amount and its size

### ISSUE THREAD

**Issue by kkarbowiak** [VROOM-Project/vroom#781]
The `Input` class keeps two sources of truth about the amount size: `_amount_size` and `_zero`.

I propose to remove the `_amount_size` member, as the size can be queried from `_zero`, and switch from passing the amount size to several functions to passing the zero amount directly. This way more code can be oblivious to the fact that the amount has some dimensions.

**Comment by jcoupey** [comment]
Thanks for pointing this out. While I agree it would be clearer and simpler to have a single source in `Input`, I not convinced that passing the zero amount instead of the amount size would actually make client code easier. Bottom line is: if you pass the zero amount yourself in functions, you still have to create it based on amount size. I'll comment further in the PR.

**Comment by kkarbowiak** [comment]
I'm closing this as I have also closed the associated PR.
