### ISSUE TITLE
Vehicle costs factor

### ISSUE THREAD

**Issue by qwelias** [VROOM-Project/vroom#783]
I've been just looking through sources and it seems like it should be fairly simple to implement `costs_factor` for `vehicle` input similarly to `speed_factor` using `CostWrapper::set_costs_factor`.

In practice it would help avoid creating custom profiles (with scaled costs matrices) per vehicle (which break `-g` flag usage).

Is there any particular reason it wasn't implemented?
Is there any reason for limiting `speed_factor` to `(0, 5]` range?
Should same range limit apply to `costs_factor`?

**Comment by jcoupey** [comment]
> Is there any particular reason it wasn't implemented?

Yes. The `speed_factor` parameter was introduced to account for small variations in speeds across different vehicles in order to get better time estimates. It was not intended as a way to adjust the optimization objective. I'm reluctant to introduce a `cost_factor` parameter for two reasons.

1. It would mess with any further change we may want to do on costs. Say for example if at some point we want edge costs to be a vehicle-dependent linear combination of travel time and distance.
2. It would only really be meaningful when using custom matrices since when *not* using them, costs are currently equal to travel times, which are already scaled with `speed_factor`. So it would only be a helper for something you can already do externally by providing your own scaled matrices as custom matrices.

> Is there any reason for limiting speed_factor to (0, 5] range?

See https://github.com/VROOM-Project/vroom/issues/591.

> Should same range limit apply to costs_factor?

If you go on and implement this for your own use-case, then you'll run into the same numerical concerns detailed in the above ticket.

**Comment by qwelias** [comment]
> It would mess with any further change we may want to do on costs. Say for example if at some point we want edge costs to be a vehicle-dependent linear combination of travel time and distance.

Are there any plans? Wouldn't it mess with costs matrix and `speed_factor` anyway then?

**Comment by qwelias** [comment]
My point is that current implementation already does cost factor and speed factor which mess with durations/costs anyway.
What I'm trying to solve is make the behavior more explicit and controllable by decoupling costs factor from speed factor

**Comment by qwelias** [comment]
> So it would only be a helper for something you can already do externally by providing your own scaled matrices as custom matrices.

True, but it's in exchange for more complicated input (which may require increasing max input size limit) and not being able to use `-g` flag

**Comment by jcoupey** [comment]
> What I'm trying to solve is make the behavior more explicit and controllable by decoupling costs factor from speed factor

If you're using custom matrices, then costs and speeds are already decoupled anyway. My point is that adding a `cost_factor` would not add anything *feature-wise* as you can already use arbitrary scaling in your own cost logic. We want to avoid the burden of an internal complexity (and maintaining it in the long run) for something that is already doable.

> not being able to use -g flag

Not true. Say you use profiles `my-profile`, `my-profile-scaled-1` and `my-profile-scaled-2` to submit variants of the costs matrices, then you can have all those profiles point to the same routing endpoint, see `-a` and `-p` flags.

**Comment by jcoupey** [comment]
> how to pass multiple profiles to vroom-express?

The default values are set in `config.yml`, then of course you can add any ad-hoc logic to define multiple profiles directly from javascript, same as you would add arbitrary `-a` and `-p` parameters when using command-line.
