### ISSUE TITLE
Start step arrival way after vehicle's time_window begin

### ISSUE THREAD

**Issue by manuel-ch** [VROOM-Project/vroom#790]
We see route steps of type "start" with arrival later than the vehicle's time_window begin. We'd expect the start step to start when the vehicle's time_window starts.

I guess that reflects an optimizer rule, but can't figure out which.

Input vehicle: `{
			"id": 1,
			"profile": "driving-car",
			"start": [
				11.5844,
				48.1593
			],
			"end": [
				11.5844,
				48.1593
			],
			"time_window": [
				28820,
				68420
			],
			"breaks": [],
		}`
Output step: `				{
					"type": "start",
					"location": [
						11.5844,
						48.1593
					],
					"arrival": 30607,
					"duration": 0
				},`

Happy to add more context if required.

**Comment by jcoupey** [comment]
This usually happens when you have timing constraints down the line. For example if the vehicle TW starts at 8:00 but the TW  for first job starts at 10:00 and the drive is 30 minutes: then starting at 8:00 and arriving at 8:30 would result in 1.5 hours of waiting time.

The scheduling logic is done in such a way that we arrive ASAP for the last task, then start at the latest possible time to match that arrival. In other words, starting earlier would not improve completion time but only add waiting time along the route.

**Comment by nemosmithasf** [comment]
@jcoupey - just to clarify, is `arrival` and `waiting_time` effectively synonymous for a `start` step? (i.e. it's saying we should wait until `arrival` before departing)

**Comment by jcoupey** [comment]
As a general rule, `arrival` is the step ETA. This may be different from the beginning of the step task in case of waiting time, so the beginning of tasks is `arrival + waiting_time` in general. Now `start` steps never have any waiting time, so `waiting_time` will always be zero and `arrival` is the time where the start occurs.
