### ISSUE TITLE
Access to the Valhalla matrix object from C++

### ISSUE THREAD

**Issue by FranckRobin** [VROOM-Project/vroom#793]
Vroom associated with Valhalla fit well my need, but they begin to be too slow when dealing with travel time tables above 50x50. Most of the time being spent in the "loading" step, would it be possible to build Vroom with Valhalla and directly access to the Valhalla matrix object from C++ as done for OSRM with libosrm?
Thank you by advance for your help.

**Comment by jcoupey** [comment]
This could definitely make sense when wanting to speed-up exchanges between Valhalla and VROOM. It would require to implement a new routing wrapper similar to the `libosrm_wrapper` we have. Some stuff would also be needed on the build side to correctly link to Valhalla as a C++ library.

This being said, I think you should first benchmark computing times to spot the actual bottleneck. For OSRM in some situations serializing the matrices to json and sending them over http is actually longer than computing them so using it as a library from VROOM makes a significant difference. But that's because OSRM is built to be fast on computing matrices in the first place.

For Valhalla, I'd expect the bottleneck to be rather the matrix computing time itself rather than the time it takes to use it from VROOM. Of course speeding things up can only help, but my point is that it may not significantly raise the limit anyway.

When I mean benchmarking, I'd suggest to:

1. Run VROOM with your current Valhalla setup on a representative set of your instances to lookup `summary.computing_times.loading` values (this includes parsing the VRP problem, doing some pre-calculations, sending the matrix request to the routing engine and parsing its response).
2. For each instance, compare the VROOM loading time with the matrix computing time from Valhalla logs. The difference will mostly be http overhead + matrix parsing on the VROOM side.
3. Run the same Valhalla matrix queries directly from C++ and monitor computing time. The difference will be the serialization time for Valhalla in C++.

That last bit is probably trickier but it's probably worth digging to know what gains you could achieve to see whether it's worth the trouble.

**Comment by nilsnolde** [comment]
IMO you can save the time to compare performance (Valhalla maintainer here): the problem is the matrix computation. It’s not built for performance, it’s built for flexibility. There’s hardly a (realistic) way for speed up’s on magnitude levels. You can have a look at a few closed/open issues in Valhalla to get some background on why. 

That being said, I toyed around with the idea as well, to integrate both on the C++ level. It’s fairly easily possible, but it’s not as nice to integrate as OSRM for various reasons. For me it’d mostly make sense for embedded applications. Didn’t have that use case yet myself, and I’d move mostly interested to embed the libraries of OSRM and Valhalla into the VROOM Python bindings which is quite a bit harder.

**Comment by FranckRobin** [comment]
Thanks a lot @jcoupey and @nilsnolde for your fast, detailed and useful answers!
Indeed after quickly looking at the VROOM `summary.computing_times.loading` and the Valhalla log file, 99% of the time is the matrix computation.
Even if not with magnitude levels, would there be a way to speed up the matrix computation time? more threads, less precision, ... ? I likely missed that, but did I not find this in the Valhalla documentation or discussions.
(I understand that this last question is not directly in the VROOM scope)

**Comment by nilsnolde** [comment]
Depending on the exact use case, it is possible to speed up the computation somewhat. You can contact me on enquiry@gis-ops.com if you need some professional support.

**Comment by jcoupey** [comment]
I think it's safe to close here as the proposed change would not really solve the full issue. If anyone wishes to work on this though, feel free to reopen and submit a PR.
