### ISSUE TITLE
Priority management for delivery first and pickup last

### ISSUE THREAD

**Issue by TEMAROUTE** [VROOM-Project/vroom#803]
I am trying to solve routes for which i am submitting a list of jobs having both deliveries and pickup. Sometimes, the deliveries and pickup are for same locations, sometimes, they are distinct locations. Setting higher PRIORITY for DELIVERY and  lower priority for PICKUP, I would expect the SOLVER to return ROUTES where deliveries are always processed first (routes with deliveries in first sequences...). But this does not seem to work with usage of PRIORITY. Any feedback on how to resolve some jobs first would be hight appreciated. Thanks.

**Comment by jcoupey** [comment]
Tasks priority is not about timing, see [the docs explanation](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#task-priorities).

There is currently no other way to achieve this than setting different TW for delivery and pickup jobs. The good news is that once #786 is implemented, you should be able to trick VROOM into inserting a low-load break in the middle of the route, resulting in (most) deliveries happening before the break and (most) pickups after.

**Comment by aardvarkk** [comment]
@jcoupey I'm also interested in being able to model this sort of problem in VROOM ("all deliveries before any pickups"). 

I had two questions:

1. It sounds like you're recommending the best approach to modeling this in the current version would be to manipulate time windows for deliveries and pickups to try to have them temporally separate. So the idea would be a kind of "meta optimization" where the user would run the optimization several times while tweaking that "break point" timing (the time window **close** for any delivery and the time window **open** for any pickup in this case) until, ideally, all stops were included and all deliveries took place before all pickups. Do you think that's the best way to accomplish this at the moment?

2. In the future, how do you imagine something like this being modeled in the optimizer (if at all)? It feels like the request in its most general form is to model **dependencies between jobs**. So job A might be able to say, "place me strictly before jobs [B, C, D]", and so on. Were this to be implemented, wouldn't such requirements potentially **speed up** the optimization by limiting the search space to only a subset of possibilities? I could take a look at what an implementation might look like if you were able to guide me towards some appropriate sections in the code where the changes might be placed.

**Comment by jcoupey** [comment]
> Do you think that's the best way to accomplish this at the moment?

Yes, but that is not very convenient nor flexible.

> In the future, how do you imagine something like this being modeled in the optimizer (if at all)?

My previous comment was probably not clear enough: if we have the ability to force a `max_load` value on breaks, then you can create a break with an empty `max_load`. This means that no pickup won't be possible until all deliveries are performed, or else the route would not be valid since the break wouldn't fit anywhere.

This is how [I intend](https://github.com/VROOM-Project/vroom-scripts/pull/47/commits/9c32daf708d0f01e3c5069f755203e7e3f8d68f1) to model VRPB (*vehicle routing problem with backhauls*) instances from the literature. As opposed to linehauls (regular deliveries from the depot), backhauls are pickups that need to be brought back at the end of the route and the VRPB problem description states that backhauls should only happen after linehauls in a route.

**Comment by jcoupey** [comment]
Closing as the modeling explained in my previous comment is now a thing in the v1.13 release candidates. See previous link and the [VRPB instances](https://github.com/VROOM-Project/vroom-scripts/tree/master/benchmarks/VRPB) for more.
