### ISSUE TITLE
Route calculation in rural, alpine area.

### ISSUE THREAD

**Issue by Doctor-N0** [VROOM-Project/vroom#808]
I currently use VROOM/OSRM for route calculations in rural areas in Austria. Due to the geographic situation, there are two additional constraints:
1.) Roads are very narrow, which means that the actual average speed is significantly below the legal speed limit. 
2.) Highways must be used preferentially (even if country roads would be "theoretically" faster).

I have tried to address these problems with an OSRM truck profile (see [this](https://github.com/Project-OSRM/osrm-backend/issues/5475) and [this ](https://github.com/Project-OSRM/osrm-profiles-contrib/tree/master/5/21/truck-soft) post). Are there any profiles provided by VROOM for this kind of problems, or is it advised to use the OSRM profiles? 

Thank you for your answers!

**Comment by jcoupey** [comment]
There is no such thing as a "VROOM profile" since we rely on the underlying routing engine to perform all routing choices. Once we get the travel time matrix describing all point-to-point costs, what is or is not a good routing choice is already decided.

You could always preprocess the matrix to do some adjustments and then feed it as a "costs" matrix to VROOM but I don't really see on what basis you could do this, so you're probably better off adjusting the routing profile itself. Point 1. and 2. from your description are typically things you'd want to improve in the OSRM profile, by changing some speeds or weights.

I'm not saying this is easy to handle from the profile, just that there is not much you can do on the VROOM level if at the routing level speeds are overestimated or the ETA take into account the "wrong" type of road.

**Comment by Doctor-N0** [comment]
Thanks so much!
