### ISSUE TITLE
Are results deterministic? If so, is it possible to set the seed?

### ISSUE THREAD

**Issue by nemosmithasf** [VROOM-Project/vroom#834]
I see that according to #145, VROOM results will differ depending on the environment. But given the same environment, are results guaranteed to be deterministic?

Also, would it be possible to force VROOM to give differing results? The use-case would be trying to brute force an alternative solution when the default solution isn't satisfactory.

**Comment by jcoupey** [comment]
> given the same environment, are results guaranteed to be deterministic?

Yes, running several times on the same problem will always trigger the same search path on the same setup. We don't use any stochastic decision-making internally, so there is no seed that you could adjust to generate another search.

We have a number of solutions at hand while solving so technically you could get a set of solutions out of VROOM, the problem is:
- they would be worse based on the optimization objective;
- there is no reason those solutions would be "more satisfactory" than the one we output in the first place.

Can you elaborate on what isn't satisfactory for your use-case? It looks like you may want to adjust the constraints.

**Comment by nemosmithasf** [comment]
My problem requires that two vehicles are not at the same location (i.e. job) at the same time. I don't believe this is a supported feature, so I was planning to just brute force it by generating "good enough" solutions until I find one where this was true.

**Comment by jcoupey** [comment]
We don't have any built-in way to achieve this so your best bet is to either find a modelling workaround or solve variants of the problem to pick from various solutions.
