### ISSUE TITLE
Distance matrix structure

### ISSUE THREAD

**Issue by LeoAlle** [VROOM-Project/vroom#846]
Hi,
if my distance matrix doesn't respect the triangular inequality what is the solver's behaviour? Is it going to use the shortest path to go from a point to another one or is it going to use the distance between the 2 points no matter what?

**Comment by jcoupey** [comment]
No, we don't do any matrix treatment to find wanabee shortcuts. Whenever we need the cost/travel time between two locations, we just lookup the value in the matrix. The rationale is that if there are such violations, it is because it makes sense at the routing level, probably due to the routing optimization objective.

The code never relies on triangular inequality so you should be safe using such matrices (you'll probably get non-intuitive results though if violations are huge). A simple example of this is when removing a task from a valid route: if the triangular inequality holds, then we have a guarantee that all timing constraints are still valid. But in practice removing a job can increase the actual travel time between the job before and after and result in a TW violation for the job after. So we have checks to test for removal validity.

**Comment by LeoAlle** [comment]
Ok thank you @jcoupey,
I'll continue to use those kinds of matrice though.
So do you already have those kinds of validity checks implemented in the algorithm?

**Comment by jcoupey** [comment]
Yes, everything should work consistently, even when using matrices that do not fulfill the triangular inequality.

**Comment by LeoAlle** [comment]
Ok thank you @jcoupey
