### ISSUE TITLE
Custom working times for vehicles

### ISSUE THREAD

**Issue by Doctor-N0** [VROOM-Project/vroom#875]
I would like to let a few vehicles work the full day (e.g. 8:30 - 18:00), while other work only in the afternoon (e.g. 12:30-18:00). I understand that this can be archived by a different `time_window` in the [vehicle section](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md). To take the [example input](https://github.com/VROOM-Project/vroom/blob/master/docs/example_1.json):
```
  "vehicles": [
    {
      [...]
      "time_window": [
        1600416000,
        1600430400
      ]
    },
```
However, I couldn't find out how these times are defined. To take the example above, does 1600416000 mean 16:41:60 (sixteen - forty one and sixty seconds) ?

Thanks so much for your answers!

**Comment by kkarbowiak** [comment]
> However, I couldn't find out how these times are defined. To take the example above, does 1600416000 mean 16:41:60 (sixteen - forty one and sixty seconds) ?

The times are number of seconds since a common "now" moment.

For example if you define a time window as `[3600, 7200]`, it means the vehicle starts working in an hour and stops working in two hours.

The quoted example uses [UNIX timestamps](https://en.wikipedia.org/wiki/Unix_time) - the number of seconds since midnight Jan 1st 1970. This convention is useful if you want to use real calendar time as input. You could translate the example (using e.g. [this site](https://www.unixtimestamp.com/)) to `[8:00 Sep 18 2020, 12:00 Sep 18 2020]`.

I hope that helps.

**Comment by jcoupey** [comment]
Also summed up in the docs: https://github.com/VROOM-Project/vroom/blob/master/docs/API.md#time-windows

**Comment by Doctor-N0** [comment]
Thank you so much!
