### ISSUE TITLE
Prevent u-turns around jobs

### ISSUE THREAD

**Issue by fdalesio** [VROOM-Project/vroom#876]
Hello there,
we are using VROOM with a custom cost matrix, generated by a dedicated, home made, routing service.
I'm trying to find a way to prevent u-turns that generally happens around jobs.
I'm aware this should probably be handled on the routing service, but I'm struggling finding a way to model it in the cost matrix.

This is the output I'm getting now
![clipboard-202301191604-wrkvx](https://user-images.githubusercontent.com/5504031/213684343-ada82b4d-6fa3-4574-88e8-44511e16bff5.png)

As you can see, there are u-turns around job 4 and 9, and the overall route is not realistic.

Obvously, VROOM doesn't know that the solution has u-turns, but also the routing service is not aware of (as it doesn't know, at first, the jobs order).
If I increse the cost, for example, from 4 to 5, I'll penalize that route even when no u-turns are needed.
Even adjusting costs after VROOM propose u-turns (and optimize again) doesn't seem viable, as I'll penalize the route around 4 and 9.
Also, repeating optimizations doesn't seem a solution: what if the new order involves new u-turns?
Also consider that, usually, jobs are between 100 and 500..

So, we can implement every custom way of building the cost matrix, but it seems to me that there's no way to prevent u-turns around jobs.
Can you confirm that?
Is that something I'm missing?
Did you come up against this problem before?

Thank you very much

Francesco

**Comment by jcoupey** [comment]
I don't think there is a way around this either. You're basically asking for information that can't be embedded in a matrix of travel times between pair. In your example, the `4 -> 5` travel time should be smaller in `9 -> 4 -> 5` than in `3 -> 4 -> 5` because in the latter you'd have to go straight past 4 and make a detour to 5 to avoid the u-turn.

Put it differently: when you're talking u-turns, you're referring to topological information from the underlying routing network that is lost in the graph whose edges are described by the cost matrix.

The closest related thing that maybe could help here would be to force the approach side to the jobs. See e.g. the `approach=curb` option for OSRM.

For the record, this is why [we disable](https://github.com/VROOM-Project/vroom/blob/f563bc3a8d38cf0646cb2ef4a3ec5bf9b49c9cd8/src/routing/osrm_routed_wrapper.cpp#L22-L23) the `continue_straight` option in the OSRM routing request because this is the only way to have consistent travel times across `table` and `route` requests.

**Comment by fdalesio** [comment]
Thank you Julien, I'll check the approach=curb option for OSRM to get an idea..
