### ISSUE TITLE
Doxygen documents

### ISSUE THREAD

**Issue by SC-One** [VROOM-Project/vroom#885]
Thanks for a nice project; 
I think we need Doxygen documents.
Why? so many calsses are really hard to detect why exactly it created and what's its duty in the system. at all, if it's understandable, we should have Doxygen documents because we have none in the code level's documents?
I really like to add the documents, but I'm not fully aware of the class features and algorithm used. If you want, I will try to add the Doxygen documents, and you can modify which places are incorrect.I saw [the link](https://github.com/VROOM-Project/vroom/blob/master/docs/API.md) too (actually, I read approximately the whole of the documents).
Thanks.

**Comment by jcoupey** [comment]
Yes, a better codebase documentation would indeed be useful, at least to explain the main components and their respective roles. But in the light of #735 and other similar questions, I wonder if we should go with a fine-grain documentation per class or function, since in this case you still need to make your way through a lot of stuff to find relevant information and get the big picture.

Maybe it would be better to have a kind of high-level paper describing the solving approach, which could include pointers to the code and outline the main implementation choices.

**Comment by jcoupey** [comment]
Frankly I don't think I'll ever go around to doing this myself, and I don't see anyone else really taking care of it, anyway not since the nearly one year since this has been opened. Probably more realistic to close for clarity.
