### ISSUE TITLE
Make port optional for routers

### ISSUE THREAD

**Issue by nilsnolde** [VROOM-Project/vroom#947]
I weirdly never tried this, but currently it's not possible to use a public HTTPS routing server with vroom (at least for Valhalla we use a reverse proxy, so IP:port isn't an option). Should be pretty trivial to make the port optional, I'll take a stab at that later this week:)

**Comment by jcoupey** [comment]
Sounds like a good reason to allow *not* providing a port. The only question I see here is how to handle the default. The obvious (ideal) choice would be that not providing `-p` result in not using a port, but this would break the current behavior of using `5000` for OSRM. Rather handy when working locally with OSRM, and probably implicitly relied on by some users so we may want to be cautious changing that.

**Comment by nilsnolde** [comment]
How about port 0 to omit it and default 5000?

**Comment by jcoupey** [comment]
Yep, sounds good.

**Comment by jcoupey** [comment]
@nilsnolde while working on #956, I had to run a few requests to a Valhalla instance and I managed to fire them against the demo server using:

```
vroom -i test_valhalla.json -r valhalla -a pedestrian:valhalla1.openstreetmap.de -p pedestrian:443
```

So it looks like making the port optional is not necessary after all?

**Comment by nilsnolde** [comment]
Ah great:) Huh, maybe I tried port 80 and the redirection fails it? Or maybe I wasn't even trying it..Thanks for the notice, seems like we can close:)

**Comment by jcoupey** [comment]
The `HttpWrapper::send_then_receive` function is basically a wrapper around asio that performs the requests, and we have a [`ssl_send_then_receive` version](https://github.com/VROOM-Project/vroom/blob/master/src/routing/http_wrapper.cpp#L83) handling SSL. It's triggered if the port value is 443, see #289.

This being said, running `vroom -i test_valhalla.json -a pedestrian:valhalla1.openstreetmap.de -r valhalla -p pedestrian:80` does work too! Probably because http requests are accepted on your side and not redirected to https.

**Comment by nilsnolde** [comment]
Proves that I didn’t try it😅
