### ISSUE TITLE
Depot throughput

### ISSUE THREAD

**Issue by torinori** [VROOM-Project/vroom#994]
### Problem

You are given depot throughput in format of amount per second or vehicles per second. If depot is busy at the arrival of vehicle it should wait until 

The `depot throughput` is specified in the format `amount per second` or `vehicle per second`.
When a car arrives at a depot to pick up goods, it will load the depot by `pickup (amount) / service (duration)` of "work" for `service` seconds, if the load exceeds the `depot throughput`, then it must wait until the depot is free.

#### Given: 
10 shipments (pickup = depot location) with `amount = [4]` and service time `2 sec`
1 vehicle
1 depot with amount throughput [4] per second

#### Result:
```
Shipments #1, #2 will be processed immediately after arrival to depot,
shipments #3, #4 will be processed 2 sec after arrival
shipments #5, #6 will be processed 4 sec after arrival,
and so on.
```

#### What I need:
Let's assume I already implemented depot entity and throughput tracking. 
I need some suggestion how to implement restriction logic for vehicle waiting on depot.

**Comment by jcoupey** [comment]
Not sure if I fully grasp your problem, but my understanding is that you basically want a way to have the time spent on premises for a given pickup depend on:

1. whether other vehicles are currently at the depot;
2. the number of same-location tasks happening right before or after.

The hard part here is that the `service` time we ingest is fixed and both 1. and 2. cannot be decided before-hand since they vary with the current solution we have internally.

The closest you can get to 2. is by using a combination of `setup` and `service` time. The `setup` key was introduced exactly to provide a way to adjust the time spent for a tasks, which is decided dynamically based on whether the task happens at the same location as the previous one or at a different place.
